/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SIO"
 * 	found in "sio.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -no-gen-PER -pdu=all`
 */

#include "Key.h"

asn_TYPE_member_t asn_MBR_Key_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Key, referenceId),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"referenceId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Key, crypto),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"crypto"
		},
};
static const ber_tlv_tag_t asn_DEF_Key_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Key_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* crypto */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 } /* referenceId */
};
asn_SEQUENCE_specifics_t asn_SPC_Key_specs_1 = {
	sizeof(struct Key),
	offsetof(struct Key, _asn_ctx),
	asn_MAP_Key_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Key = {
	"Key",
	"Key",
	&asn_OP_SEQUENCE,
	asn_DEF_Key_tags_1,
	sizeof(asn_DEF_Key_tags_1)
		/sizeof(asn_DEF_Key_tags_1[0]), /* 1 */
	asn_DEF_Key_tags_1,	/* Same as above */
	sizeof(asn_DEF_Key_tags_1)
		/sizeof(asn_DEF_Key_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Key_1,
	2,	/* Elements count */
	&asn_SPC_Key_specs_1	/* Additional specs */
};

