/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SIO"
 * 	found in "sio.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -no-gen-PER -pdu=all`
 */

#ifndef	_PACS_H_
#define	_PACS_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PACS */
typedef struct PACS {
	OCTET_STRING_t	 payload;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PACS_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PACS;
extern asn_SEQUENCE_specifics_t asn_SPC_PACS_specs_1;
extern asn_TYPE_member_t asn_MBR_PACS_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _PACS_H_ */
#include <asn_internal.h>
