/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SIO"
 * 	found in "sio.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -no-gen-PER -pdu=all`
 */

#ifndef	_SIO_H_
#define	_SIO_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <NULL.h>
#include "Key.h"
#include "PACS.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SIO */
typedef struct SIO {
	OCTET_STRING_t	 rid;
	OCTET_STRING_t	*unknown3	/* OPTIONAL */;
	NULL_t	 unknown5;
	Key_t	 key;
	PACS_t	 pacs;
	NULL_t	 unknown9;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SIO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SIO;

#ifdef __cplusplus
}
#endif

#endif	/* _SIO_H_ */
#include <asn_internal.h>
