#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xff97;
constexpr uint24_t FX_DATA_BYTES = 18688;

constexpr uint16_t FX_SAVE_PAGE  = 0xffe0;
constexpr uint24_t FX_SAVE_BYTES = 8192;

constexpr uint24_t LEVELS_DEFAULT = 0x000000;
constexpr uint24_t SAVEDATA = 0x004900;
