#ifndef RAVKAV_LISTS_H
#define RAVKAV_LISTS_H

static const char* RAVKAV_ISSUERS_LIST[300] = {
    [0] = "undefined",
    [1] = "Service Center (Postal Bank)",
    [2] = "Israel Railways",
    [3] = "Egged",
    [4] = "Egged Transport",
    [5] = "Dan",
    [6] = "NTT (United Bus Services Nazareth)",
    [7] = "NTT (Nazareth Travel & Tourism)",
    [8] = "GB Tours",
    [9] = "Omni Nazrin Express (transferred to Nativ Express)",
    [10] = "Eilot Regional Council",
    [11] = "Illit (merged with Kavim)",
    [12] = "undefined 12",
    [13] = "undefined 13",
    [14] = "Nativ Express",
    [15] = "Metropoline",
    [16] = "Superbus",
    [17] = "Connex Veolia (transferred to Afikim)",
    [18] = "Kavim",
    [19] = "Metrodan (defunct, transferred to Dan Be\'er Sheva)",
    [20] = "Carmelit",
    [21] = "CityPass",
    [22] = "Tel Aviv Light Rail operator",
    [23] = "Galim (Narkis Gal)",
    [24] = "Golan Regional Council",
    [25] = "Afikim",
    [26] = "undefined 26",
    [27] = "undefined 27",
    [28] = "undefined 28",
    [29] = "undefined 29",
    [30] = "Dan North",
    [31] = "Dan South",
    [32] = "Dan Be\'er Sheva",
    [33] = "undefined 33",
    [34] = "undefined 34",
    [35] = "undefined 35",
    [36] = "undefined 36",
    [37] = "undefined 37",
    [38] = "undefined 38",
    [39] = "undefined 39",
    [40] = "undefined 40",
    [41] = "East Jerusalem operators",
    [42] = "Jerusalem - Ramallah united",
    [43] = "(obsolete) Jerusalem - Mahane Shuafat",
    [44] = "Jerusalem - Anata united",
    [45] = "Jerusalem - Isawiya united",
    [46] = "(obsolete) Jabal Al Muhbar Ltd",
    [47] = "Jerusalem - Mount of Olives",
    [48] = "(obsolete) Abu-Tor Siluan bus company",
    [49] = "Jerusalem - Isawiya - Mahane Shuafat united",
    [50] = "South Jerusalem united",
    [51] = "Jerusalem - Sur Baher united",
    [52] = "(obsolete) Ras-al Amud Izriya - Abu-Dis",
    [53] = "(obsolete) Jerusalem - A. Swahra united",

    [98] = "Tel Aviv Service Taxi Lines 4, 2 and 5",
    [240] = "[Technical] Service Center - Contract restores",
    [250] = "Israel Defence Forces"};

#endif // RAVKAV_LISTS_H
