[env:m5stack-atom]
platform = espressif32
board = m5stack-atom
framework = arduino
monitor_speed = 115200
build_flags =
    -D BOARD_M5STACK_ATOM
    -D CAN_DRIVER_TWAI
lib_deps =
    adafruit/Adafruit NeoPixel@^1.12.0
    Links2004/WebSockets@^2.4.0

[env:esp32-mcp2515]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -D BOARD_ESP32_GENERIC
    -D CAN_DRIVER_MCP2515
lib_deps =
    adafruit/Adafruit NeoPixel@^1.12.0
    autowp/autowp-mcp2515@^1.3.0
    Links2004/WebSockets@^2.4.0
src_dir = .firmware
