name: "Release"
run-name: "Release ${{ github.ref_name }}"

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and publish release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with ufbt
        id: build-app
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          sdk-index-url: https://up.unleashedflip.com/directory.json

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          files: ${{ steps.build-app.outputs.fap-artifacts }}
          fail_on_unmatched_files: true
