/* generated by fbt from .png files in images folder */
#include <chief_cooker_icons.h>

#include "app/App.hpp"

extern "C" int32_t chief_cooker_app(void* p) {
    UNUSED(p);

    App app;
    app.Run();

    return 0;
}
