/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Passport"
 * 	found in "eMRTD.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -pdu=all`
 */

#ifndef	_Application1_H_
#define	_Application1_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MRZ.h"
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum Application1_PR {
	Application1_PR_mrz,	/* Member mrz is present */
} Application1_PR;

/* Application1 */
typedef struct Application1 {
	MRZ_t	 mrz;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pApplication1, Application1_PR_x) */
	unsigned int _presence_map
		[((1+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Application1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Application1;

#ifdef __cplusplus
}
#endif

#endif	/* _Application1_H_ */
#include <asn_internal.h>
