/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Passport"
 * 	found in "eMRTD.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -pdu=all`
 */

#include "Application1.h"

static asn_TYPE_member_t asn_MBR_Application1_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Application1, mrz),
		(ASN_TAG_CLASS_APPLICATION | (31 << 2)),
		0,
		&asn_DEF_MRZ,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mrz"
		},
};
static const ber_tlv_tag_t asn_DEF_Application1_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Application1_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (31 << 2)), 0, 0, 0 } /* mrz */
};
static const uint8_t asn_MAP_Application1_mmap_1[(1 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(1 << 7)
};
static 
asn_SET_specifics_t asn_SPC_Application1_specs_1 = {
	sizeof(struct Application1),
	offsetof(struct Application1, _asn_ctx),
	offsetof(struct Application1, _presence_map),
	asn_MAP_Application1_tag2el_1,
	1,	/* Count of tags in the map */
	asn_MAP_Application1_tag2el_1,	/* Same as above */
	1,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(const unsigned int *)asn_MAP_Application1_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_Application1 = {
	"Application1",
	"Application1",
	&asn_OP_SET,
	asn_DEF_Application1_tags_1,
	sizeof(asn_DEF_Application1_tags_1)
		/sizeof(asn_DEF_Application1_tags_1[0]), /* 1 */
	asn_DEF_Application1_tags_1,	/* Same as above */
	sizeof(asn_DEF_Application1_tags_1)
		/sizeof(asn_DEF_Application1_tags_1[0]), /* 1 */
	{ 0, 0, SET_constraint },
	asn_MBR_Application1_1,
	1,	/* Elements count */
	&asn_SPC_Application1_specs_1	/* Additional specs */
};

