/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Passport"
 * 	found in "eMRTD.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -pdu=all`
 */

#include "COM.h"

static asn_TYPE_member_t asn_MBR_COM_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct COM, ldsVersion),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LDSVersion,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ldsVersion"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct COM, unicodeVersion),
		(ASN_TAG_CLASS_APPLICATION | (54 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UnicodeVersion,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"unicodeVersion"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct COM, dataGroups),
		(ASN_TAG_CLASS_APPLICATION | (28 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DataGroups,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dataGroups"
		},
};
static const ber_tlv_tag_t asn_DEF_COM_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_COM_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 0, 0, 0 }, /* ldsVersion */
    { (ASN_TAG_CLASS_APPLICATION | (28 << 2)), 2, 0, 0 }, /* dataGroups */
    { (ASN_TAG_CLASS_APPLICATION | (54 << 2)), 1, 0, 0 } /* unicodeVersion */
};
static asn_SEQUENCE_specifics_t asn_SPC_COM_specs_1 = {
	sizeof(struct COM),
	offsetof(struct COM, _asn_ctx),
	asn_MAP_COM_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_COM = {
	"COM",
	"COM",
	&asn_OP_SEQUENCE,
	asn_DEF_COM_tags_1,
	sizeof(asn_DEF_COM_tags_1)
		/sizeof(asn_DEF_COM_tags_1[0]) - 1, /* 1 */
	asn_DEF_COM_tags_1,	/* Same as above */
	sizeof(asn_DEF_COM_tags_1)
		/sizeof(asn_DEF_COM_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_COM_1,
	3,	/* Elements count */
	&asn_SPC_COM_specs_1	/* Additional specs */
};

