/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Passport"
 * 	found in "eMRTD.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -pdu=all`
 */

#ifndef	_COM_H_
#define	_COM_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LDSVersion.h"
#include "UnicodeVersion.h"
#include "DataGroups.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* COM */
typedef struct COM {
	LDSVersion_t	 ldsVersion;
	UnicodeVersion_t	 unicodeVersion;
	DataGroups_t	 dataGroups;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} COM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_COM;

#ifdef __cplusplus
}
#endif

#endif	/* _COM_H_ */
#include <asn_internal.h>
