/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Passport"
 * 	found in "eMRTD.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -pdu=all`
 */

#ifndef	_DataGroups_H_
#define	_DataGroups_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DataGroups */
typedef OCTET_STRING_t	 DataGroups_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DataGroups;
asn_struct_free_f DataGroups_free;
asn_struct_print_f DataGroups_print;
asn_constr_check_f DataGroups_constraint;
ber_type_decoder_f DataGroups_decode_ber;
der_type_encoder_f DataGroups_encode_der;
xer_type_decoder_f DataGroups_decode_xer;
xer_type_encoder_f DataGroups_encode_xer;
oer_type_decoder_f DataGroups_decode_oer;
oer_type_encoder_f DataGroups_encode_oer;
per_type_decoder_f DataGroups_decode_uper;
per_type_encoder_f DataGroups_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DataGroups_H_ */
#include <asn_internal.h>
