/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Passport"
 * 	found in "eMRTD.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -pdu=all`
 */

#ifndef	_DG1_H_
#define	_DG1_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MRZ.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DG1 */
typedef struct DG1 {
	MRZ_t	 mrz;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DG1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DG1;

#ifdef __cplusplus
}
#endif

#endif	/* _DG1_H_ */
#include <asn_internal.h>
