/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Passport"
 * 	found in "eMRTD.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -pdu=all`
 */

#include "DG1.h"

static asn_TYPE_member_t asn_MBR_DG1_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DG1, mrz),
		(ASN_TAG_CLASS_APPLICATION | (31 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MRZ,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mrz"
		},
};
static const ber_tlv_tag_t asn_DEF_DG1_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DG1_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (31 << 2)), 0, 0, 0 } /* mrz */
};
static asn_SEQUENCE_specifics_t asn_SPC_DG1_specs_1 = {
	sizeof(struct DG1),
	offsetof(struct DG1, _asn_ctx),
	asn_MAP_DG1_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_DG1 = {
	"DG1",
	"DG1",
	&asn_OP_SEQUENCE,
	asn_DEF_DG1_tags_1,
	sizeof(asn_DEF_DG1_tags_1)
		/sizeof(asn_DEF_DG1_tags_1[0]) - 1, /* 1 */
	asn_DEF_DG1_tags_1,	/* Same as above */
	sizeof(asn_DEF_DG1_tags_1)
		/sizeof(asn_DEF_DG1_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_DG1_1,
	1,	/* Elements count */
	&asn_SPC_DG1_specs_1	/* Additional specs */
};

