/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Passport"
 * 	found in "eMRTD.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -pdu=all`
 */

#ifndef	_LDSVersion_H_
#define	_LDSVersion_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LDSVersion */
typedef VisibleString_t	 LDSVersion_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LDSVersion_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LDSVersion;
asn_struct_free_f LDSVersion_free;
asn_struct_print_f LDSVersion_print;
asn_constr_check_f LDSVersion_constraint;
ber_type_decoder_f LDSVersion_decode_ber;
der_type_encoder_f LDSVersion_encode_der;
xer_type_decoder_f LDSVersion_decode_xer;
xer_type_encoder_f LDSVersion_encode_xer;
oer_type_decoder_f LDSVersion_decode_oer;
oer_type_encoder_f LDSVersion_encode_oer;
per_type_decoder_f LDSVersion_decode_uper;
per_type_encoder_f LDSVersion_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LDSVersion_H_ */
#include <asn_internal.h>
