/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Passport"
 * 	found in "eMRTD.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -pdu=all`
 */

#ifndef	_MRZ_H_
#define	_MRZ_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MRZ */
typedef VisibleString_t	 MRZ_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_MRZ_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_MRZ;
asn_struct_free_f MRZ_free;
asn_struct_print_f MRZ_print;
asn_constr_check_f MRZ_constraint;
ber_type_decoder_f MRZ_decode_ber;
der_type_encoder_f MRZ_encode_der;
xer_type_decoder_f MRZ_decode_xer;
xer_type_encoder_f MRZ_encode_xer;
oer_type_decoder_f MRZ_decode_oer;
oer_type_encoder_f MRZ_encode_oer;
per_type_decoder_f MRZ_decode_uper;
per_type_encoder_f MRZ_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MRZ_H_ */
#include <asn_internal.h>
