/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Passport"
 * 	found in "eMRTD.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -pdu=all`
 */

#ifndef	_UnicodeVersion_H_
#define	_UnicodeVersion_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UnicodeVersion */
typedef VisibleString_t	 UnicodeVersion_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_UnicodeVersion_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_UnicodeVersion;
asn_struct_free_f UnicodeVersion_free;
asn_struct_print_f UnicodeVersion_print;
asn_constr_check_f UnicodeVersion_constraint;
ber_type_decoder_f UnicodeVersion_decode_ber;
der_type_encoder_f UnicodeVersion_encode_der;
xer_type_decoder_f UnicodeVersion_decode_xer;
xer_type_encoder_f UnicodeVersion_encode_xer;
oer_type_decoder_f UnicodeVersion_decode_oer;
oer_type_encoder_f UnicodeVersion_encode_oer;
per_type_decoder_f UnicodeVersion_decode_uper;
per_type_encoder_f UnicodeVersion_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UnicodeVersion_H_ */
#include <asn_internal.h>
