#include "tpms_proto.h"

/* The protocol table.
 *
 * chip_us is the chip duration the decoder quantises intervals with.
 * rtl_433 lists 49, 50, 51 and 52 us for what is the same 20 kBaud
 * family; those are rounded to two rates here, because every distinct
 * rate costs another set of shift registers on every interval, and a two
 * percent error is far inside what rounding a run of one or two chips can
 * absorb.
 *
 * sync is written as the decoder wants to see the payload. Where rtl_433
 * inverts the whole buffer before searching, the sync word here is
 * inverted to match, and the engine tries both polarities anyway.
 *
 * capture_bits is how many slicer bits the payload needs: twice the data
 * bits for Manchester coding, and a little more where the coding needs
 * room to find its footing.
 */

const TpmsProtocol tpms_protocols[] = {
    {
        .id = "renault",
        .label = "Renault",
        .chip_us = 52,
        .modulation = TpmsModulationFsk,
        .slicer = TpmsSlicerNrz,
        .id_digits = 6,
        .sync = 0xAAAA9,
        .sync_bits = 20,
        .capture_bits = 144,
        .decode = tpms_decode_renault,
    },
    {
        .id = "renault0435r",
        .label = "Renault 0435R",
        .chip_us = 52,
        .modulation = TpmsModulationFsk,
        .slicer = TpmsSlicerNrz,
        .id_digits = 6,
        .sync = 0xAAAA9,
        .sync_bits = 20,
        .capture_bits = 144,
        .decode = tpms_decode_renault_0435r,
    },
    {
        .id = "citroen",
        .label = "Citroen/PSA",
        .chip_us = 52,
        .modulation = TpmsModulationFsk,
        .slicer = TpmsSlicerNrz,
        .id_digits = 8,
        .sync = 0xAAAA9,
        .sync_bits = 20,
        .capture_bits = 176,
        .decode = tpms_decode_citroen,
    },
    {
        .id = "ford",
        .label = "Ford",
        .chip_us = 52,
        .modulation = TpmsModulationFsk,
        .slicer = TpmsSlicerNrz,
        .id_digits = 8,
        .sync = 0xAAAA9,
        .sync_bits = 20,
        .capture_bits = 128,
        .decode = tpms_decode_ford,
    },
    {
        .id = "toyota",
        .label = "Toyota",
        .chip_us = 52,
        .modulation = TpmsModulationFsk,
        .slicer = TpmsSlicerNrz,
        .id_digits = 8,
        .sync = 0x54F,
        .sync_bits = 11,
        .capture_bits = 160,
        .decode = tpms_decode_toyota,
    },
    {
        .id = "vdo_tg1c",
        .label = "VDO TG1C",
        .chip_us = 52,
        .modulation = TpmsModulationFsk,
        .slicer = TpmsSlicerNrz,
        .id_digits = 8,
        .sync = 0xAAAAA9,
        .sync_bits = 24,
        .capture_bits = 144,
        .decode = tpms_decode_abarth124,
    },
    {
        .id = "egq_q85",
        .label = "EGQ Q85",
        .chip_us = 52,
        .modulation = TpmsModulationFsk,
        .slicer = TpmsSlicerNrz,
        .id_digits = 8,
        .sync = 0xAAAAA9,
        .sync_bits = 24,
        .capture_bits = 192,
        .decode = tpms_decode_egq_q85,
    },
    {
        .id = "jansite",
        .label = "Jansite TY02S",
        .chip_us = 52,
        .modulation = TpmsModulationFsk,
        .slicer = TpmsSlicerNrz,
        .id_digits = 7,
        .sync = 0xAAAAAAA9,
        .sync_bits = 32,
        .capture_bits = 112,
        .decode = tpms_decode_jansite,
    },
    {
        .id = "jansite_solar",
        .label = "Jansite Solar",
        .chip_us = 50,
        .modulation = TpmsModulationFsk,
        .slicer = TpmsSlicerNrz,
        .id_digits = 6,
        .sync = 0xA6A65A5A,
        .sync_bits = 32,
        .capture_bits = 144,
        .decode = tpms_decode_jansite_solar,
    },
    {
        .id = "jansite_ty588",
        .label = "Jansite TY588",
        .chip_us = 50,
        .modulation = TpmsModulationFsk,
        .slicer = TpmsSlicerNrz,
        .id_digits = 6,
        .sync = 0x99AA5A6A9AAULL,
        .sync_bits = 44,
        .capture_bits = 128,
        .decode = tpms_decode_jansite_ty588,
    },
    {
        .id = "porsche",
        .label = "Porsche",
        .chip_us = 52,
        .modulation = TpmsModulationFsk,
        .slicer = TpmsSlicerNrz,
        .id_digits = 8,
        .sync = 0x33332,
        .sync_bits = 20,
        .capture_bits = 168,
        .decode = tpms_decode_porsche,
    },
    {
        .id = "truck",
        .label = "Truck solar",
        .chip_us = 52,
        .modulation = TpmsModulationFsk,
        .slicer = TpmsSlicerNrz,
        .id_digits = 8,
        .sync = 0xAAAAA9,
        .sync_bits = 24,
        .capture_bits = 152,
        .decode = tpms_decode_truck,
    },
    {
        .id = "hyundai_vdo",
        .label = "Hyundai VDO",
        .chip_us = 52,
        .modulation = TpmsModulationFsk,
        .slicer = TpmsSlicerNrz,
        .id_digits = 8,
        .sync = 0xAAAAAAA9,
        .sync_bits = 32,
        .capture_bits = 160,
        .decode = tpms_decode_hyundai_vdo,
    },
    {
        .id = "elantra2012",
        .label = "Elantra 2012",
        .chip_us = 50,
        .modulation = TpmsModulationFsk,
        .slicer = TpmsSlicerNrz,
        .id_digits = 8,
        .sync = 0x7155,
        .sync_bits = 16,
        .capture_bits = 128,
        .decode = tpms_decode_elantra2012,
    },
    {
        .id = "honda",
        .label = "Honda TRW",
        .chip_us = 50,
        .modulation = TpmsModulationFsk,
        .slicer = TpmsSlicerNrz,
        .id_digits = 8,
        .sync = 0x6D71AA,
        .sync_bits = 23,
        .capture_bits = 128,
        .decode = tpms_decode_honda,
    },
    {
        .id = "kia",
        .label = "Kia",
        .chip_us = 50,
        .modulation = TpmsModulationFsk,
        .slicer = TpmsSlicerNrz,
        .id_digits = 8,
        .sync = 0xED71,
        .sync_bits = 16,
        .capture_bits = 276,
        .decode = tpms_decode_kia,
    },
    {
        .id = "sefis_m3",
        .label = "Sefis M3",
        .chip_us = 52,
        .modulation = TpmsModulationFsk,
        .slicer = TpmsSlicerNrz,
        .id_digits = 6,
        .sync = 0x669996A6,
        .sync_bits = 32,
        .capture_bits = 144,
        .decode = tpms_decode_sefis_m3,
    },
    {
        .id = "airpuxem",
        .label = "Airpuxem",
        .chip_us = 52,
        .modulation = TpmsModulationFsk,
        .slicer = TpmsSlicerNrz,
        .id_digits = 8,
        .sync = 0xAAAAA9,
        .sync_bits = 24,
        .capture_bits = 176,
        .decode = tpms_decode_airpuxem,
    },
    {
        .id = "bmw_g3",
        .label = "BMW Gen2/3",
        .chip_us = 52,
        .modulation = TpmsModulationFsk,
        .slicer = TpmsSlicerNrz,
        .id_digits = 8,
        .sync = 0xCCCD,
        .sync_bits = 16,
        .capture_bits = 184,
        .decode = tpms_decode_bmw_g3,
    },
    {
        .id = "ave",
        .label = "AVE",
        .chip_us = 100,
        .modulation = TpmsModulationFsk,
        .slicer = TpmsSlicerNrz,
        .id_digits = 8,
        .sync = 0xCCCCCCCD,
        .sync_bits = 32,
        .capture_bits = 136,
        .decode = tpms_decode_ave,
    },
    {
        .id = "pmv107j",
        .label = "PMV-107J",
        .chip_us = 100,
        .modulation = TpmsModulationFsk,
        .slicer = TpmsSlicerNrz,
        .id_digits = 8,
        .sync = 0x7E,
        .sync_bits = 7,
        .capture_bits = 140,
        .decode = tpms_decode_pmv107j,
    },
    {
        .id = "nissan",
        .label = "Nissan",
        .chip_us = 120,
        .modulation = TpmsModulationFsk,
        .slicer = TpmsSlicerNrz,
        .id_digits = 6,
        .sync = 0xF5555555EULL,
        .sync_bits = 36,
        .capture_bits = 80,
        .decode = tpms_decode_nissan,
    },
    {
        .id = "bmw",
        .label = "BMW Gen4/5",
        .chip_us = 25,
        .modulation = TpmsModulationFsk,
        .slicer = TpmsSlicerNrz,
        .id_digits = 8,
        .sync = 0xAA59,
        .sync_bits = 16,
        .capture_bits = 184,
        .decode = tpms_decode_bmw,
    },
    {
        .id = "mercedes_benz",
        .label = "Mercedes",
        .chip_us = 25,
        .modulation = TpmsModulationFsk,
        .slicer = TpmsSlicerManchester,
        .id_digits = 8,
        .sync = 0x002,
        .sync_bits = 12,
        .capture_bits = 80,
        .decode = tpms_decode_mercedes_benz,
    },
    {
        .id = "steelmate",
        .label = "Steelmate",
        .chip_us = 50,
        .modulation = TpmsModulationFsk,
        .slicer = TpmsSlicerManchester,
        .id_digits = 4,
        .sync = 0xFFFF80,
        .sync_bits = 24,
        .capture_bits = 48,
        .decode = tpms_decode_steelmate,
    },
    {
        .id = "trw_fsk",
        .label = "TRW FSK",
        .chip_us = 52,
        .modulation = TpmsModulationFsk,
        .slicer = TpmsSlicerManchester,
        .id_digits = 8,
        .sync = 0x7FFF,
        .sync_bits = 16,
        .capture_bits = 81,
        .decode = tpms_decode_trw,
    },
    {
        .id = "trw_ook",
        .label = "TRW OOK",
        .chip_us = 52,
        .modulation = TpmsModulationOok,
        .slicer = TpmsSlicerManchester,
        .id_digits = 8,
        .sync = 0x0001,
        .sync_bits = 16,
        .capture_bits = 81,
        .decode = tpms_decode_trw,
    },
    {
        .id = "schrader",
        .label = "Schrader",
        .chip_us = 120,
        .modulation = TpmsModulationOok,
        .slicer = TpmsSlicerManchester,
        .id_digits = 8,
        .sync = 0,
        .sync_bits = 0,
        .capture_bits = 67,
        .decode = tpms_decode_schrader,
    },
    {
        .id = "schrader_eg53",
        .label = "Schrader EG53",
        .chip_us = 120,
        .modulation = TpmsModulationOok,
        .slicer = TpmsSlicerManchester,
        .id_digits = 6,
        .sync = 0,
        .sync_bits = 0,
        .capture_bits = 119,
        .decode = tpms_decode_schrader_eg53ma4,
    },
    {
        .id = "schrader_smd3",
        .label = "Schrader SMD3",
        .chip_us = 120,
        .modulation = TpmsModulationOok,
        .slicer = TpmsSlicerNrz,
        .id_digits = 6,
        .sync = 0x3D5555557ULL,
        .sync_bits = 34,
        .capture_bits = 76,
        .decode = tpms_decode_schrader_smd3ma4,
    },
    {
        .id = "schrader_bmw",
        .label = "Schrader BMW",
        .chip_us = 120,
        .modulation = TpmsModulationOok,
        .slicer = TpmsSlicerManchester,
        .id_digits = 6,
        .sync = 0x7FFF,
        .sync_bits = 16,
        .capture_bits = 45,
        .decode = tpms_decode_schrader_mrxbc5a4,
    },
    {
        .id = "schrader_moto",
        .label = "Schrader moto",
        .chip_us = 120,
        .modulation = TpmsModulationOok,
        .slicer = TpmsSlicerManchester,
        .id_digits = 6,
        .sync = 0xFFF,
        .sync_bits = 13,
        .capture_bits = 56,
        .decode = tpms_decode_schrader_motorcycle,
    },
    {
        .id = "gm",
        .label = "GM aftermarket",
        .chip_us = 120,
        .modulation = TpmsModulationOok,
        .slicer = TpmsSlicerManchester,
        .id_digits = 8,
        .sync = 0,
        .sync_bits = 48,
        .capture_bits = 80,
        .decode = tpms_decode_gm,
    },
    {
        .id = "gear_hive",
        .label = "Gear Hive",
        .chip_us = 120,
        .modulation = TpmsModulationOok,
        .slicer = TpmsSlicerManchester,
        .id_digits = 6,
        .sync = 0x2594,
        .sync_bits = 16,
        .capture_bits = 72,
        .decode = tpms_decode_gear_hive,
    },
    {
        .id = "tyreguard400",
        .label = "TyreGuard 400",
        .chip_us = 100,
        .modulation = TpmsModulationOok,
        .slicer = TpmsSlicerManchester,
        .id_digits = 7,
        .sync = 0xFD5FD5F,
        .sync_bits = 28,
        .capture_bits = 60,
        .decode = tpms_decode_tyreguard400,
    },
    {
        .id = "smartire",
        .label = "SmarTire",
        .chip_us = 167,
        .modulation = TpmsModulationOok,
        .slicer = TpmsSlicerNrz,
        .id_digits = 6,
        .sync = 0x32B4,
        .sync_bits = 16,
        .capture_bits = 96,
        .decode = tpms_decode_smartire,
    },
    {
        .id = "eezrv",
        .label = "EezTire/TST",
        .chip_us = 50,
        .modulation = TpmsModulationOok,
        .slicer = TpmsSlicerManchester,
        .id_digits = 6,
        .sync = 0xFFFF,
        .sync_bits = 16,
        .capture_bits = 64,
        .decode = tpms_decode_eezrv,
    },
    {
        .id = "jansite_ty468",
        .label = "Jansite TY468",
        .chip_us = 50,
        .modulation = TpmsModulationOok,
        .slicer = TpmsSlicerNrz,
        .id_digits = 6,
        .sync = 0xAAAAAAAA,
        .sync_bits = 32,
        .capture_bits = 128,
        .decode = tpms_decode_jansite_ty468,
    },
    {
        .id = "imars_t240",
        .label = "iMars T240",
        .chip_us = 50,
        .modulation = TpmsModulationOok,
        .slicer = TpmsSlicerNrz,
        .id_digits = 6,
        .sync = 0xAAAAAAAA,
        .sync_bits = 32,
        .capture_bits = 128,
        .decode = tpms_decode_imars_t240,
    },
};

const uint8_t tpms_protocol_count = (uint8_t)(sizeof(tpms_protocols) / sizeof(tpms_protocols[0]));

const char* tpms_protocol_label(uint8_t index) {
    return index < tpms_protocol_count ? tpms_protocols[index].label : "?";
}

const char* tpms_protocol_id(uint8_t index) {
    return index < tpms_protocol_count ? tpms_protocols[index].id : "?";
}

uint8_t tpms_protocol_count_for(TpmsModulation modulation) {
    uint8_t count = 0;
    for(uint8_t i = 0; i < tpms_protocol_count; i++) {
        if(tpms_protocols[i].modulation == modulation) count++;
    }
    return count;
}
