ADD_SCENE(nearby_files, start, Start)
ADD_SCENE(nearby_files, file_list, FileList)
ADD_SCENE(nearby_files, menu, Menu)
ADD_SCENE(nearby_files, add_gps, AddGps)
ADD_SCENE(nearby_files, gps_baudrate, GpsBaudrate)
ADD_SCENE(nearby_files, about, About)
