#ifndef SOUNDS_H_
#define SOUNDS_H_

enum
{
	HITWALLSND,              // 0
	SELECTWPNSND,            // 1
	SELECTITEMSND,           // 2
	HEARTBEATSND,            // 3
	MOVEGUN2SND,             // 4
	MOVEGUN1SND,             // 5
	NOWAYSND,                // 6
	NAZIHITPLAYERSND,        // 7
	SCHABBSTHROWSND,         // 8
	PLAYERDEATHSND,          // 9
	DOGDEATHSND,             // 10
	ATKGATLINGSND,           // 11
	GETKEYSND,               // 12
	NOITEMSND,               // 13
	WALK1SND,                // 14
	WALK2SND,                // 15
	TAKEDAMAGESND,           // 16
	GAMEOVERSND,             // 17
	OPENDOORSND,             // 18
	CLOSEDOORSND,            // 19
	DONOTHINGSND,            // 20
	HALTSND,                 // 21
	DEATHSCREAM2SND,         // 22
	ATKKNIFESND,             // 23
	ATKPISTOLSND,            // 24
	DEATHSCREAM3SND,         // 25
	ATKMACHINEGUNSND,        // 26
	HITENEMYSND,             // 27
	SHOOTDOORSND,            // 28
	DEATHSCREAM1SND,         // 29
	GETMACHINESND,           // 30
	GETAMMOSND,              // 31
	SHOOTSND,                // 32
	HEALTH1SND,              // 33
	HEALTH2SND,              // 34
	BONUS1SND,               // 35
	BONUS2SND,               // 36
	BONUS3SND,               // 37
	GETGATLINGSND,           // 38
	ESCPRESSEDSND,           // 39
	LEVELDONESND,            // 40
	DOGBARKSND,              // 41
	ENDBONUS1SND,            // 42
	ENDBONUS2SND,            // 43
	BONUS1UPSND,             // 44
	BONUS4SND,               // 45
	PUSHWALLSND,             // 46
	NOBONUSSND,              // 47
	PERCENT100SND,           // 48
	BOSSACTIVESND,           // 49
	MUTTISND,                // 50
	SCHUTZADSND,             // 51
	AHHHGSND,                // 52
	DIESND,                  // 53
	EVASND,                  // 54
	GUTENTAGSND,             // 55
	LEBENSND,                // 56
	SCHEISTSND,              // 57
	NAZIFIRESND,             // 58
	BOSSFIRESND,             // 59
	SSFIRESND,               // 60
	SLURPIESND,              // 61
	TOT_HUNDSND,             // 62
	MEINGOTTSND,             // 63
	SCHABBSHASND,            // 64
	HITLERHASND,             // 65
	SPIONSND,                // 66
	NEINSOVASSND,            // 67
	DOGATTACKSND,            // 68
	FLAMETHROWERSND,         // 69
	MECHSTEPSND,             // 70
	GOOBSSND,                // 71
	YEAHSND,                 // 72
	DEATHSCREAM4SND,         // 73
	DEATHSCREAM5SND,         // 74
	DEATHSCREAM6SND,         // 75
	DEATHSCREAM7SND,         // 76
	DEATHSCREAM8SND,         // 77
	DEATHSCREAM9SND,         // 78
	DONNERSND,               // 79
	EINESND,                 // 80
	ERLAUBENSND,             // 81
	KEINSND,                 // 82
	MEINSND,                 // 83
	ROSESND,                 // 84
	MISSILEFIRESND,          // 85
	MISSILEHITSND,           // 86
};

#endif
