/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -S ./lib/asn1_skeletons -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#ifndef	_I2CCommand_H_
#define	_I2CCommand_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <NativeInteger.h>
#include "UHFModuleCommand.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* I2CCommand */
typedef struct I2CCommand {
	OCTET_STRING_t	 header;
	long	 busAddress;
	UHFModuleCommand_t	 uhfModuleCommand;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} I2CCommand_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_I2CCommand;
extern asn_SEQUENCE_specifics_t asn_SPC_I2CCommand_specs_1;
extern asn_TYPE_member_t asn_MBR_I2CCommand_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _I2CCommand_H_ */
#include <asn_internal.h>
