/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -S ./lib/asn1_skeletons -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#ifndef	_I2CClockSpeed_H_
#define	_I2CClockSpeed_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum I2CClockSpeed {
	I2CClockSpeed_i2c100KHz	= 100,
	I2CClockSpeed_i2c400KHz	= 400,
	I2CClockSpeed_i2c1000KHz	= 1000
} e_I2CClockSpeed;

/* I2CClockSpeed */
typedef long	 I2CClockSpeed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_I2CClockSpeed;
extern const asn_INTEGER_specifics_t asn_SPC_I2CClockSpeed_specs_1;
asn_struct_free_f I2CClockSpeed_free;
asn_struct_print_f I2CClockSpeed_print;
asn_constr_check_f I2CClockSpeed_constraint;
ber_type_decoder_f I2CClockSpeed_decode_ber;
der_type_encoder_f I2CClockSpeed_encode_der;
xer_type_decoder_f I2CClockSpeed_decode_xer;
xer_type_encoder_f I2CClockSpeed_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _I2CClockSpeed_H_ */
#include <asn_internal.h>
