/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#ifndef	_Key_H_
#define	_Key_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Key */
typedef struct Key {
	OCTET_STRING_t	 referenceId;
	OCTET_STRING_t	 crypto;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Key_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Key;
extern asn_SEQUENCE_specifics_t asn_SPC_Key_specs_1;
extern asn_TYPE_member_t asn_MBR_Key_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Key_H_ */
#include <asn_internal.h>
