/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#ifndef	_Pacs2_H_
#define	_Pacs2_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Pacs2 */
typedef struct Pacs2 {
	OCTET_STRING_t	*bits	/* OPTIONAL */;
	OCTET_STRING_t	*oid	/* OPTIONAL */;
	long	*type	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Pacs2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Pacs2;
extern asn_SEQUENCE_specifics_t asn_SPC_Pacs2_specs_1;
extern asn_TYPE_member_t asn_MBR_Pacs2_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _Pacs2_H_ */
#include <asn_internal.h>
