/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#include "PACS.h"

asn_TYPE_member_t asn_MBR_PACS_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PACS, payload),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"payload"
		},
};
static const ber_tlv_tag_t asn_DEF_PACS_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PACS_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 0, 0, 0 } /* payload */
};
asn_SEQUENCE_specifics_t asn_SPC_PACS_specs_1 = {
	sizeof(struct PACS),
	offsetof(struct PACS, _asn_ctx),
	asn_MAP_PACS_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PACS = {
	"PACS",
	"PACS",
	&asn_OP_SEQUENCE,
	asn_DEF_PACS_tags_1,
	sizeof(asn_DEF_PACS_tags_1)
		/sizeof(asn_DEF_PACS_tags_1[0]), /* 1 */
	asn_DEF_PACS_tags_1,	/* Same as above */
	sizeof(asn_DEF_PACS_tags_1)
		/sizeof(asn_DEF_PACS_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PACS_1,
	1,	/* Elements count */
	&asn_SPC_PACS_specs_1	/* Additional specs */
};

