/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -S ./lib/asn1_skeletons -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#include "RunTimerValue.h"

int
RunTimerValue_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
const asn_INTEGER_specifics_t asn_SPC_RunTimerValue_specs_1 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_RunTimerValue_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
asn_TYPE_descriptor_t asn_DEF_RunTimerValue = {
	"RunTimerValue",
	"RunTimerValue",
	&asn_OP_NativeInteger,
	asn_DEF_RunTimerValue_tags_1,
	sizeof(asn_DEF_RunTimerValue_tags_1)
		/sizeof(asn_DEF_RunTimerValue_tags_1[0]), /* 1 */
	asn_DEF_RunTimerValue_tags_1,	/* Same as above */
	sizeof(asn_DEF_RunTimerValue_tags_1)
		/sizeof(asn_DEF_RunTimerValue_tags_1[0]), /* 1 */
	{ 0, 0, RunTimerValue_constraint },
	0, 0,	/* No members */
	&asn_SPC_RunTimerValue_specs_1	/* Additional specs */
};

