/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -S ./lib/asn1_skeletons -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#ifndef	_RunTimerValue_H_
#define	_RunTimerValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RunTimerValue */
typedef unsigned long	 RunTimerValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RunTimerValue;
extern const asn_INTEGER_specifics_t asn_SPC_RunTimerValue_specs_1;
asn_struct_free_f RunTimerValue_free;
asn_struct_print_f RunTimerValue_print;
asn_constr_check_f RunTimerValue_constraint;
ber_type_decoder_f RunTimerValue_decode_ber;
der_type_encoder_f RunTimerValue_encode_der;
xer_type_decoder_f RunTimerValue_decode_xer;
xer_type_encoder_f RunTimerValue_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RunTimerValue_H_ */
#include <asn_internal.h>
