/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#include "SamResponse2.h"

asn_TYPE_member_t asn_MBR_SamResponse2_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SamResponse2, choice.pacs),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Pacs2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pacs"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_SamResponse2_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* pacs */
};
asn_CHOICE_specifics_t asn_SPC_SamResponse2_specs_1 = {
	sizeof(struct SamResponse2),
	offsetof(struct SamResponse2, _asn_ctx),
	offsetof(struct SamResponse2, present),
	sizeof(((struct SamResponse2 *)0)->present),
	asn_MAP_SamResponse2_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_SamResponse2 = {
	"SamResponse2",
	"SamResponse2",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, CHOICE_constraint },
	asn_MBR_SamResponse2_1,
	1,	/* Elements count */
	&asn_SPC_SamResponse2_specs_1	/* Additional specs */
};

