/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#ifndef	_SamResponse2_H_
#define	_SamResponse2_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Pacs2.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SamResponse2_PR {
	SamResponse2_PR_NOTHING,	/* No components present */
	SamResponse2_PR_pacs
} SamResponse2_PR;

/* SamResponse2 */
typedef struct SamResponse2 {
	SamResponse2_PR present;
	union SamResponse2_u {
		Pacs2_t	 pacs;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SamResponse2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SamResponse2;
extern asn_CHOICE_specifics_t asn_SPC_SamResponse2_specs_1;
extern asn_TYPE_member_t asn_MBR_SamResponse2_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _SamResponse2_H_ */
#include <asn_internal.h>
