/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#ifndef	_SamVerionDetails_H_
#define	_SamVerionDetails_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SamVerionDetails */
typedef struct SamVerionDetails {
	OCTET_STRING_t	 zero;
	OCTET_STRING_t	 one;
	OCTET_STRING_t	 two;
	OCTET_STRING_t	 three;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SamVerionDetails_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SamVerionDetails;
extern asn_SEQUENCE_specifics_t asn_SPC_SamVerionDetails_specs_1;
extern asn_TYPE_member_t asn_MBR_SamVerionDetails_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _SamVerionDetails_H_ */
#include <asn_internal.h>
