/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#include "SamVerionDetails.h"

asn_TYPE_member_t asn_MBR_SamVerionDetails_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SamVerionDetails, zero),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"zero"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SamVerionDetails, one),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"one"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SamVerionDetails, two),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"two"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SamVerionDetails, three),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"three"
		},
};
static const ber_tlv_tag_t asn_DEF_SamVerionDetails_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SamVerionDetails_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* zero */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* one */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* two */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* three */
};
asn_SEQUENCE_specifics_t asn_SPC_SamVerionDetails_specs_1 = {
	sizeof(struct SamVerionDetails),
	offsetof(struct SamVerionDetails, _asn_ctx),
	asn_MAP_SamVerionDetails_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SamVerionDetails = {
	"SamVerionDetails",
	"SamVerionDetails",
	&asn_OP_SEQUENCE,
	asn_DEF_SamVerionDetails_tags_1,
	sizeof(asn_DEF_SamVerionDetails_tags_1)
		/sizeof(asn_DEF_SamVerionDetails_tags_1[0]), /* 1 */
	asn_DEF_SamVerionDetails_tags_1,	/* Same as above */
	sizeof(asn_DEF_SamVerionDetails_tags_1)
		/sizeof(asn_DEF_SamVerionDetails_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SamVerionDetails_1,
	4,	/* Elements count */
	&asn_SPC_SamVerionDetails_specs_1	/* Additional specs */
};

