/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#include "SIO.h"

static asn_TYPE_member_t asn_MBR_SIO_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SIO, rid),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rid"
		},
	{ ATF_POINTER, 1, offsetof(struct SIO, unknown3),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"unknown3"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SIO, unknown5),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"unknown5"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SIO, key),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Key,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"key"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SIO, pacs),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PACS,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pacs"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SIO, unknown9),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"unknown9"
		},
};
static const ber_tlv_tag_t asn_DEF_SIO_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SIO_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* rid */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 }, /* unknown3 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 2, 0, 0 }, /* unknown5 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 3, 0, 0 }, /* key */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 4, 0, 0 }, /* pacs */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 5, 0, 0 } /* unknown9 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SIO_specs_1 = {
	sizeof(struct SIO),
	offsetof(struct SIO, _asn_ctx),
	asn_MAP_SIO_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SIO = {
	"SIO",
	"SIO",
	&asn_OP_SEQUENCE,
	asn_DEF_SIO_tags_1,
	sizeof(asn_DEF_SIO_tags_1)
		/sizeof(asn_DEF_SIO_tags_1[0]), /* 1 */
	asn_DEF_SIO_tags_1,	/* Same as above */
	sizeof(asn_DEF_SIO_tags_1)
		/sizeof(asn_DEF_SIO_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SIO_1,
	6,	/* Elements count */
	&asn_SPC_SIO_specs_1	/* Additional specs */
};

