/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -S ./lib/asn1_skeletons -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#include "SoMediaEdgeType.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static const asn_INTEGER_enum_map_t asn_MAP_SoMediaEdgeType_value2enum_1[] = {
	{ 0,	7,	"unknown" },
	{ 1,	7,	"desfire" },
	{ 2,	6,	"mifare" },
	{ 3,	8,	"picoPass" },
	{ 6,	10,	"mifarePlus" },
	{ 7,	4,	"seos" },
	{ 10,	3,	"uhf" }
};
static const unsigned int asn_MAP_SoMediaEdgeType_enum2value_1[] = {
	1,	/* desfire(1) */
	2,	/* mifare(2) */
	4,	/* mifarePlus(6) */
	3,	/* picoPass(3) */
	5,	/* seos(7) */
	6,	/* uhf(10) */
	0	/* unknown(0) */
};
const asn_INTEGER_specifics_t asn_SPC_SoMediaEdgeType_specs_1 = {
	asn_MAP_SoMediaEdgeType_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_SoMediaEdgeType_enum2value_1,	/* N => "tag"; sorted by N */
	7,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_SoMediaEdgeType_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_SoMediaEdgeType = {
	"SoMediaEdgeType",
	"SoMediaEdgeType",
	&asn_OP_NativeEnumerated,
	asn_DEF_SoMediaEdgeType_tags_1,
	sizeof(asn_DEF_SoMediaEdgeType_tags_1)
		/sizeof(asn_DEF_SoMediaEdgeType_tags_1[0]), /* 1 */
	asn_DEF_SoMediaEdgeType_tags_1,	/* Same as above */
	sizeof(asn_DEF_SoMediaEdgeType_tags_1)
		/sizeof(asn_DEF_SoMediaEdgeType_tags_1[0]), /* 1 */
	{ 0, 0, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_SoMediaEdgeType_specs_1	/* Additional specs */
};

