/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -S ./lib/asn1_skeletons -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#ifndef	_SoMediaEdgeType_H_
#define	_SoMediaEdgeType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SoMediaEdgeType {
	SoMediaEdgeType_unknown	= 0,
	SoMediaEdgeType_desfire	= 1,
	SoMediaEdgeType_mifare	= 2,
	SoMediaEdgeType_picoPass	= 3,
	SoMediaEdgeType_mifarePlus	= 6,
	SoMediaEdgeType_seos	= 7,
	SoMediaEdgeType_uhf	= 10
} e_SoMediaEdgeType;

/* SoMediaEdgeType */
typedef long	 SoMediaEdgeType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SoMediaEdgeType;
extern const asn_INTEGER_specifics_t asn_SPC_SoMediaEdgeType_specs_1;
asn_struct_free_f SoMediaEdgeType_free;
asn_struct_print_f SoMediaEdgeType_print;
asn_constr_check_f SoMediaEdgeType_constraint;
ber_type_decoder_f SoMediaEdgeType_decode_ber;
der_type_encoder_f SoMediaEdgeType_encode_der;
xer_type_decoder_f SoMediaEdgeType_decode_xer;
xer_type_encoder_f SoMediaEdgeType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SoMediaEdgeType_H_ */
#include <asn_internal.h>
