/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -S ./lib/asn1_skeletons -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#ifndef	_UHFModuleCommandGetVersion_H_
#define	_UHFModuleCommandGetVersion_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UHFModuleCommandGetVersion */
typedef NULL_t	 UHFModuleCommandGetVersion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UHFModuleCommandGetVersion;
asn_struct_free_f UHFModuleCommandGetVersion_free;
asn_struct_print_f UHFModuleCommandGetVersion_print;
asn_constr_check_f UHFModuleCommandGetVersion_constraint;
ber_type_decoder_f UHFModuleCommandGetVersion_decode_ber;
der_type_encoder_f UHFModuleCommandGetVersion_encode_der;
xer_type_decoder_f UHFModuleCommandGetVersion_decode_xer;
xer_type_encoder_f UHFModuleCommandGetVersion_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _UHFModuleCommandGetVersion_H_ */
#include <asn_internal.h>
