/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -S ./lib/asn1_skeletons -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#ifndef	_UHFModuleCommand_H_
#define	_UHFModuleCommand_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UHFModuleCommandGetVersion.h"
#include "UHFModuleCommandGetStatus.h"
#include "UHFModuleCommandTransceive.h"
#include "UHFModuleCommandDeactivateMedia.h"
#include "UHFModuleCommandGetProperties.h"
#include "UHFModuleCommandSetConfiguration.h"
#include "UHFModuleCommandSetAccessPassword.h"
#include "UHFModuleCommandGetPrivateData.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UHFModuleCommand_PR {
	UHFModuleCommand_PR_NOTHING,	/* No components present */
	UHFModuleCommand_PR_uhfModuleCommandGetVersion,
	UHFModuleCommand_PR_uhfModuleCommandGetStatus,
	UHFModuleCommand_PR_uhfModuleCommandTransceive,
	UHFModuleCommand_PR_uhfModuleCommandDeactivateMedia,
	UHFModuleCommand_PR_uhfModuleCommandGetProperties,
	UHFModuleCommand_PR_uhfModuleCommandSetConfiguration,
	UHFModuleCommand_PR_uhfModuleCommandSetAccessPassword,
	UHFModuleCommand_PR_uhfModuleCommandGetPrivateData
} UHFModuleCommand_PR;

/* UHFModuleCommand */
typedef struct UHFModuleCommand {
	UHFModuleCommand_PR present;
	union UHFModuleCommand_u {
		UHFModuleCommandGetVersion_t	 uhfModuleCommandGetVersion;
		UHFModuleCommandGetStatus_t	 uhfModuleCommandGetStatus;
		UHFModuleCommandTransceive_t	 uhfModuleCommandTransceive;
		UHFModuleCommandDeactivateMedia_t	 uhfModuleCommandDeactivateMedia;
		UHFModuleCommandGetProperties_t	 uhfModuleCommandGetProperties;
		UHFModuleCommandSetConfiguration_t	 uhfModuleCommandSetConfiguration;
		UHFModuleCommandSetAccessPassword_t	 uhfModuleCommandSetAccessPassword;
		UHFModuleCommandGetPrivateData_t	 uhfModuleCommandGetPrivateData;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UHFModuleCommand_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UHFModuleCommand;
extern asn_CHOICE_specifics_t asn_SPC_UHFModuleCommand_specs_1;
extern asn_TYPE_member_t asn_MBR_UHFModuleCommand_1[8];

#ifdef __cplusplus
}
#endif

#endif	/* _UHFModuleCommand_H_ */
#include <asn_internal.h>
