/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -S ./lib/asn1_skeletons -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#ifndef	_UHFModuleResponseStatus_H_
#define	_UHFModuleResponseStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CardDetails;

/* UHFModuleResponseStatus */
typedef struct UHFModuleResponseStatus {
	struct CardDetails	*mediaInfo	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UHFModuleResponseStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UHFModuleResponseStatus;
extern asn_SEQUENCE_specifics_t asn_SPC_UHFModuleResponseStatus_specs_1;
extern asn_TYPE_member_t asn_MBR_UHFModuleResponseStatus_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CardDetails.h"

#endif	/* _UHFModuleResponseStatus_H_ */
#include <asn_internal.h>
