/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -S ./lib/asn1_skeletons -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#include "UHFModuleResponseStatus.h"

asn_TYPE_member_t asn_MBR_UHFModuleResponseStatus_1[] = {
	{ ATF_POINTER, 1, offsetof(struct UHFModuleResponseStatus, mediaInfo),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CardDetails,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mediaInfo"
		},
};
static const ber_tlv_tag_t asn_DEF_UHFModuleResponseStatus_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UHFModuleResponseStatus_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* mediaInfo */
};
asn_SEQUENCE_specifics_t asn_SPC_UHFModuleResponseStatus_specs_1 = {
	sizeof(struct UHFModuleResponseStatus),
	offsetof(struct UHFModuleResponseStatus, _asn_ctx),
	asn_MAP_UHFModuleResponseStatus_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UHFModuleResponseStatus = {
	"UHFModuleResponseStatus",
	"UHFModuleResponseStatus",
	&asn_OP_SEQUENCE,
	asn_DEF_UHFModuleResponseStatus_tags_1,
	sizeof(asn_DEF_UHFModuleResponseStatus_tags_1)
		/sizeof(asn_DEF_UHFModuleResponseStatus_tags_1[0]), /* 1 */
	asn_DEF_UHFModuleResponseStatus_tags_1,	/* Same as above */
	sizeof(asn_DEF_UHFModuleResponseStatus_tags_1)
		/sizeof(asn_DEF_UHFModuleResponseStatus_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_UHFModuleResponseStatus_1,
	1,	/* Elements count */
	&asn_SPC_UHFModuleResponseStatus_specs_1	/* Additional specs */
};

