/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -S ./lib/asn1_skeletons -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#ifndef	_UHFModuleResponse_H_
#define	_UHFModuleResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UHFModuleResponseVersion.h"
#include "UHFModuleResponseStatus.h"
#include "UHFModuleResponseTransceive.h"
#include "UHFModuleResponseDeactivateMedia.h"
#include "UHFModuleResponseGetProperties.h"
#include "UHFModuleResponseSetConfiguration.h"
#include "UHFModuleResponseSetAccessPassword.h"
#include "UHFModuleResponseGetPrivateData.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UHFModuleResponse_PR {
	UHFModuleResponse_PR_NOTHING,	/* No components present */
	UHFModuleResponse_PR_uhfModuleResponseVersion,
	UHFModuleResponse_PR_uhfModuleResponseStatus,
	UHFModuleResponse_PR_uhfModuleResponseTransceive,
	UHFModuleResponse_PR_uhfModuleResponseDeactivateMedia,
	UHFModuleResponse_PR_uhfModuleResponseGetProperties,
	UHFModuleResponse_PR_uhfModuleResponseSetConfiguration,
	UHFModuleResponse_PR_uhfModuleResponseSetAccessPassword,
	UHFModuleResponse_PR_uhfModuleResponseGetPrivateData
} UHFModuleResponse_PR;

/* UHFModuleResponse */
typedef struct UHFModuleResponse {
	UHFModuleResponse_PR present;
	union UHFModuleResponse_u {
		UHFModuleResponseVersion_t	 uhfModuleResponseVersion;
		UHFModuleResponseStatus_t	 uhfModuleResponseStatus;
		UHFModuleResponseTransceive_t	 uhfModuleResponseTransceive;
		UHFModuleResponseDeactivateMedia_t	 uhfModuleResponseDeactivateMedia;
		UHFModuleResponseGetProperties_t	 uhfModuleResponseGetProperties;
		UHFModuleResponseSetConfiguration_t	 uhfModuleResponseSetConfiguration;
		UHFModuleResponseSetAccessPassword_t	 uhfModuleResponseSetAccessPassword;
		UHFModuleResponseGetPrivateData_t	 uhfModuleResponseGetPrivateData;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UHFModuleResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UHFModuleResponse;
extern asn_CHOICE_specifics_t asn_SPC_UHFModuleResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_UHFModuleResponse_1[8];

#ifdef __cplusplus
}
#endif

#endif	/* _UHFModuleResponse_H_ */
#include <asn_internal.h>
