/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -S ./lib/asn1_skeletons -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#include "UHFModuleResponse.h"

asn_TYPE_member_t asn_MBR_UHFModuleResponse_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UHFModuleResponse, choice.uhfModuleResponseVersion),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UHFModuleResponseVersion,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uhfModuleResponseVersion"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UHFModuleResponse, choice.uhfModuleResponseStatus),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UHFModuleResponseStatus,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uhfModuleResponseStatus"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UHFModuleResponse, choice.uhfModuleResponseTransceive),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UHFModuleResponseTransceive,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uhfModuleResponseTransceive"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UHFModuleResponse, choice.uhfModuleResponseDeactivateMedia),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UHFModuleResponseDeactivateMedia,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uhfModuleResponseDeactivateMedia"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UHFModuleResponse, choice.uhfModuleResponseGetProperties),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UHFModuleResponseGetProperties,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uhfModuleResponseGetProperties"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UHFModuleResponse, choice.uhfModuleResponseSetConfiguration),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UHFModuleResponseSetConfiguration,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uhfModuleResponseSetConfiguration"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UHFModuleResponse, choice.uhfModuleResponseSetAccessPassword),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UHFModuleResponseSetAccessPassword,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uhfModuleResponseSetAccessPassword"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UHFModuleResponse, choice.uhfModuleResponseGetPrivateData),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UHFModuleResponseGetPrivateData,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uhfModuleResponseGetPrivateData"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_UHFModuleResponse_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* uhfModuleResponseVersion */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* uhfModuleResponseStatus */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* uhfModuleResponseTransceive */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* uhfModuleResponseDeactivateMedia */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* uhfModuleResponseGetProperties */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* uhfModuleResponseSetConfiguration */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* uhfModuleResponseSetAccessPassword */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* uhfModuleResponseGetPrivateData */
};
asn_CHOICE_specifics_t asn_SPC_UHFModuleResponse_specs_1 = {
	sizeof(struct UHFModuleResponse),
	offsetof(struct UHFModuleResponse, _asn_ctx),
	offsetof(struct UHFModuleResponse, present),
	sizeof(((struct UHFModuleResponse *)0)->present),
	asn_MAP_UHFModuleResponse_tag2el_1,
	8,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_UHFModuleResponse = {
	"UHFModuleResponse",
	"UHFModuleResponse",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, CHOICE_constraint },
	asn_MBR_UHFModuleResponse_1,
	8,	/* Elements count */
	&asn_SPC_UHFModuleResponse_specs_1	/* Additional specs */
};

