/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -S ./lib/asn1_skeletons -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#ifndef	_UHFModuleCommandSetAccessPassword_H_
#define	_UHFModuleCommandSetAccessPassword_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UHFModuleCommandSetAccessPassword */
typedef OCTET_STRING_t	 UHFModuleCommandSetAccessPassword_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UHFModuleCommandSetAccessPassword;
asn_struct_free_f UHFModuleCommandSetAccessPassword_free;
asn_struct_print_f UHFModuleCommandSetAccessPassword_print;
asn_constr_check_f UHFModuleCommandSetAccessPassword_constraint;
ber_type_decoder_f UHFModuleCommandSetAccessPassword_decode_ber;
der_type_encoder_f UHFModuleCommandSetAccessPassword_encode_der;
xer_type_decoder_f UHFModuleCommandSetAccessPassword_decode_xer;
xer_type_encoder_f UHFModuleCommandSetAccessPassword_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _UHFModuleCommandSetAccessPassword_H_ */
#include <asn_internal.h>
