/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -S ./lib/asn1_skeletons -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#include "UHFModuleCommand.h"

asn_TYPE_member_t asn_MBR_UHFModuleCommand_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UHFModuleCommand, choice.uhfModuleCommandGetVersion),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UHFModuleCommandGetVersion,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uhfModuleCommandGetVersion"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UHFModuleCommand, choice.uhfModuleCommandGetStatus),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UHFModuleCommandGetStatus,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uhfModuleCommandGetStatus"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UHFModuleCommand, choice.uhfModuleCommandTransceive),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UHFModuleCommandTransceive,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uhfModuleCommandTransceive"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UHFModuleCommand, choice.uhfModuleCommandDeactivateMedia),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UHFModuleCommandDeactivateMedia,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uhfModuleCommandDeactivateMedia"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UHFModuleCommand, choice.uhfModuleCommandGetProperties),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UHFModuleCommandGetProperties,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uhfModuleCommandGetProperties"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UHFModuleCommand, choice.uhfModuleCommandSetConfiguration),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UHFModuleCommandSetConfiguration,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uhfModuleCommandSetConfiguration"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UHFModuleCommand, choice.uhfModuleCommandSetAccessPassword),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UHFModuleCommandSetAccessPassword,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uhfModuleCommandSetAccessPassword"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UHFModuleCommand, choice.uhfModuleCommandGetPrivateData),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UHFModuleCommandGetPrivateData,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uhfModuleCommandGetPrivateData"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_UHFModuleCommand_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* uhfModuleCommandGetVersion */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* uhfModuleCommandGetStatus */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* uhfModuleCommandTransceive */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* uhfModuleCommandDeactivateMedia */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* uhfModuleCommandGetProperties */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* uhfModuleCommandSetConfiguration */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* uhfModuleCommandSetAccessPassword */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* uhfModuleCommandGetPrivateData */
};
asn_CHOICE_specifics_t asn_SPC_UHFModuleCommand_specs_1 = {
	sizeof(struct UHFModuleCommand),
	offsetof(struct UHFModuleCommand, _asn_ctx),
	offsetof(struct UHFModuleCommand, present),
	sizeof(((struct UHFModuleCommand *)0)->present),
	asn_MAP_UHFModuleCommand_tag2el_1,
	8,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_UHFModuleCommand = {
	"UHFModuleCommand",
	"UHFModuleCommand",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, CHOICE_constraint },
	asn_MBR_UHFModuleCommand_1,
	8,	/* Elements count */
	&asn_SPC_UHFModuleCommand_specs_1	/* Additional specs */
};

