/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -S ./lib/asn1_skeletons -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#ifndef	_UHFModuleResponseSetAccessPassword_H_
#define	_UHFModuleResponseSetAccessPassword_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UHFModuleResponseSetAccessPassword */
typedef NULL_t	 UHFModuleResponseSetAccessPassword_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UHFModuleResponseSetAccessPassword;
asn_struct_free_f UHFModuleResponseSetAccessPassword_free;
asn_struct_print_f UHFModuleResponseSetAccessPassword_print;
asn_constr_check_f UHFModuleResponseSetAccessPassword_constraint;
ber_type_decoder_f UHFModuleResponseSetAccessPassword_decode_ber;
der_type_encoder_f UHFModuleResponseSetAccessPassword_encode_der;
xer_type_decoder_f UHFModuleResponseSetAccessPassword_decode_xer;
xer_type_encoder_f UHFModuleResponseSetAccessPassword_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _UHFModuleResponseSetAccessPassword_H_ */
#include <asn_internal.h>
