/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -S ./lib/asn1_skeletons -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#ifndef	_UHFModuleResponseDeactivateMedia_H_
#define	_UHFModuleResponseDeactivateMedia_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UHFModuleResponseDeactivateMedia */
typedef NULL_t	 UHFModuleResponseDeactivateMedia_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UHFModuleResponseDeactivateMedia;
asn_struct_free_f UHFModuleResponseDeactivateMedia_free;
asn_struct_print_f UHFModuleResponseDeactivateMedia_print;
asn_constr_check_f UHFModuleResponseDeactivateMedia_constraint;
ber_type_decoder_f UHFModuleResponseDeactivateMedia_decode_ber;
der_type_encoder_f UHFModuleResponseDeactivateMedia_encode_der;
xer_type_decoder_f UHFModuleResponseDeactivateMedia_decode_xer;
xer_type_encoder_f UHFModuleResponseDeactivateMedia_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _UHFModuleResponseDeactivateMedia_H_ */
#include <asn_internal.h>
