/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -S ./lib/asn1_skeletons -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#ifndef	_UHFModuleCommandDeactivateMedia_H_
#define	_UHFModuleCommandDeactivateMedia_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include "UHFModuleTransactionStatus.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UHFModuleCommandDeactivateMedia */
typedef struct UHFModuleCommandDeactivateMedia {
	OCTET_STRING_t	 mediaEPC;
	UHFModuleTransactionStatus_t	 transactionStatus;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UHFModuleCommandDeactivateMedia_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UHFModuleCommandDeactivateMedia;
extern asn_SEQUENCE_specifics_t asn_SPC_UHFModuleCommandDeactivateMedia_specs_1;
extern asn_TYPE_member_t asn_MBR_UHFModuleCommandDeactivateMedia_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _UHFModuleCommandDeactivateMedia_H_ */
#include <asn_internal.h>
