/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -S ./lib/asn1_skeletons -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#ifndef	_UHFModuleCommandGetProperties_H_
#define	_UHFModuleCommandGetProperties_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UHFModuleCommandGetProperties */
typedef NULL_t	 UHFModuleCommandGetProperties_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UHFModuleCommandGetProperties;
asn_struct_free_f UHFModuleCommandGetProperties_free;
asn_struct_print_f UHFModuleCommandGetProperties_print;
asn_constr_check_f UHFModuleCommandGetProperties_constraint;
ber_type_decoder_f UHFModuleCommandGetProperties_decode_ber;
der_type_encoder_f UHFModuleCommandGetProperties_encode_der;
xer_type_decoder_f UHFModuleCommandGetProperties_decode_xer;
xer_type_encoder_f UHFModuleCommandGetProperties_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _UHFModuleCommandGetProperties_H_ */
#include <asn_internal.h>
