/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -S ./lib/asn1_skeletons -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#include "UHFModuleCommandGetProperties.h"

/*
 * This type is implemented using NULL,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_UHFModuleCommandGetProperties_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (5 << 2))
};
asn_TYPE_descriptor_t asn_DEF_UHFModuleCommandGetProperties = {
	"UHFModuleCommandGetProperties",
	"UHFModuleCommandGetProperties",
	&asn_OP_NULL,
	asn_DEF_UHFModuleCommandGetProperties_tags_1,
	sizeof(asn_DEF_UHFModuleCommandGetProperties_tags_1)
		/sizeof(asn_DEF_UHFModuleCommandGetProperties_tags_1[0]), /* 1 */
	asn_DEF_UHFModuleCommandGetProperties_tags_1,	/* Same as above */
	sizeof(asn_DEF_UHFModuleCommandGetProperties_tags_1)
		/sizeof(asn_DEF_UHFModuleCommandGetProperties_tags_1[0]), /* 1 */
	{ 0, 0, NULL_constraint },
	0, 0,	/* No members */
	0	/* No specifics */
};

