/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -S ./lib/asn1_skeletons -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#ifndef	_UHFModuleResponseVersion_H_
#define	_UHFModuleResponseVersion_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UHFModuleResponseVersion */
typedef OCTET_STRING_t	 UHFModuleResponseVersion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UHFModuleResponseVersion;
asn_struct_free_f UHFModuleResponseVersion_free;
asn_struct_print_f UHFModuleResponseVersion_print;
asn_constr_check_f UHFModuleResponseVersion_constraint;
ber_type_decoder_f UHFModuleResponseVersion_decode_ber;
der_type_encoder_f UHFModuleResponseVersion_encode_der;
xer_type_decoder_f UHFModuleResponseVersion_decode_xer;
xer_type_encoder_f UHFModuleResponseVersion_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _UHFModuleResponseVersion_H_ */
#include <asn_internal.h>
