/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -S ./lib/asn1_skeletons -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#include "UHFModuleTransactionStatus.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static const asn_INTEGER_enum_map_t asn_MAP_UHFModuleTransactionStatus_value2enum_1[] = {
	{ 0,	7,	"unknown" },
	{ 1,	7,	"success" },
	{ 2,	7,	"failure" },
	{ 3,	20,	"antipassBackRejected" }
};
static const unsigned int asn_MAP_UHFModuleTransactionStatus_enum2value_1[] = {
	3,	/* antipassBackRejected(3) */
	2,	/* failure(2) */
	1,	/* success(1) */
	0	/* unknown(0) */
};
const asn_INTEGER_specifics_t asn_SPC_UHFModuleTransactionStatus_specs_1 = {
	asn_MAP_UHFModuleTransactionStatus_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_UHFModuleTransactionStatus_enum2value_1,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_UHFModuleTransactionStatus_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_UHFModuleTransactionStatus = {
	"UHFModuleTransactionStatus",
	"UHFModuleTransactionStatus",
	&asn_OP_NativeEnumerated,
	asn_DEF_UHFModuleTransactionStatus_tags_1,
	sizeof(asn_DEF_UHFModuleTransactionStatus_tags_1)
		/sizeof(asn_DEF_UHFModuleTransactionStatus_tags_1[0]), /* 1 */
	asn_DEF_UHFModuleTransactionStatus_tags_1,	/* Same as above */
	sizeof(asn_DEF_UHFModuleTransactionStatus_tags_1)
		/sizeof(asn_DEF_UHFModuleTransactionStatus_tags_1[0]), /* 1 */
	{ 0, 0, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_UHFModuleTransactionStatus_specs_1	/* Additional specs */
};

