/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -S ./lib/asn1_skeletons -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#ifndef	_UHFModuleCommandGetStatus_H_
#define	_UHFModuleCommandGetStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UHFModuleCommandGetStatus */
typedef NULL_t	 UHFModuleCommandGetStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UHFModuleCommandGetStatus;
asn_struct_free_f UHFModuleCommandGetStatus_free;
asn_struct_print_f UHFModuleCommandGetStatus_print;
asn_constr_check_f UHFModuleCommandGetStatus_constraint;
ber_type_decoder_f UHFModuleCommandGetStatus_decode_ber;
der_type_encoder_f UHFModuleCommandGetStatus_encode_der;
xer_type_decoder_f UHFModuleCommandGetStatus_decode_xer;
xer_type_encoder_f UHFModuleCommandGetStatus_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _UHFModuleCommandGetStatus_H_ */
#include <asn_internal.h>
