/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Seader"
 * 	found in "seader.asn1"
 * 	`asn1c -S ./lib/asn1_skeletons -D ./lib/asn1 -no-gen-example -no-gen-OER -no-gen-PER -pdu=all`
 */

#ifndef	_UHFModuleTransactionStatus_H_
#define	_UHFModuleTransactionStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UHFModuleTransactionStatus {
	UHFModuleTransactionStatus_unknown	= 0,
	UHFModuleTransactionStatus_success	= 1,
	UHFModuleTransactionStatus_failure	= 2,
	UHFModuleTransactionStatus_antipassBackRejected	= 3
} e_UHFModuleTransactionStatus;

/* UHFModuleTransactionStatus */
typedef long	 UHFModuleTransactionStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UHFModuleTransactionStatus;
extern const asn_INTEGER_specifics_t asn_SPC_UHFModuleTransactionStatus_specs_1;
asn_struct_free_f UHFModuleTransactionStatus_free;
asn_struct_print_f UHFModuleTransactionStatus_print;
asn_constr_check_f UHFModuleTransactionStatus_constraint;
ber_type_decoder_f UHFModuleTransactionStatus_decode_ber;
der_type_encoder_f UHFModuleTransactionStatus_encode_der;
xer_type_decoder_f UHFModuleTransactionStatus_decode_xer;
xer_type_encoder_f UHFModuleTransactionStatus_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _UHFModuleTransactionStatus_H_ */
#include <asn_internal.h>
