#include <furi.h>

#include "pocketlab_content.h"

#include <string.h>

#include "pocketlab_i18n.h"
#include "pocketlab_labtext.h"

static const char* const track_names[PocketLabTrackCount] = {
    [PocketLabTrackBasics] = "Basics",
    [PocketLabTrackInfrared] = "Infrared",
    [PocketLabTrackSubGhz] = "Sub-GHz",
    [PocketLabTrackRfid] = "RFID 125 kHz",
    [PocketLabTrackNfc] = "NFC",
    [PocketLabTrackIbutton] = "iButton",
    [PocketLabTrackUsb] = "USB / HID",
    [PocketLabTrackGpio] = "GPIO",
    [PocketLabTrackBluetooth] = "Bluetooth",
    [PocketLabTrackSecurity] = "Security",
    [PocketLabTrackSystem] = "System",
};

const char* pocketlab_track_name(PocketLabTrack track) {
    return track < PocketLabTrackCount ? track_names[track] : "";
}

static const PocketLabStep ir_basics_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "Infrared",
        .body = "Your remote uses invisible infrared light. Flipper can learn and repeat it.",
    },
    {
        .type = PocketLabStepText,
        .title = "How it works",
        .body = "A remote blinks an LED in a pattern. Flipper reads it as a command.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "TV remote sends:",
        .correct = "Infrared light",
        .distractors = {"Radio waves", "Bluetooth", "Wi-Fi", "Ultrasound", "Microwaves"},
        .distractor_count = 5,
        .feedback_ok = "Yes, invisible IR light, not radio.",
        .feedback_no = "No, a TV remote sends infrared light.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Open Infrared, Universal Remotes, TV. Aim at a TV and press Power.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep subghz_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "Sub-GHz radio",
        .body = "Sub-GHz is low radio, like 433 MHz. Key fobs and sensors use it.",
    },
    {
        .type = PocketLabStepText,
        .title = "Read and replay",
        .body = "Flipper can read a signal and send it back, great for your own remotes.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "Common band is:",
        .correct = "433 MHz",
        .distractors = {"2.4 GHz", "60 Hz", "5 GHz", "50 kHz", "1 THz"},
        .distractor_count = 5,
        .feedback_ok = "Right, 433 MHz is a very common band.",
        .feedback_no = "No, 433 MHz is the typical one.",
    },
    {
        .type = PocketLabStepText,
        .title = "Stay legal",
        .body = "Capture only your own devices. Some bands are limited by law.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Open Sub-GHz, Read, then press your own remote nearby.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep rfid125_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "Low-freq RFID",
        .body = "125 kHz cards are simple ID tags. Office fobs often use EM4100.",
    },
    {
        .type = PocketLabStepText,
        .title = "Read your tag",
        .body = "Flipper reads the ID and can save or emulate your own card.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "125 kHz RFID is:",
        .correct = "Low frequency",
        .distractors = {"High frequency", "Optical", "Ultra high freq", "Audio band", "Microwave"},
        .distractor_count = 5,
        .feedback_ok = "Yes, 125 kHz is low frequency.",
        .feedback_no = "No, 125 kHz is low frequency.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Open 125 kHz RFID, Read, and hold your fob to the back.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep nfc_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "NFC cards",
        .body = "NFC works at 13.56 MHz. Transit and bank cards use it.",
    },
    {
        .type = PocketLabStepText,
        .title = "MIFARE",
        .body = "Many access cards are MIFARE. Flipper can read and study your own.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "NFC frequency:",
        .correct = "13.56 MHz",
        .distractors = {"125 kHz", "433 MHz", "2.4 GHz", "868 MHz", "27 MHz"},
        .distractor_count = 5,
        .feedback_ok = "Correct, NFC runs at 13.56 MHz.",
        .feedback_no = "No, NFC runs at 13.56 MHz.",
    },
    {
        .type = PocketLabStepText,
        .title = "Be ethical",
        .body = "Read only cards you own. Never clone someone else's card.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Open NFC, Read, and hold your own card to the back.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep ibutton_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "iButton keys",
        .body = "iButton is a metal contact key, used for intercoms and doors.",
    },
    {
        .type = PocketLabStepText,
        .title = "One wire",
        .body = "It talks over one wire. Flipper reads and emulates your own keys.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "iButton uses:",
        .correct = "Metal contact",
        .distractors = {"Radio", "Camera", "Infrared", "Magnetism", "Bluetooth"},
        .distractor_count = 5,
        .feedback_ok = "Right, it uses physical contact.",
        .feedback_no = "No, it is contact based.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Open iButton, Read, and touch your key to the pins.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep badusb_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "Bad USB",
        .body = "Plugged into a PC, Flipper can act as a keyboard and type fast.",
    },
    {
        .type = PocketLabStepText,
        .title = "Ducky scripts",
        .body = "Scripts send keystrokes, handy for setup and quick demos.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "Bad USB is a:",
        .correct = "Keyboard",
        .distractors = {"Mouse", "Printer", "Webcam", "Speaker", "Monitor"},
        .distractor_count = 5,
        .feedback_ok = "Yes, it acts as a keyboard (HID).",
        .feedback_no = "No, it acts as a keyboard.",
    },
    {
        .type = PocketLabStepText,
        .title = "Consent first",
        .body = "Run it only on computers you own or are allowed to test.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Open Bad USB, pick a demo, and plug into your own PC.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep gpio_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "GPIO pins",
        .body = "The top pins let Flipper talk to chips and external modules.",
    },
    {
        .type = PocketLabStepText,
        .title = "UART",
        .body = "UART is a simple serial link, great for ESP32 boards and sensors.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "GPIO lets you:",
        .correct = "Add modules",
        .distractors =
            {"Charge faster", "Play music", "Boost Wi-Fi", "Extend battery", "Unlock regions"},
        .distractor_count = 5,
        .feedback_ok = "Yes, you can add external modules.",
        .feedback_no = "No, GPIO connects modules.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Open GPIO, USB-UART Bridge to see the serial console.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep ble_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "Bluetooth LE",
        .body = "Flipper has BLE. It can act as a remote for your phone or PC.",
    },
    {
        .type = PocketLabStepText,
        .title = "BLE remote",
        .body = "Use it as a media or camera remote over Bluetooth.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "Flipper BLE is:",
        .correct = "Remote control",
        .distractors = {"Wi-Fi router", "GPS", "Modem", "Speaker", "Charger"},
        .distractor_count = 5,
        .feedback_ok = "Yes, it works as a BLE remote.",
        .feedback_no = "No, it works as a BLE remote.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Open Bluetooth Remote and pair it with your phone.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep u2f_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "U2F keys",
        .body = "Flipper can act as a security key for two-factor login.",
    },
    {
        .type = PocketLabStepText,
        .title = "How it helps",
        .body = "Instead of typing a code, you confirm login with the device.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "U2F is used for:",
        .correct = "Secure login",
        .distractors =
            {"Fast charging", "Louder sound", "GPS tracking", "Faster Wi-Fi", "Screen mirror"},
        .distractor_count = 5,
        .feedback_ok = "Right, it is for secure login.",
        .feedback_no = "No, it is for secure login.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Open U2F and register it on a site that supports keys.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep ethics_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "Use it right",
        .body = "Flipper is a tool. Use it on your own devices only.",
    },
    {
        .type = PocketLabStepText,
        .title = "Know the rules",
        .body = "Scanning or copying other people's cards can be illegal.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "Best practice:",
        .correct = "Only your own",
        .distractors =
            {"Test anything", "Ask nobody", "Copy any card", "Share all keys", "Ignore the law"},
        .distractor_count = 5,
        .feedback_ok = "Yes, work on your own devices only.",
        .feedback_no = "No, work on your own devices only.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep firmware_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "Apps catalog",
        .body = "Add features with Apps. Browse the catalog in the mobile app.",
    },
    {
        .type = PocketLabStepText,
        .title = "Firmware",
        .body = "Firmware is the system. Keep it updated for new features.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "Extra features are:",
        .correct = "Apps (.fap)",
        .distractors = {"Stickers", "Batteries", "Cables", "Screen film", "Cases"},
        .distractor_count = 5,
        .feedback_ok = "Yes, features come as installable apps.",
        .feedback_no = "No, they come as installable apps.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Open Apps, browse the list, and launch one you like.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep whatis_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "Meet Flipper",
        .body = "Flipper Zero is a pocket multi-tool for radio, cards and hardware.",
    },
    {
        .type = PocketLabStepText,
        .title = "What it does",
        .body = "It reads, saves and replays signals from devices you own, and runs apps.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "Flipper Zero is a:",
        .correct = "Pocket multi-tool",
        .distractors = {"Game console", "Phone", "Router", "Camera", "Toy only"},
        .distractor_count = 5,
        .feedback_ok = "Right, a pocket multi-tool.",
        .feedback_no = "It is a pocket multi-tool.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep sdcard_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "The SD card",
        .body = "Everything you save lives on the microSD card: keys, signals and apps.",
    },
    {
        .type = PocketLabStepText,
        .title = "Back it up",
        .body = "Copy the SD card to your PC now and then, so you never lose your saves.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "Your saves live on:",
        .correct = "The SD card",
        .distractors = {"The cloud", "Internal only", "A server", "RAM", "The battery"},
        .distractor_count = 5,
        .feedback_ok = "Yes, on the microSD card.",
        .feedback_no = "They live on the SD card.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Open Settings, Storage to see your SD card usage.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep universal_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "Universal remotes",
        .body = "Flipper ships with IR codes for thousands of TVs, ACs and projectors.",
    },
    {
        .type = PocketLabStepText,
        .title = "Power off anything",
        .body = "Cycle through codes to turn off a nearby TV, even without its remote.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "Universal remotes use:",
        .correct = "Infrared",
        .distractors = {"Wi-Fi", "Sub-GHz", "Bluetooth", "NFC", "GPS"},
        .distractor_count = 5,
        .feedback_ok = "Yes, infrared codes.",
        .feedback_no = "They use infrared.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Open Infrared, Universal Remotes, TV, and press Power.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep freqanalyzer_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "Find the frequency",
        .body = "The Frequency Analyzer finds which Sub-GHz frequency a remote uses.",
    },
    {
        .type = PocketLabStepText,
        .title = "Why it helps",
        .body = "Knowing the frequency lets you read the signal on the right band.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "The analyzer finds:",
        .correct = "The frequency",
        .distractors = {"The password", "The brand", "The distance", "The owner", "The battery"},
        .distractor_count = 5,
        .feedback_ok = "Right, the active frequency.",
        .feedback_no = "It finds the frequency.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Open Sub-GHz, Frequency Analyzer, and hold your remote's button.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep subreplay_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "Read a signal",
        .body = "Sub-GHz Read captures a nearby signal so you can save and study it.",
    },
    {
        .type = PocketLabStepText,
        .title = "Replay your own",
        .body = "Send a saved signal back to control your own gate or doorbell.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "Never replay:",
        .correct = "Others' devices",
        .distractors =
            {"Your own remote", "A test signal", "Your doorbell", "Your gate", "A saved file"},
        .distractor_count = 5,
        .feedback_ok = "Right, only your own devices.",
        .feedback_no = "Do not replay others' devices.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Open Sub-GHz, Read, press your own remote, then Save.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep rfidsave_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "Save a tag",
        .body = "After reading a 125 kHz tag you can save it under a name.",
    },
    {
        .type = PocketLabStepText,
        .title = "Emulate it",
        .body = "Flipper can pretend to be your saved tag for readers you own.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "125 kHz tags can be:",
        .correct = "Saved and emulated",
        .distractors = {"Charged", "Printed", "Called", "Painted", "Read only"},
        .distractor_count = 5,
        .feedback_ok = "Yes, saved and emulated.",
        .feedback_no = "They can be saved and emulated.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Open 125 kHz RFID, Saved, pick a tag, then Emulate.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep mifare_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "MIFARE Classic",
        .body = "A common 13.56 MHz card split into sectors, each locked by keys.",
    },
    {
        .type = PocketLabStepText,
        .title = "Keys and dictionary",
        .body = "Flipper tries a dictionary of common keys to read known sectors.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "MIFARE is split into:",
        .correct = "Sectors",
        .distractors = {"Frames", "Pixels", "Channels", "Tracks", "Pages only"},
        .distractor_count = 5,
        .feedback_ok = "Right, sectors locked by keys.",
        .feedback_no = "It is split into sectors.",
    },
    {
        .type = PocketLabStepText,
        .title = "Be ethical",
        .body = "Read only cards you own. Do not clone other people's cards.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Open NFC, Read, and hold your own MIFARE card.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep ducky_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "DuckyScript",
        .body = "Bad USB scripts use simple lines like STRING and ENTER.",
    },
    {
        .type = PocketLabStepText,
        .title = "Delays matter",
        .body = "Add DELAY so the target PC keeps up before the next keystroke.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "DuckyScript writes:",
        .correct = "Keystrokes",
        .distractors = {"Radio", "Images", "Sound", "Cards", "Firmware"},
        .distractor_count = 5,
        .feedback_ok = "Yes, keystrokes.",
        .feedback_no = "It writes keystrokes.",
    },
    {
        .type = PocketLabStepText,
        .title = "Consent first",
        .body = "Run scripts only on computers you own or may test.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Open Bad USB, pick a demo script, plug into your own PC.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep pinlock_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "Lock your Flipper",
        .body = "Set a PIN so nobody can use your Flipper if it is lost.",
    },
    {
        .type = PocketLabStepText,
        .title = "Safety first",
        .body = "A locked Flipper protects your saved keys and cards.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "A PIN lock protects:",
        .correct = "Your saved data",
        .distractors = {"The battery", "The screen", "The antenna", "The speaker", "The case"},
        .distractor_count = 5,
        .feedback_ok = "Right, your saved data.",
        .feedback_no = "It protects your saved data.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Open Settings, Desktop, PIN Setup.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep navigation_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "The buttons",
        .body = "Use the D-pad to move, OK to select, and Back to go up a level.",
    },
    {
        .type = PocketLabStepText,
        .title = "The main menu",
        .body = "Each icon opens a tool: Sub-GHz, RFID, NFC, Apps and more.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "The Back button:",
        .correct = "Goes up a level",
        .distractors = {"Turns off", "Deletes", "Opens apps", "Locks it", "Reboots"},
        .distractor_count = 5,
        .feedback_ok = "Right, Back goes up a level.",
        .feedback_no = "Back goes up a level.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep rolling_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "Rolling codes",
        .body = "Modern car fobs change their code every press, so a replay will not work.",
    },
    {
        .type = PocketLabStepText,
        .title = "Why replay fails",
        .body = "The receiver expects a new code each time and rejects an old one.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "Rolling codes change:",
        .correct = "Every press",
        .distractors = {"Never", "Once a year", "On charge", "By color", "At night"},
        .distractor_count = 5,
        .feedback_ok = "Right, every press.",
        .feedback_no = "They change every press.",
    },
    {
        .type = PocketLabStepText,
        .title = "Stay legal",
        .body = "Do not attack cars. Study rolling codes in theory or on your own gear.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep cardtypes_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "Card families",
        .body = "125 kHz tags come in types like EM4100 and HID Prox.",
    },
    {
        .type = PocketLabStepText,
        .title = "Different formats",
        .body = "Each stores its ID a bit differently, so Flipper labels the type.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "EM4100 is a:",
        .correct = "125 kHz tag",
        .distractors = {"NFC card", "Bank card", "SIM card", "QR code", "Barcode"},
        .distractor_count = 5,
        .feedback_ok = "Yes, a 125 kHz tag.",
        .feedback_no = "It is a 125 kHz tag.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Open 125 kHz RFID, Read, and note the detected type.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep nfcemulate_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "Emulate a card",
        .body = "Flipper can present a saved NFC card to a reader you own.",
    },
    {
        .type = PocketLabStepText,
        .title = "UID emulation",
        .body = "Simple readers check the card's UID, which Flipper can replay.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "Emulating means:",
        .correct = "Act as the card",
        .distractors = {"Print it", "Call it", "Charge it", "Delete it", "Scan it"},
        .distractor_count = 5,
        .feedback_ok = "Right, it acts as the card.",
        .feedback_no = "It acts as the card.",
    },
    {
        .type = PocketLabStepText,
        .title = "Be ethical",
        .body = "Emulate only your own cards, on your own readers.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Open NFC, Saved, pick your card, then Emulate.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep ibtypes_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "iButton families",
        .body = "Common types are Dallas, Cyfral and Metakom.",
    },
    {
        .type = PocketLabStepText,
        .title = "Regional use",
        .body = "Different intercom brands use different iButton types.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "A common iButton type:",
        .correct = "Dallas",
        .distractors = {"MIFARE", "EM4100", "U2F", "LoRa", "Zigbee"},
        .distractor_count = 5,
        .feedback_ok = "Yes, Dallas is common.",
        .feedback_no = "Dallas is a common type.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Open iButton, Read, and note the detected type.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep jiggler_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "Mouse Jiggler",
        .body = "Plugged into a PC, Flipper can nudge the mouse to keep it awake.",
    },
    {
        .type = PocketLabStepText,
        .title = "Handy uses",
        .body = "Stops the screen from sleeping during a long download or read.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "Mouse Jiggler keeps the:",
        .correct = "PC awake",
        .distractors = {"Fob charged", "Card warm", "Radio on", "Screen off", "App open"},
        .distractor_count = 5,
        .feedback_ok = "Right, it keeps the PC awake.",
        .feedback_no = "It keeps the PC awake.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Open Bad USB, Mouse Jiggler, and plug into your own PC.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep wifiboard_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "WiFi Dev Board",
        .body = "An ESP32 board on the GPIO adds Wi-Fi to your Flipper.",
    },
    {
        .type = PocketLabStepText,
        .title = "What it enables",
        .body = "With companion apps it scans and works with Wi-Fi networks.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "The WiFi board adds:",
        .correct = "Wi-Fi",
        .distractors = {"A battery", "A screen", "GPS", "A camera", "Storage"},
        .distractor_count = 5,
        .feedback_ok = "Yes, it adds Wi-Fi.",
        .feedback_no = "It adds Wi-Fi.",
    },
    {
        .type = PocketLabStepText,
        .title = "Use it right",
        .body = "Test only networks you own or are allowed to.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep sensors_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "Read sensors",
        .body = "Over GPIO, Flipper can read sensors like temperature and humidity.",
    },
    {
        .type = PocketLabStepText,
        .title = "The I2C bus",
        .body = "Many sensors talk over I2C, a two-wire bus on the GPIO pins.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "I2C uses how many wires:",
        .correct = "Two",
        .distractors = {"One", "Four", "Eight", "Zero", "Ten"},
        .distractor_count = 5,
        .feedback_ok = "Right, two wires.",
        .feedback_no = "I2C uses two wires.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Wire an I2C sensor and open a sensor app like Unitemp.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep bleremote_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "BLE remote",
        .body = "Over Bluetooth, Flipper acts as a remote for your phone or PC.",
    },
    {
        .type = PocketLabStepText,
        .title = "Media and camera",
        .body = "Use it to skip tracks, control slides, or trigger the camera.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "BLE Remote controls:",
        .correct = "Your phone",
        .distractors = {"A car", "A gate", "A TV via IR", "A fob", "A card"},
        .distractor_count = 5,
        .feedback_ok = "Yes, your phone or PC.",
        .feedback_no = "It controls your phone or PC.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Open Bluetooth Remote and pair with your phone.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep weather_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "Weather sensors",
        .body = "Many wireless weather sensors broadcast on Sub-GHz bands.",
    },
    {
        .type = PocketLabStepText,
        .title = "Read the air",
        .body = "The Weather Station app decodes temperature and humidity nearby.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "Weather sensors use:",
        .correct = "Sub-GHz radio",
        .distractors = {"NFC", "Infrared", "Bluetooth", "Wi-Fi", "GPS"},
        .distractor_count = 5,
        .feedback_ok = "Right, Sub-GHz radio.",
        .feedback_no = "They use Sub-GHz radio.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Open Sub-GHz, Weather Station, and wait for a reading.",
    },
    {.type = PocketLabStepReward},
};

// ---- Advanced labs (deeper per-subsystem topics) ---------------------------

static const PocketLabStep nfckeys_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "Sector keys",
        .body = "Each MIFARE Classic sector holds a Key A and Key B in its trailer.",
    },
    {
        .type = PocketLabStepText,
        .title = "Dictionary first",
        .body = "Flipper tries a list of common keys; many cards still use defaults.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "A sector is unlocked by its:",
        .correct = "Key",
        .distractors = {"Colour", "Voltage", "UID only", "PIN code", "Antenna"},
        .distractor_count = 5,
        .feedback_ok = "Right, Key A or Key B.",
        .feedback_no = "It is unlocked by a key.",
    },
    {
        .type = PocketLabStepText,
        .title = "MFKey32",
        .body = "Emulate a card to a reader, capture nonces, recover keys offline.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "MFKey32 recovers keys from:",
        .correct = "Reader nonces",
        .distractors = {"Card photos", "GPS", "Bluetooth", "The PIN", "Screen taps"},
        .distractor_count = 5,
        .feedback_ok = "Yes, from captured reader nonces.",
        .feedback_no = "It uses captured reader nonces.",
    },
    {
        .type = PocketLabStepText,
        .title = "Nested & hardnested",
        .body = "One known key unlocks others; hardened cards fix the nonce to resist it.",
    },
    {
        .type = PocketLabStepText,
        .title = "Ethics",
        .body = "Recover keys only from cards you own. Cloning access is illegal.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "NFC, Detect Reader on your own reader, then run MFKey.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep t5577_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "The T5577 blank",
        .body = "A writable 125 kHz chip that can mimic EM4100, HID Prox or Indala.",
    },
    {
        .type = PocketLabStepText,
        .title = "Clone flow",
        .body = "Read the source tag, save it, then write it onto a T5577 blank.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "A T5577 is special because it is:",
        .correct = "Writable",
        .distractors = {"Encrypted", "13.56 MHz", "Optical", "A battery", "Bluetooth"},
        .distractor_count = 5,
        .feedback_ok = "Right, you can write to it.",
        .feedback_no = "It is a writable blank.",
    },
    {
        .type = PocketLabStepText,
        .title = "LF has no crypto",
        .body = "EM4100 sends a fixed ID with no auth, so LF access control is weak.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "EM4100 protects its ID with:",
        .correct = "Nothing",
        .distractors = {"AES", "A password", "Rolling code", "A key", "TLS"},
        .distractor_count = 5,
        .feedback_ok = "Correct, it has no security.",
        .feedback_no = "It has no protection at all.",
    },
    {
        .type = PocketLabStepText,
        .title = "Ethics",
        .body = "Clone only your own fobs. Copying building access is not allowed.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "125 kHz RFID, Read your fob, Save, then Write to a T5577.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep irproto_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "Parsed vs raw",
        .body = "Remotes speak protocols; Flipper decodes known ones or stores raw timings.",
    },
    {
        .type = PocketLabStepText,
        .title = "NEC & RC5",
        .body = "NEC carries an address and command; RC5 and SIRC are other common ones.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "A NEC frame carries:",
        .correct = "Address + command",
        .distractors = {"Audio", "Video", "Voltage", "A photo", "GPS"},
        .distractor_count = 5,
        .feedback_ok = "Right, address and command bytes.",
        .feedback_no = "It carries address and command.",
    },
    {
        .type = PocketLabStepText,
        .title = "Learn a button",
        .body = "Add a custom remote by capturing one raw signal per button you press.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "Universal TV-off works by:",
        .correct = "Trying many codes",
        .distractors = {"One secret code", "Wi-Fi", "Bluetooth", "A magnet", "Sound"},
        .distractor_count = 5,
        .feedback_ok = "Yes, it brute-forces a code list.",
        .feedback_no = "It tries many known codes.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Infrared, Learn New Remote, capture a button from your own remote.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep ibtnwrite_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "Writable keys",
        .body = "RW1990 and similar blanks let you save a read iButton ID onto them.",
    },
    {
        .type = PocketLabStepText,
        .title = "Dallas ROM",
        .body = "A Dallas key is a family byte, a unique serial and a CRC check.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "An iButton ID is:",
        .correct = "Not encrypted",
        .distractors = {"AES", "A password", "A radio code", "A PIN", "A song"},
        .distractor_count = 5,
        .feedback_ok = "Right, so it can be copied.",
        .feedback_no = "It is unencrypted, so copyable.",
    },
    {
        .type = PocketLabStepText,
        .title = "The CRC",
        .body = "A wrong CRC means the reader rejects the key, so it must copy exactly.",
    },
    {
        .type = PocketLabStepText,
        .title = "Ethics",
        .body = "Copy only your own keys. Duplicating building keys needs permission.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "iButton, Read your key, Save, then Write to a blank.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep usbadv_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "OS-aware payloads",
        .body = "Good scripts branch for Windows, macOS or Linux, since shortcuts differ.",
    },
    {
        .type = PocketLabStepText,
        .title = "Modifiers",
        .body = "GUI r opens Run on Windows; combine ALT, CTRL and SHIFT for hotkeys.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "DELAY in a payload gives the PC:",
        .correct = "Time to react",
        .distractors = {"More colour", "Volume", "Encryption", "GPS", "Battery"},
        .distractor_count = 5,
        .feedback_ok = "Right, timing keeps it reliable.",
        .feedback_no = "It gives the PC time to react.",
    },
    {
        .type = PocketLabStepText,
        .title = "Detection",
        .body = "Security tools flag machine-fast typing, so realistic tests add delays.",
    },
    {
        .type = PocketLabStepText,
        .title = "Consent",
        .body = "Run payloads only on computers you own or are authorised to test.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Bad USB, load a demo script, run it on your own PC.",
    },
    {.type = PocketLabStepReward},
};

static const PocketLabStep gpiologic_steps[] = {
    {
        .type = PocketLabStepText,
        .title = "Reading buses",
        .body = "Flipper can sniff serial buses on its GPIO to see how devices talk.",
    },
    {
        .type = PocketLabStepText,
        .title = "UART, SPI, I2C",
        .body = "UART needs a shared ground; SPI and I2C add clock and select lines.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "UART between two boards needs a common:",
        .correct = "Ground",
        .distractors = {"Antenna", "Battery", "Screen", "Key", "Speaker"},
        .distractor_count = 5,
        .feedback_ok = "Right, a shared ground reference.",
        .feedback_no = "They must share a ground.",
    },
    {
        .type = PocketLabStepText,
        .title = "Mind the voltage",
        .body = "Flipper GPIO is 3.3V; a 5V line can damage the pins without a divider.",
    },
    {
        .type = PocketLabStepQuiz,
        .title = "Flipper GPIO logic level is:",
        .correct = "3.3V",
        .distractors = {"5V", "12V", "1.5V", "230V", "9V"},
        .distractor_count = 5,
        .feedback_ok = "Right, 3.3V logic.",
        .feedback_no = "It is 3.3V logic.",
    },
    {
        .type = PocketLabStepTry,
        .title = "Try it",
        .body = "Wire a 3.3V UART device to GPIO and open the UART bridge.",
    },
    {.type = PocketLabStepReward},
};

const PocketLabLab pocketlab_labs[] = {
    {
        .id = "what-is-flipper",
        .title = "What is Flipper",
        .badge = "First Steps",
        .track = PocketLabTrackBasics,
        .xp = 20,
        .icon = {252, 258, 561, 561, 513, 561, 561, 561, 378, 252},
        .steps = whatis_steps,
        .step_count = COUNT_OF(whatis_steps),
    },
    {
        .id = "sd-card",
        .title = "SD Card & Backups",
        .badge = "Data Keeper",
        .track = PocketLabTrackBasics,
        .xp = 25,
        .icon = {254, 341, 257, 385, 257, 257, 257, 257, 511, 0},
        .steps = sdcard_steps,
        .step_count = COUNT_OF(sdcard_steps),
    },
    {
        .id = "ir-basics",
        .title = "IR Basics",
        .badge = "IR Initiate",
        .track = PocketLabTrackInfrared,
        .xp = 30,
        .icon = {0, 504, 1542, 2289, 264, 96, 0, 240, 504, 504, 4095, 0},
        .steps = ir_basics_steps,
        .step_count = COUNT_OF(ir_basics_steps),
    },
    {
        .id = "ir-universal",
        .title = "Universal Remotes",
        .badge = "Remote Ninja",
        .track = PocketLabTrackInfrared,
        .xp = 35,
        .icon = {120, 252, 180, 180, 252, 180, 132, 180, 132, 252, 120, 0},
        .steps = universal_steps,
        .step_count = COUNT_OF(universal_steps),
    },
    {
        .id = "subghz-basics",
        .title = "Sub-GHz Basics",
        .badge = "RF Scout",
        .track = PocketLabTrackSubGhz,
        .xp = 40,
        .icon = {516, 1026, 2313, 2661, 2661, 2565, 2409, 1122, 612, 96, 96, 96},
        .steps = subghz_steps,
        .step_count = COUNT_OF(subghz_steps),
    },
    {
        .id = "subghz-analyzer",
        .title = "Frequency Analyzer",
        .badge = "Signal Hunter",
        .track = PocketLabTrackSubGhz,
        .xp = 40,
        .icon = {516, 1026, 2313, 2661, 2661, 2565, 2409, 1122, 612, 96, 96, 96},
        .steps = freqanalyzer_steps,
        .step_count = COUNT_OF(freqanalyzer_steps),
    },
    {
        .id = "subghz-replay",
        .title = "Read & Replay",
        .badge = "Replayer",
        .track = PocketLabTrackSubGhz,
        .xp = 40,
        .icon = {32, 504, 532, 1074, 1138, 1266, 1139, 1074, 1042, 516, 504, 0},
        .steps = subreplay_steps,
        .step_count = COUNT_OF(subreplay_steps),
    },
    {
        .id = "rfid-125",
        .title = "125 kHz RFID",
        .badge = "Tag Reader",
        .track = PocketLabTrackRfid,
        .xp = 40,
        .icon = {0, 2046, 1026, 1530, 1290, 1386, 1386, 1290, 1530, 1026, 2046, 0},
        .steps = rfid125_steps,
        .step_count = COUNT_OF(rfid125_steps),
    },
    {
        .id = "rfid-emulate",
        .title = "Save & Emulate",
        .badge = "Cloner",
        .track = PocketLabTrackRfid,
        .xp = 40,
        .icon = {0, 2046, 1026, 1530, 1290, 1386, 1386, 1290, 1530, 1026, 2046, 0},
        .steps = rfidsave_steps,
        .step_count = COUNT_OF(rfidsave_steps),
    },
    {
        .id = "nfc-basics",
        .title = "NFC Basics",
        .badge = "NFC Explorer",
        .track = PocketLabTrackNfc,
        .xp = 45,
        .icon = {0, 0, 128, 288, 328, 336, 336, 328, 288, 128, 0, 0},
        .steps = nfc_steps,
        .step_count = COUNT_OF(nfc_steps),
    },
    {
        .id = "nfc-mifare",
        .title = "MIFARE Classic",
        .badge = "Sector Sleuth",
        .track = PocketLabTrackNfc,
        .xp = 45,
        .icon = {0, 0, 128, 288, 328, 336, 336, 328, 288, 128, 0, 0},
        .steps = mifare_steps,
        .step_count = COUNT_OF(mifare_steps),
    },
    {
        .id = "ibutton",
        .title = "iButton Keys",
        .badge = "Key Master",
        .track = PocketLabTrackIbutton,
        .xp = 40,
        .icon = {384, 576, 576, 384, 64, 32, 16, 24, 20, 6},
        .steps = ibutton_steps,
        .step_count = COUNT_OF(ibutton_steps),
    },
    {
        .id = "bad-usb",
        .title = "Bad USB",
        .badge = "HID Novice",
        .track = PocketLabTrackUsb,
        .xp = 45,
        .icon = {0, 2046, 1026, 1194, 1026, 1194, 1026, 1266, 2046, 0},
        .steps = badusb_steps,
        .step_count = COUNT_OF(badusb_steps),
    },
    {
        .id = "usb-ducky",
        .title = "DuckyScript",
        .badge = "Ducky Writer",
        .track = PocketLabTrackUsb,
        .xp = 45,
        .icon = {0, 56, 124, 492, 124, 56, 254, 511, 1022, 510, 252, 0},
        .steps = ducky_steps,
        .step_count = COUNT_OF(ducky_steps),
    },
    {
        .id = "gpio-uart",
        .title = "GPIO and UART",
        .badge = "Pin Wrangler",
        .track = PocketLabTrackGpio,
        .xp = 45,
        .icon = {146, 146, 146, 1023, 513, 341, 513, 1023, 0, 0},
        .steps = gpio_steps,
        .step_count = COUNT_OF(gpio_steps),
    },
    {
        .id = "bluetooth",
        .title = "Bluetooth LE",
        .badge = "BLE Tinkerer",
        .track = PocketLabTrackBluetooth,
        .xp = 40,
        .icon = {24, 40, 74, 52, 24, 52, 74, 40, 24, 0},
        .steps = ble_steps,
        .step_count = COUNT_OF(ble_steps),
    },
    {
        .id = "u2f",
        .title = "U2F and 2FA",
        .badge = "2FA Guardian",
        .track = PocketLabTrackSecurity,
        .xp = 45,
        .icon = {124, 130, 313, 297, 313, 146, 146, 68, 40, 16},
        .steps = u2f_steps,
        .step_count = COUNT_OF(u2f_steps),
    },
    {
        .id = "pin-lock",
        .title = "PIN Lock & Safety",
        .badge = "Guardian",
        .track = PocketLabTrackSecurity,
        .xp = 30,
        .icon = {0, 120, 204, 204, 510, 510, 510, 462, 462, 462, 510, 0},
        .steps = pinlock_steps,
        .step_count = COUNT_OF(pinlock_steps),
    },
    {
        .id = "ethics",
        .title = "Ethics and Law",
        .badge = "Responsible",
        .track = PocketLabTrackBasics,
        .xp = 30,
        .icon = {124, 130, 257, 265, 277, 265, 130, 130, 68, 56},
        .steps = ethics_steps,
        .step_count = COUNT_OF(ethics_steps),
    },
    {
        .id = "firmware-apps",
        .title = "Firmware and Apps",
        .badge = "Power User",
        .track = PocketLabTrackSystem,
        .xp = 35,
        .icon = {341, 510, 765, 258, 645, 258, 645, 510, 341, 0},
        .steps = firmware_steps,
        .step_count = COUNT_OF(firmware_steps),
    },
    {
        .id = "navigation",
        .title = "Navigation",
        .badge = "Navigator",
        .track = PocketLabTrackBasics,
        .xp = 20,
        .icon = {96, 240, 240, 504, 1020, 1020, 2046, 3870, 3598, 3078},
        .steps = navigation_steps,
        .step_count = COUNT_OF(navigation_steps),
    },
    {
        .id = "subghz-rolling",
        .title = "Rolling Codes",
        .badge = "Rolling Master",
        .track = PocketLabTrackSubGhz,
        .xp = 45,
        .icon = {516, 1026, 2313, 2661, 2661, 2565, 2409, 1122, 612, 96, 96, 96},
        .steps = rolling_steps,
        .step_count = COUNT_OF(rolling_steps),
    },
    {
        .id = "subghz-weather",
        .title = "Weather Station",
        .badge = "Weather Watcher",
        .track = PocketLabTrackSubGhz,
        .xp = 35,
        .icon = {0, 96, 248, 508, 1022, 1022, 508, 0, 340, 340, 0, 0},
        .steps = weather_steps,
        .step_count = COUNT_OF(weather_steps),
    },
    {
        .id = "rfid-types",
        .title = "Card Types",
        .badge = "Tag Sorter",
        .track = PocketLabTrackRfid,
        .xp = 40,
        .icon = {0, 2046, 1026, 1530, 1290, 1386, 1386, 1290, 1530, 1026, 2046, 0},
        .steps = cardtypes_steps,
        .step_count = COUNT_OF(cardtypes_steps),
    },
    {
        .id = "nfc-emulate",
        .title = "Emulate NFC",
        .badge = "NFC Emulator",
        .track = PocketLabTrackNfc,
        .xp = 45,
        .icon = {0, 0, 128, 288, 328, 336, 336, 328, 288, 128, 0, 0},
        .steps = nfcemulate_steps,
        .step_count = COUNT_OF(nfcemulate_steps),
    },
    {
        .id = "ibutton-types",
        .title = "iButton Types",
        .badge = "Key Collector",
        .track = PocketLabTrackIbutton,
        .xp = 40,
        .icon = {384, 576, 576, 384, 64, 32, 16, 24, 20, 6},
        .steps = ibtypes_steps,
        .step_count = COUNT_OF(ibtypes_steps),
    },
    {
        .id = "usb-jiggler",
        .title = "Mouse Jiggler",
        .badge = "Jiggler",
        .track = PocketLabTrackUsb,
        .xp = 30,
        .icon = {0, 56, 124, 492, 124, 56, 254, 511, 1022, 510, 252, 0},
        .steps = jiggler_steps,
        .step_count = COUNT_OF(jiggler_steps),
    },
    {
        .id = "gpio-wifi",
        .title = "WiFi Dev Board",
        .badge = "Board Builder",
        .track = PocketLabTrackGpio,
        .xp = 45,
        .icon = {146, 146, 146, 1023, 513, 341, 513, 1023, 0, 0},
        .steps = wifiboard_steps,
        .step_count = COUNT_OF(wifiboard_steps),
    },
    {
        .id = "gpio-sensors",
        .title = "Sensors & I2C",
        .badge = "Sensor Sage",
        .track = PocketLabTrackGpio,
        .xp = 45,
        .icon = {12, 20, 20, 20, 276, 660, 702, 938, 924, 768},
        .steps = sensors_steps,
        .step_count = COUNT_OF(sensors_steps),
    },
    {
        .id = "ble-remote",
        .title = "BLE Remote",
        .badge = "Remote Master",
        .track = PocketLabTrackBluetooth,
        .xp = 40,
        .icon = {24, 40, 74, 52, 24, 52, 74, 40, 24, 0},
        .steps = bleremote_steps,
        .step_count = COUNT_OF(bleremote_steps),
    },
    {
        .id = "nfc-keys",
        .title = "MIFARE Keys",
        .badge = "Key Cracker",
        .track = PocketLabTrackNfc,
        .xp = 60,
        .icon = {0, 0, 128, 288, 328, 336, 336, 328, 288, 128, 0, 0},
        .steps = nfckeys_steps,
        .step_count = COUNT_OF(nfckeys_steps),
    },
    {
        .id = "rfid-t5577",
        .title = "T5577 Cloning",
        .badge = "Clone Smith",
        .track = PocketLabTrackRfid,
        .xp = 55,
        .icon = {0, 2046, 1026, 1530, 1290, 1386, 1386, 1290, 1530, 1026, 2046, 0},
        .steps = t5577_steps,
        .step_count = COUNT_OF(t5577_steps),
    },
    {
        .id = "ir-protocols",
        .title = "IR Protocols",
        .badge = "Signal Decoder",
        .track = PocketLabTrackInfrared,
        .xp = 55,
        .icon = {0, 1638, 1638, 2044, 408, 0, 2906, 2906, 0, 0},
        .steps = irproto_steps,
        .step_count = COUNT_OF(irproto_steps),
    },
    {
        .id = "ibutton-write",
        .title = "iButton Cloning",
        .badge = "Blank Writer",
        .track = PocketLabTrackIbutton,
        .xp = 55,
        .icon = {384, 576, 576, 384, 64, 32, 16, 24, 20, 6},
        .steps = ibtnwrite_steps,
        .step_count = COUNT_OF(ibtnwrite_steps),
    },
    {
        .id = "usb-advanced",
        .title = "Advanced Payloads",
        .badge = "Script Smith",
        .track = PocketLabTrackUsb,
        .xp = 55,
        .icon = {0, 4095, 2049, 2057, 2065, 2081, 2065, 2953, 2049, 4095, 0},
        .steps = usbadv_steps,
        .step_count = COUNT_OF(usbadv_steps),
    },
    {
        .id = "gpio-logic",
        .title = "Logic & Buses",
        .badge = "Bus Analyst",
        .track = PocketLabTrackGpio,
        .xp = 55,
        .icon = {0, 56, 68, 130, 130, 130, 196, 440, 768, 1536, 3072, 0},
        .steps = gpiologic_steps,
        .step_count = COUNT_OF(gpiologic_steps),
    },
};

const size_t pocketlab_labs_count = COUNT_OF(pocketlab_labs);

// --- Content translations (EN -> RU) ---------------------------------------
// Kept in this TU so the EN keys pool with the content string literals above.

typedef struct {
    const char* en;
    const char* ru;
} PocketLabTr;

// Lab/quiz content translations (EN -> RU). Anything not listed falls back to
// English. On-device Flipper menu names stay in English inside instructions.
static const PocketLabTr translations[] = {
    {"Reviewed!", "Уже пройдено!"},
    {"Nice work!", "Отлично!"},
    {"Basics", "Основы"},
    {"Infrared", "ИК-связь"},
    {"Sub-GHz", "Sub-GHz"},
    {"RFID 125 kHz", "RFID 125 кГц"},
    {"NFC", "NFC"},
    {"iButton", "iButton"},
    {"USB / HID", "USB / HID"},
    {"GPIO", "GPIO"},
    {"Bluetooth", "Bluetooth"},
    {"Security", "Безопасность"},
    {"System", "Система"},
    {"Your remote uses invisible infrared light. Flipper can learn and repeat it.",
     "Пульт передаёт ИК-сигнал. Flipper умеет его повторять."},
    {"How it works", "Как это работает"},
    {"A remote blinks an LED in a pattern. Flipper reads it as a command.",
     "Пульт шлёт команду вспышками ИК-светодиода."},
    {"TV remote sends:", "Пульт ТВ передаёт:"},
    {"Infrared light", "Инфракрасный свет"},
    {"Radio waves", "Радиоволны"},
    {"Wi-Fi", "Wi-Fi"},
    {"Ultrasound", "Ультразвук"},
    {"Microwaves", "Микроволны"},
    {"Yes, invisible IR light, not radio.", "Да, это ИК-свет, не радио."},
    {"No, a TV remote sends infrared light.", "Нет, пульт передаёт ИК-сигнал."},
    {"Try it", "Попробуй"},
    {"Open Infrared, Universal Remotes, TV. Aim at a TV and press Power.",
     "Infrared > Universal Remotes > TV. Наведи на ТВ и нажми Power."},
    {"Sub-GHz radio", "Sub-GHz связь"},
    {"Sub-GHz is low radio, like 433 MHz. Key fobs and sensors use it.",
     "Sub-GHz: низкие частоты вроде 433 МГц для брелоков и датчиков."},
    {"Read and replay", "Чтение и повтор"},
    {"Flipper can read a signal and send it back, great for your own remotes.",
     "Flipper считывает и повторяет сигналы твоих пультов."},
    {"Common band is:", "Распространенная частота:"},
    {"433 MHz", "433 МГц"},
    {"2.4 GHz", "2.4 ГГц"},
    {"60 Hz", "60 Гц"},
    {"5 GHz", "5 ГГц"},
    {"50 kHz", "50 кГц"},
    {"1 THz", "1 ТГц"},
    {"Right, 433 MHz is a very common band.", "Верно, 433 МГц часто используется."},
    {"No, 433 MHz is the typical one.", "Нет, типичный - 433 МГц."},
    {"Stay legal", "Соблюдай закон"},
    {"Capture only your own devices. Some bands are limited by law.",
     "Перехватывай лишь свои сигналы. Некоторые частоты ограничены законом."},
    {"Open Sub-GHz, Read, then press your own remote nearby.",
     "Sub-GHz > Read. Нажми кнопку своего пульта."},
    {"Low-freq RFID", "Низкочастотный RFID"},
    {"125 kHz cards are simple ID tags. Office fobs often use EM4100.",
     "Карты 125 кГц - простые ID-метки, часто EM4100."},
    {"Read your tag", "Считай метку"},
    {"Flipper reads the ID and can save or emulate your own card.",
     "Flipper читает ID, сохраняет и эмулирует карту."},
    {"125 kHz RFID is:", "RFID 125 кГц это:"},
    {"Low frequency", "Низкая частота"},
    {"High frequency", "Высокая частота"},
    {"Optical", "Оптика"},
    {"Ultra high freq", "Сверхвысокая"},
    {"Audio band", "Звуковой"},
    {"Microwave", "СВЧ"},
    {"Yes, 125 kHz is low frequency.", "Да, 125 кГц - низкая частота."},
    {"No, 125 kHz is low frequency.", "Нет, 125 кГц - низкая частота."},
    {"Open 125 kHz RFID, Read, and hold your fob to the back.",
     "125 kHz RFID > Read. Приложи брелок сзади."},
    {"NFC cards", "Карты NFC"},
    {"NFC works at 13.56 MHz. Transit and bank cards use it.",
     "NFC работает на 13.56 МГц. Его используют проездные и банковские карты."},
    {"MIFARE", "MIFARE"},
    {"Many access cards are MIFARE. Flipper can read and study your own.",
     "Многие пропуска - MIFARE. Flipper читает и анализирует их."},
    {"NFC frequency:", "Частота NFC:"},
    {"13.56 MHz", "13.56 МГц"},
    {"125 kHz", "125 кГц"},
    {"868 MHz", "868 МГц"},
    {"27 MHz", "27 МГц"},
    {"Correct, NFC runs at 13.56 MHz.", "Верно, NFC: 13.56 МГц."},
    {"No, NFC runs at 13.56 MHz.", "Нет, NFC: 13.56 МГц."},
    {"Be ethical", "Будь этичным"},
    {"Read only cards you own. Never clone someone else's card.",
     "Читай только свои карты. Не клонируй чужие."},
    {"Open NFC, Read, and hold your own card to the back.",
     "NFC > Read. Приложи свою карту сзади."},
    {"iButton keys", "Ключи iButton"},
    {"iButton is a metal contact key, used for intercoms and doors.",
     "iButton - контактный ключ для домофонов и дверей."},
    {"One wire", "Один провод"},
    {"It talks over one wire. Flipper reads and emulates your own keys.",
     "iButton работает по одному проводу; Flipper читает и эмулирует ключи."},
    {"iButton uses:", "iButton использует:"},
    {"Metal contact", "Физический контакт"},
    {"Radio", "Радио"},
    {"Camera", "Камеру"},
    {"Magnetism", "Магнетизм"},
    {"Right, it uses physical contact.", "Верно, нужен физический контакт."},
    {"No, it is contact based.", "Нет, он контактный."},
    {"Open iButton, Read, and touch your key to the pins.",
     "iButton > Read. Коснись ключом контактов."},
    {"Bad USB", "Bad USB"},
    {"Plugged into a PC, Flipper can act as a keyboard and type fast.",
     "При подключении к ПК Flipper работает как клавиатура."},
    {"Ducky scripts", "Ducky-скрипты"},
    {"Scripts send keystrokes, handy for setup and quick demos.",
     "Скрипты имитируют нажатия - удобно для автоматизации и демо."},
    {"Bad USB is a:", "Bad USB это:"},
    {"Keyboard", "Клавиатура"},
    {"Mouse", "Мышь"},
    {"Printer", "Принтер"},
    {"Webcam", "Веб-камера"},
    {"Speaker", "Динамик"},
    {"Monitor", "Монитор"},
    {"Yes, it acts as a keyboard (HID).", "Да, это клавиатура HID."},
    {"No, it acts as a keyboard.", "Нет, это клавиатура."},
    {"Consent first", "Только с разрешения"},
    {"Run it only on computers you own or are allowed to test.",
     "Запускай лишь на своих ПК или с разрешения."},
    {"Open Bad USB, pick a demo, and plug into your own PC.",
     "Bad USB: выбери демо и подключи Flipper к ПК."},
    {"GPIO pins", "Пины GPIO"},
    {"The top pins let Flipper talk to chips and external modules.",
     "Верхние контакты подключают Flipper к чипам и модулям."},
    {"UART", "UART"},
    {"UART is a simple serial link, great for ESP32 boards and sensors.",
     "UART - простой канал для плат ESP32 и датчиков."},
    {"GPIO lets you:", "GPIO позволяет:"},
    {"Add modules", "Добавлять модули"},
    {"Charge faster", "Быстрей заряжать"},
    {"Play music", "Играть музыку"},
    {"Boost Wi-Fi", "Усилить Wi-Fi"},
    {"Extend battery", "Продлить заряд"},
    {"Unlock regions", "Открыть регионы"},
    {"Yes, you can add external modules.", "Да, GPIO подключает модули."},
    {"No, GPIO connects modules.", "Нет, GPIO подключает модули."},
    {"Open GPIO, USB-UART Bridge to see the serial console.",
     "GPIO > USB-UART Bridge: открой консоль."},
    {"Bluetooth LE", "Bluetooth LE"},
    {"Flipper has BLE. It can act as a remote for your phone or PC.",
     "BLE превращает Flipper в пульт для телефона или ПК."},
    {"BLE remote", "BLE-пульт"},
    {"Use it as a media or camera remote over Bluetooth.",
     "Управляй музыкой и камерой по Bluetooth."},
    {"Flipper BLE is:", "Flipper BLE это:"},
    {"Remote control", "Пульт"},
    {"Wi-Fi router", "Wi-Fi роутер"},
    {"GPS", "GPS"},
    {"Modem", "Модем"},
    {"Charger", "Зарядка"},
    {"Yes, it works as a BLE remote.", "Да, это BLE-пульт."},
    {"No, it works as a BLE remote.", "Нет, это BLE-пульт."},
    {"Open Bluetooth Remote and pair it with your phone.",
     "Открой Bluetooth Remote и сопряги с телефоном."},
    {"U2F keys", "Ключи U2F"},
    {"Flipper can act as a security key for two-factor login.",
     "Flipper может быть U2F-ключом для двухфакторного входа."},
    {"How it helps", "Чем помогает"},
    {"Instead of typing a code, you confirm login with the device.",
     "Вместо кода подтверди вход устройством."},
    {"U2F is used for:", "U2F нужен для:"},
    {"Secure login", "Безопасный вход"},
    {"Fast charging", "Быстрая зарядка"},
    {"Louder sound", "Громче звук"},
    {"GPS tracking", "GPS-трекинг"},
    {"Faster Wi-Fi", "Быстрей Wi-Fi"},
    {"Screen mirror", "Зеркало экрана"},
    {"Right, it is for secure login.", "Верно, для безопасного входа."},
    {"No, it is for secure login.", "Нет, для безопасного входа."},
    {"Open U2F and register it on a site that supports keys.",
     "Открой U2F и добавь его на сайт с поддержкой ключей."},
    {"Use it right", "Используй по уму"},
    {"Flipper is a tool. Use it on your own devices only.",
     "Используй Flipper только со своими устройствами."},
    {"Know the rules", "Знай правила"},
    {"Scanning or copying other people's cards can be illegal.",
     "Сканирование и копирование чужих карт может быть незаконным."},
    {"Best practice:", "Как правильно:"},
    {"Only your own", "Только свои устройства"},
    {"Test anything", "Тестить всё"},
    {"Ask nobody", "Никого не спрашивать"},
    {"Copy any card", "Копировать любую"},
    {"Share all keys", "Раздать ключи"},
    {"Ignore the law", "Игнорить закон"},
    {"Yes, work on your own devices only.", "Да, только со своими устройствами."},
    {"No, work on your own devices only.", "Нет, только со своими устройствами."},
    {"Apps catalog", "Каталог приложений"},
    {"Add features with Apps. Browse the catalog in the mobile app.",
     "Функции ставятся через Apps; каталог - в мобильном приложении."},
    {"Firmware", "Прошивка"},
    {"Firmware is the system. Keep it updated for new features.",
     "Прошивка - система Flipper. Обновляй её для новых функций."},
    {"Extra features are:", "Доп. функции это:"},
    {"Apps (.fap)", "Приложения (.fap)"},
    {"Stickers", "Наклейки"},
    {"Batteries", "Батарейки"},
    {"Cables", "Кабели"},
    {"Screen film", "Плёнка"},
    {"Cases", "Чехлы"},
    {"Yes, features come as installable apps.", "Да, функции ставятся как приложения."},
    {"No, they come as installable apps.", "Нет, они идут как приложения."},
    {"Open Apps, browse the list, and launch one you like.",
     "Открой Apps и запусти любое приложение."},
    {"Meet Flipper", "Знакомься, Flipper"},
    {"Flipper Zero is a pocket multi-tool for radio, cards and hardware.",
     "Flipper Zero - мультитул для радио, карт и электроники."},
    {"What it does", "Что он умеет"},
    {"It reads, saves and replays signals from devices you own, and runs apps.",
     "Читает, хранит и повторяет сигналы, запускает приложения."},
    {"Flipper Zero is a:", "Flipper Zero это:"},
    {"Pocket multi-tool", "Карманный мультитул"},
    {"Game console", "Приставка"},
    {"Phone", "Телефон"},
    {"Router", "Роутер"},
    {"Toy only", "Просто игрушка"},
    {"Right, a pocket multi-tool.", "Верно, карманный мультитул."},
    {"It is a pocket multi-tool.", "Это карманный мультитул."},
    {"The SD card", "SD-карта"},
    {"Everything you save lives on the microSD card: keys, signals and apps.",
     "На microSD хранятся ключи, сигналы и приложения."},
    {"Back it up", "Делай бэкап"},
    {"Copy the SD card to your PC now and then, so you never lose your saves.",
     "Иногда копируй microSD на ПК, чтобы не потерять данные."},
    {"Your saves live on:", "Где хранятся сохранения?"},
    {"The cloud", "В облаке"},
    {"Internal only", "Только внутри"},
    {"A server", "На сервере"},
    {"RAM", "В ОЗУ"},
    {"The battery", "В батарее"},
    {"Yes, on the microSD card.", "Да, на microSD-карте."},
    {"They live on the SD card.", "Они на SD-карте."},
    {"Open Settings, Storage to see your SD card usage.",
     "Settings > Storage: проверь память microSD."},
    {"Universal remotes", "Универсальные пульты"},
    {"Flipper ships with IR codes for thousands of TVs, ACs and projectors.",
     "Во Flipper есть ИК-коды тысяч ТВ, кондиционеров и проекторов."},
    {"Power off anything", "Выключай что угодно"},
    {"Cycle through codes to turn off a nearby TV, even without its remote.",
     "Перебирай коды, чтобы выключить ТВ без пульта."},
    {"Universal remotes use:", "Универсальные пульты:"},
    {"Yes, infrared codes.", "Да, инфракрасные коды."},
    {"They use infrared.", "Через ИК-сигнал."},
    {"Open Infrared, Universal Remotes, TV, and press Power.",
     "Infrared > Universal Remotes > TV > Power."},
    {"Find the frequency", "Поиск частот"},
    {"The Frequency Analyzer finds which Sub-GHz frequency a remote uses.",
     "Frequency Analyzer определяет частоту пульта Sub-GHz."},
    {"Why it helps", "Чем помогает"},
    {"Knowing the frequency lets you read the signal on the right band.",
     "Частота укажет нужный диапазон сигнала."},
    {"The analyzer finds:", "Анализатор находит:"},
    {"The frequency", "Частоту"},
    {"The password", "Пароль"},
    {"The brand", "Бренд"},
    {"The distance", "Расстояние"},
    {"The owner", "Владельца"},
    {"Right, the active frequency.", "Верно, активную частоту."},
    {"It finds the frequency.", "Он находит частоту."},
    {"Open Sub-GHz, Frequency Analyzer, and hold your remote's button.",
     "Sub-GHz > Frequency Analyzer. Зажми кнопку пульта."},
    {"Read a signal", "Считай сигнал"},
    {"Sub-GHz Read captures a nearby signal so you can save and study it.",
     "Sub-GHz Read ловит сигнал для сохранения и анализа."},
    {"Replay your own", "Повтори сигнал"},
    {"Send a saved signal back to control your own gate or doorbell.",
     "Повтори сигнал для своих ворот или звонка."},
    {"Never replay:", "Не воспроизводи:"},
    {"Others' devices", "Чужие сигналы"},
    {"Your own remote", "Свой сигнал"},
    {"A test signal", "Тестовый сигнал"},
    {"Your doorbell", "Свой звонок"},
    {"Your gate", "Свои ворота"},
    {"A saved file", "Сохранённый файл"},
    {"Right, only your own devices.", "Верно, только свои."},
    {"Do not replay others' devices.", "Не повторяй чужие сигналы."},
    {"Open Sub-GHz, Read, press your own remote, then Save.",
     "Sub-GHz > Read. Нажми пульт, затем Save."},
    {"Save a tag", "Сохрани метку"},
    {"After reading a 125 kHz tag you can save it under a name.",
     "Метки 125 кГц можно сохранять под именем."},
    {"Emulate it", "Эмулируй её"},
    {"Flipper can pretend to be your saved tag for readers you own.",
     "Flipper эмулирует метку для твоего считывателя."},
    {"125 kHz tags can be:", "Метки 125 кГц можно:"},
    {"Saved and emulated", "Сохранять и эмулировать"},
    {"Charged", "Заряжать"},
    {"Printed", "Печатать"},
    {"Called", "Звонить"},
    {"Painted", "Красить"},
    {"Read only", "Только читать"},
    {"Yes, saved and emulated.", "Да, сохранять и эмулировать."},
    {"They can be saved and emulated.", "Их можно хранить и эмулировать."},
    {"Open 125 kHz RFID, Saved, pick a tag, then Emulate.",
     "125 kHz RFID > Saved > метка > Emulate."},
    {"MIFARE Classic", "MIFARE Classic"},
    {"A common 13.56 MHz card split into sectors, each locked by keys.",
     "Карта 13.56 МГц делится на защищённые ключами секторы."},
    {"Keys and dictionary", "Ключи и словарь"},
    {"Flipper tries a dictionary of common keys to read known sectors.",
     "Flipper перебирает частые ключи для чтения секторов."},
    {"MIFARE is split into:", "MIFARE делится на:"},
    {"Sectors", "Секторы"},
    {"Frames", "Кадры"},
    {"Pixels", "Пиксели"},
    {"Channels", "Каналы"},
    {"Tracks", "Дорожки"},
    {"Pages only", "Только страницы"},
    {"Right, sectors locked by keys.", "Верно, секторы под ключом."},
    {"It is split into sectors.", "Она делится на секторы."},
    {"Read only cards you own. Do not clone other people's cards.",
     "Читай только свои карты. Не клонируй чужие."},
    {"Open NFC, Read, and hold your own MIFARE card.", "NFC > Read. Приложи свою MIFARE-карту."},
    {"DuckyScript", "DuckyScript"},
    {"Bad USB scripts use simple lines like STRING and ENTER.",
     "Bad USB использует команды вроде STRING и ENTER."},
    {"Delays matter", "Задержки важны"},
    {"Add DELAY so the target PC keeps up before the next keystroke.",
     "Добавь DELAY, чтобы ПК успевал реагировать."},
    {"DuckyScript writes:", "DuckyScript пишет:"},
    {"Keystrokes", "Нажатия клавиш"},
    {"Images", "Картинки"},
    {"Sound", "Звук"},
    {"Cards", "Карты"},
    {"Yes, keystrokes.", "Да, нажатия клавиш."},
    {"It writes keystrokes.", "Он имитирует нажатия клавиш."},
    {"Run scripts only on computers you own or may test.",
     "Запускай скрипты лишь на своих ПК или с разрешения."},
    {"Open Bad USB, pick a demo script, plug into your own PC.",
     "Bad USB: выбери демо-скрипт и подключи к ПК."},
    {"Lock your Flipper", "Заблокируй Flipper"},
    {"Set a PIN so nobody can use your Flipper if it is lost.",
     "Задай PIN: он защитит Flipper при потере."},
    {"Safety first", "Безопасность прежде всего"},
    {"A locked Flipper protects your saved keys and cards.",
     "Блокировка защищает сохранённые ключи и карты."},
    {"A PIN lock protects:", "PIN защищает:"},
    {"Your saved data", "Твои данные"},
    {"The screen", "Экран"},
    {"The antenna", "Антенну"},
    {"The speaker", "Динамик"},
    {"The case", "Корпус"},
    {"Right, your saved data.", "Верно, твои данные."},
    {"It protects your saved data.", "Он защищает твои данные."},
    {"Open Settings, Desktop, PIN Setup.", "Settings > Desktop > PIN Setup."},
    {"The buttons", "Кнопки"},
    {"Use the D-pad to move, OK to select, and Back to go up a level.",
     "Крестовина - движение, OK - выбор, Back - назад."},
    {"The main menu", "Главное меню"},
    {"Each icon opens a tool: Sub-GHz, RFID, NFC, Apps and more.",
     "Иконки открывают Sub-GHz, RFID, NFC, Apps и другие функции."},
    {"The Back button:", "Кнопка Back:"},
    {"Goes up a level", "На уровень выше"},
    {"Turns off", "Выключает"},
    {"Deletes", "Удаляет"},
    {"Opens apps", "Открывает apps"},
    {"Locks it", "Блокирует"},
    {"Reboots", "Перезагружает"},
    {"Right, Back goes up a level.", "Верно, Back - назад."},
    {"Back goes up a level.", "Back - на уровень выше."},
    {"Rolling codes", "Динамичные коды"},
    {"Modern car fobs change their code every press, so a replay will not work.",
     "Брелок авто меняет код при каждом нажатии; повтор не сработает."},
    {"Why replay fails", "Почему не повторить?"},
    {"The receiver expects a new code each time and rejects an old one.",
     "Приёмник ждёт новый код и отклоняет старый."},
    {"Rolling codes change:", "Дин. коды меняются:"},
    {"Every press", "Каждое нажатие"},
    {"Never", "Никогда"},
    {"Once a year", "Раз в год"},
    {"On charge", "При зарядке"},
    {"By color", "По цвету"},
    {"At night", "Ночью"},
    {"Right, every press.", "Верно, каждое нажатие."},
    {"They change every press.", "Они меняются каждое нажатие."},
    {"Do not attack cars. Study rolling codes in theory or on your own gear.",
     "Не атакуй авто. Изучай коды лишь на своём оборудовании."},
    {"Card families", "Семейства карт"},
    {"125 kHz tags come in types like EM4100 and HID Prox.",
     "Метки 125 кГц: EM4100, HID Prox и другие."},
    {"Different formats", "Разные форматы"},
    {"Each stores its ID a bit differently, so Flipper labels the type.",
     "Форматы хранят ID по-разному, поэтому Flipper определяет тип."},
    {"EM4100 is a:", "EM4100 это:"},
    {"125 kHz tag", "Метка 125 кГц"},
    {"NFC card", "NFC-карта"},
    {"Bank card", "Банк. карта"},
    {"SIM card", "SIM-карта"},
    {"QR code", "QR-код"},
    {"Barcode", "Штрих-код"},
    {"Yes, a 125 kHz tag.", "Да, метка 125 кГц."},
    {"It is a 125 kHz tag.", "Это метка 125 кГц."},
    {"Open 125 kHz RFID, Read, and note the detected type.", "125 kHz RFID > Read. Запомни тип."},
    {"Emulate a card", "Эмулируй карту"},
    {"Flipper can present a saved NFC card to a reader you own.",
     "Flipper эмулирует NFC-карту для твоего считывателя."},
    {"UID emulation", "Эмуляция UID"},
    {"Simple readers check the card's UID, which Flipper can replay.",
     "Простые считыватели проверяют UID, который Flipper повторяет."},
    {"Emulating means:", "Эмуляция значит:"},
    {"Act as the card", "Работать как карта"},
    {"Print it", "Печатать её"},
    {"Call it", "Звонить ей"},
    {"Charge it", "Заряжать её"},
    {"Delete it", "Удалить её"},
    {"Scan it", "Сканировать её"},
    {"Right, it acts as the card.", "Верно, он эмулирует карту."},
    {"It acts as the card.", "Он выдаёт себя за карту."},
    {"Emulate only your own cards, on your own readers.",
     "Эмулируй свои карты на своих считывателях."},
    {"Open NFC, Saved, pick your card, then Emulate.", "NFC > Saved > карта > Emulate."},
    {"iButton families", "Семейства iButton"},
    {"Common types are Dallas, Cyfral and Metakom.", "Частые типы: Dallas, Cyfral и Metakom."},
    {"Regional use", "Региональные особенности"},
    {"Different intercom brands use different iButton types.",
     "Домофоны используют разные типы iButton."},
    {"A common iButton type:", "Частый тип iButton:"},
    {"Dallas", "Dallas"},
    {"EM4100", "EM4100"},
    {"U2F", "U2F"},
    {"LoRa", "LoRa"},
    {"Zigbee", "Zigbee"},
    {"Yes, Dallas is common.", "Да, Dallas - частый."},
    {"Dallas is a common type.", "Dallas - частый тип."},
    {"Open iButton, Read, and note the detected type.", "iButton > Read. Запомни тип."},
    {"Mouse Jiggler", "Mouse Jiggler"},
    {"Plugged into a PC, Flipper can nudge the mouse to keep it awake.",
     "Flipper двигает мышь, не давая ПК уснуть."},
    {"Handy uses", "Где полезно"},
    {"Stops the screen from sleeping during a long download or read.",
     "Не даёт ПК уснуть при долгой загрузке или чтении."},
    {"Mouse Jiggler keeps the:", "Mouse Jiggler держит:"},
    {"PC awake", "ПК бодрым"},
    {"Fob charged", "Брелок заряженным"},
    {"Card warm", "Карту тёплой"},
    {"Radio on", "Радио вкл"},
    {"Screen off", "Экран выкл"},
    {"App open", "Прил. открытым"},
    {"Right, it keeps the PC awake.", "Верно, он не даёт ПК уснуть."},
    {"It keeps the PC awake.", "Он держит ПК бодрым."},
    {"Open Bad USB, Mouse Jiggler, and plug into your own PC.",
     "Bad USB > Mouse Jiggler. Подключи к ПК."},
    {"WiFi Dev Board", "WiFi Dev Board"},
    {"An ESP32 board on the GPIO adds Wi-Fi to your Flipper.",
     "Плата ESP32 на GPIO добавляет Wi-Fi."},
    {"What it enables", "Что даёт"},
    {"With companion apps it scans and works with Wi-Fi networks.",
     "С нужными приложениями работает с сетями Wi-Fi."},
    {"The WiFi board adds:", "Плата WiFi добавляет:"},
    {"A battery", "Батарею"},
    {"A screen", "Экран"},
    {"A camera", "Камеру"},
    {"Storage", "Память"},
    {"Yes, it adds Wi-Fi.", "Да, она добавляет Wi-Fi."},
    {"It adds Wi-Fi.", "Она добавляет Wi-Fi."},
    {"Test only networks you own or are allowed to.", "Тестируй лишь свои сети или с разрешения."},
    {"Read sensors", "Считывай данные датчиков"},
    {"Over GPIO, Flipper can read sensors like temperature and humidity.",
     "Через GPIO Flipper читает температуру и влажность."},
    {"The I2C bus", "Шина I2C"},
    {"Many sensors talk over I2C, a two-wire bus on the GPIO pins.",
     "Многие датчики используют I2C - двухпроводную шину GPIO."},
    {"I2C uses how many wires:", "Сколько проводов у I2C:"},
    {"Two", "Два"},
    {"One", "Один"},
    {"Four", "Четыре"},
    {"Eight", "Восемь"},
    {"Zero", "Ноль"},
    {"Ten", "Десять"},
    {"Right, two wires.", "Верно, два провода."},
    {"I2C uses two wires.", "У I2C два провода."},
    {"Wire an I2C sensor and open a sensor app like Unitemp.",
     "Подключи I2C-датчик и открой Unitemp или аналог."},
    {"Over Bluetooth, Flipper acts as a remote for your phone or PC.",
     "По Bluetooth Flipper служит пультом для телефона или ПК."},
    {"Media and camera", "Медиа и камера"},
    {"Use it to skip tracks, control slides, or trigger the camera.",
     "Меняй треки, слайды или снимай камерой."},
    {"BLE Remote controls:", "BLE-пульт управляет:"},
    {"Your phone", "Телефоном"},
    {"A car", "Машиной"},
    {"A gate", "Воротами"},
    {"A TV via IR", "ТВ по IR"},
    {"A fob", "Брелоком"},
    {"A card", "Картой"},
    {"Yes, your phone or PC.", "Да, телефоном или ПК."},
    {"It controls your phone or PC.", "Управляет телефоном или ПК."},
    {"Open Bluetooth Remote and pair with your phone.",
     "Открой Bluetooth Remote и подключи телефон."},
    {"Weather sensors", "Метеодатчики"},
    {"Many wireless weather sensors broadcast on Sub-GHz bands.",
     "Многие метеодатчики вещают в Sub-GHz."},
    {"Read the air", "Метеоданные"},
    {"The Weather Station app decodes temperature and humidity nearby.",
     "Weather Station читает ближайшие датчики температуры и влажности."},
    {"Weather sensors use:", "Метеодатчики используют:"},
    {"Right, Sub-GHz radio.", "Верно, радио Sub-GHz."},
    {"They use Sub-GHz radio.", "Они используют радио Sub-GHz."},
    {"Open Sub-GHz, Weather Station, and wait for a reading.",
     "Sub-GHz > Weather Station. Жди показаний."},
    {"Sector keys", "Ключи секторов"},
    {"Each MIFARE Classic sector holds a Key A and Key B in its trailer.",
     "В каждом секторе MIFARE Classic есть Key A и Key B."},
    {"Dictionary first", "Сначала словарь"},
    {"Flipper tries a list of common keys; many cards still use defaults.",
     "Flipper пробует частые ключи; многие карты используют стандартные."},
    {"A sector is unlocked by its:", "Сектор открывается с помощью:"},
    {"Key", "Ключом"},
    {"Colour", "Цветом"},
    {"Voltage", "Напряжением"},
    {"UID only", "Только UID"},
    {"PIN code", "PIN-кодом"},
    {"Antenna", "Антенной"},
    {"Right, Key A or Key B.", "Верно, Key A или Key B."},
    {"It is unlocked by a key.", "Он отпирается ключом."},
    {"MFKey32", "MFKey32"},
    {"Emulate a card to a reader, capture nonces, recover keys offline.",
     "Эмулируй карту, поймай nonce и восстанови ключи офлайн."},
    {"MFKey32 recovers keys from:", "MFKey32 берёт ключи из:"},
    {"Reader nonces", "Nonce считывателя"},
    {"Card photos", "Фото карты"},
    {"The PIN", "PIN"},
    {"Screen taps", "Тапов экрана"},
    {"Yes, from captured reader nonces.", "Да, из nonce считывателя."},
    {"It uses captured reader nonces.", "Использует перехваченные nonce считывателя."},
    {"Nested & hardnested", "Nested и hardnested"},
    {"One known key unlocks others; hardened cards fix the nonce to resist it.",
     "Известный ключ открывает другие; фиксированный nonce мешает этому."},
    {"Ethics", "Этика"},
    {"Recover keys only from cards you own. Cloning access is illegal.",
     "Восстанавливай ключи лишь своих карт. Чужой доступ не клонируй."},
    {"NFC, Detect Reader on your own reader, then run MFKey.",
     "NFC > Detect Reader. Затем запусти MFKey."},
    {"The T5577 blank", "Болванка T5577"},
    {"A writable 125 kHz chip that can mimic EM4100, HID Prox or Indala.",
     "Записываемый чип 125 кГц эмулирует EM4100, HID Prox и Indala."},
    {"Clone flow", "Порядок клон-я"},
    {"Read the source tag, save it, then write it onto a T5577 blank.",
     "Считай метку, сохрани и запиши на T5577."},
    {"A T5577 is special because it is:", "T5577 особенный тем, что он:"},
    {"Writable", "Записываемый"},
    {"Encrypted", "Шифрованный"},
    {"Right, you can write to it.", "Верно, на него можно писать."},
    {"It is a writable blank.", "Это записываемая болванка."},
    {"LF has no crypto", "LF не использует шифрование"},
    {"EM4100 sends a fixed ID with no auth, so LF access control is weak.",
     "EM4100 шлёт ID без защиты, поэтому LF-доступ уязвим."},
    {"EM4100 protects its ID with:", "EM4100 защищает ID:"},
    {"Nothing", "Ничем"},
    {"AES", "AES"},
    {"A password", "Паролем"},
    {"Rolling code", "Динамические коды"},
    {"A key", "Ключом"},
    {"TLS", "TLS"},
    {"Correct, it has no security.", "Верно, у него нет защиты."},
    {"It has no protection at all.", "У него нет защиты вообще."},
    {"Clone only your own fobs. Copying building access is not allowed.",
     "Клонируй лишь свои брелоки. Для чужих нужно разрешение."},
    {"125 kHz RFID, Read your fob, Save, then Write to a T5577.",
     "125 kHz RFID > Read > Save > Write на T5577."},
    {"Parsed vs raw", "Протокол или RAW"},
    {"Remotes speak protocols; Flipper decodes known ones or stores raw timings.",
     "Flipper распознаёт ИК-протоколы или хранит RAW-тайминги."},
    {"NEC & RC5", "NEC и RC5"},
    {"NEC carries an address and command; RC5 and SIRC are other common ones.",
     "NEC несёт адрес и команду; RC5 и SIRC - другие протоколы."},
    {"A NEC frame carries:", "Кадр NEC несёт:"},
    {"Address + command", "Адрес + команда"},
    {"Audio", "Аудио"},
    {"Video", "Видео"},
    {"A photo", "Фото"},
    {"Right, address and command bytes.", "Верно, адрес и команду."},
    {"It carries address and command.", "Он несёт адрес и команду."},
    {"Learn a button", "Считай сигнал кнопки"},
    {"Add a custom remote by capturing one raw signal per button you press.",
     "Сохрани по RAW-сигналу для каждой кнопки пульта."},
    {"Universal TV-off works by:", "Универсальное выключение ТВ:"},
    {"Trying many codes", "Перебор кодов"},
    {"One secret code", "Один секретный код"},
    {"A magnet", "Магнит"},
    {"Yes, it brute-forces a code list.", "Да, перебором кодов."},
    {"It tries many known codes.", "Он пробует много кодов."},
    {"Infrared, Learn New Remote, capture a button from your own remote.",
     "Infrared > Learn New Remote. Считай кнопку пульта."},
    {"Writable keys", "Записываемые ключи"},
    {"RW1990 and similar blanks let you save a read iButton ID onto them.",
     "На RW1990 и аналоги можно записать ID iButton."},
    {"Dallas ROM", "Dallas ROM"},
    {"A Dallas key is a family byte, a unique serial and a CRC check.",
     "Dallas содержит байт семейства, серийный номер и CRC."},
    {"An iButton ID is:", "ID iButton это:"},
    {"Not encrypted", "Не шифрован"},
    {"A radio code", "Радиокод"},
    {"A PIN", "PIN"},
    {"A song", "Песня"},
    {"Right, so it can be copied.", "Верно, его можно скопировать."},
    {"It is unencrypted, so copyable.", "ID не шифруется и копируется."},
    {"The CRC", "CRC"},
    {"A wrong CRC means the reader rejects the key, so it must copy exactly.",
     "Неверный CRC отклонит ключ, поэтому копия должна быть точной."},
    {"Copy only your own keys. Duplicating building keys needs permission.",
     "Копируй лишь свои ключи. Для чужих нужно разрешение."},
    {"iButton, Read your key, Save, then Write to a blank.",
     "iButton > Read > Save > Write на болванку."},
    {"OS-aware payloads", "Пейлоуды под ОС"},
    {"Good scripts branch for Windows, macOS or Linux, since shortcuts differ.",
     "У Windows, macOS и Linux разные хоткеи - учитывай ОС."},
    {"Modifiers", "Модификаторы"},
    {"GUI r opens Run on Windows; combine ALT, CTRL and SHIFT for hotkeys.",
     "GUI r открывает Run; ALT, CTRL и SHIFT создают хоткеи."},
    {"DELAY in a payload gives the PC:", "DELAY в пейлоуде даёт ПК:"},
    {"Time to react", "Время среагировать"},
    {"More colour", "Больше цвета"},
    {"Volume", "Громкость"},
    {"Encryption", "Шифрование"},
    {"Battery", "Батарею"},
    {"Right, timing keeps it reliable.", "Верно, задержки повышают надёжность."},
    {"It gives the PC time to react.", "Даёт ПК время на реакцию."},
    {"Detection", "Обнаружение"},
    {"Security tools flag machine-fast typing, so realistic tests add delays.",
     "Защита замечает быстрый ввод, поэтому добавляй задержки."},
    {"Consent", "Согласие"},
    {"Run payloads only on computers you own or are authorised to test.",
     "Запускай пейлоуды лишь на своих ПК или с разрешения."},
    {"Bad USB, load a demo script, run it on your own PC.",
     "Bad USB: запусти демо-скрипт на своём ПК."},
    {"Reading buses", "Чтение шин"},
    {"Flipper can sniff serial buses on its GPIO to see how devices talk.",
     "Flipper перехватывает обмен по GPIO-шинам."},
    {"UART, SPI, I2C", "UART, SPI, I2C"},
    {"UART needs a shared ground; SPI and I2C add clock and select lines.",
     "UART требует общий GND; SPI и I2C - ещё тактирование и выбор."},
    {"UART between two boards needs a common:", "UART между платами нужен общий:"},
    {"Ground", "Земля"},
    {"Screen", "Экран"},
    {"Right, a shared ground reference.", "Верно, общий провод земли."},
    {"They must share a ground.", "Да, им нужна общая земля."},
    {"Mind the voltage", "Следи за напряжением"},
    {"Flipper GPIO is 3.3V; a 5V line can damage the pins without a divider.",
     "GPIO - 3.3 В; линия 5 В без делителя повредит пины."},
    {"Flipper GPIO logic level is:", "Логический уровень GPIO:"},
    {"3.3V", "3.3В"},
    {"5V", "5В"},
    {"12V", "12В"},
    {"1.5V", "1.5В"},
    {"230V", "230В"},
    {"9V", "9В"},
    {"Right, 3.3V logic.", "Верно, 3.3 В."},
    {"It is 3.3V logic.", "Да, 3.3 В."},
    {"Wire a 3.3V UART device to GPIO and open the UART bridge.",
     "Подключи UART 3.3 В к GPIO и открой UART bridge."},
    {"What is Flipper", "Что такое Flipper"},
    {"First Steps", "Первые шаги"},
    {"SD Card & Backups", "SD-карта и бэкапы"},
    {"Data Keeper", "Хранитель данных"},
    {"IR Basics", "Основы ИК"},
    {"IR Initiate", "Новичок ИК"},
    {"Universal Remotes", "Универсальные пульты"},
    {"Remote Ninja", "Ниндзя пультов"},
    {"Sub-GHz Basics", "Основы Sub-GHz"},
    {"RF Scout", "Радиоразведчик"},
    {"Frequency Analyzer", "Анализатор частот"},
    {"Signal Hunter", "Охотник за сигналом"},
    {"Read & Replay", "Чтение и повтор"},
    {"Replayer", "Повторщик"},
    {"125 kHz RFID", "RFID 125 кГц"},
    {"Tag Reader", "Знаток меток"},
    {"Save & Emulate", "Сохрани и эмулируй"},
    {"Cloner", "Клонер"},
    {"NFC Basics", "Основы NFC"},
    {"NFC Explorer", "Исследователь NFC"},
    {"Sector Sleuth", "Охотник за секторами"},
    {"iButton Keys", "Ключи iButton"},
    {"Key Master", "Мастер ключей"},
    {"HID Novice", "Новичок HID"},
    {"Ducky Writer", "Автор DuckyScript"},
    {"GPIO and UART", "GPIO и UART"},
    {"Pin Wrangler", "Укротитель пинов"},
    {"BLE Tinkerer", "Знаток BLE"},
    {"U2F and 2FA", "U2F и 2FA"},
    {"2FA Guardian", "Страж 2FA"},
    {"PIN Lock & Safety", "PIN-код и защита"},
    {"Guardian", "Страж"},
    {"Ethics and Law", "Этика и закон"},
    {"Responsible", "Ответственный"},
    {"Firmware and Apps", "Прошивка и приложения"},
    {"Power User", "Продвинутый"},
    {"Navigation", "Навигация"},
    {"Navigator", "Навигатор"},
    {"Rolling Codes", "Динамические коды"},
    {"Rolling Master", "Мастер дин. кодов"},
    {"Weather Station", "Метеостанция"},
    {"Weather Watcher", "Ветерок"},
    {"Card Types", "Типы карт"},
    {"Tag Sorter", "Сортировщик меток"},
    {"Emulate NFC", "Эмуляция NFC"},
    {"NFC Emulator", "Эмулятор NFC"},
    {"iButton Types", "Типы iButton"},
    {"Key Collector", "Ключник"},
    {"Jiggler", "Джигглер"},
    {"Board Builder", "Мастер плат"},
    {"Sensors & I2C", "Датчики и I2C"},
    {"Sensor Sage", "Знаток датчиков"},
    {"BLE Remote", "BLE-пульт"},
    {"Remote Master", "Мастер пультов"},
    {"MIFARE Keys", "Ключи MIFARE"},
    {"Key Cracker", "Укратитель ключей"},
    {"T5577 Cloning", "Клонирование T5577"},
    {"Clone Smith", "Кузнец клонов"},
    {"IR Protocols", "ИК-протоколы"},
    {"Signal Decoder", "Декодер сигналов"},
    {"iButton Cloning", "Клонирование iButton"},
    {"Blank Writer", "Ключник"},
    {"Advanced Payloads", "Продвинутые пейлоуды"},
    {"Script Smith", "Кузнец скриптов"},
    {"Logic & Buses", "Логика и шины"},
    {"Bus Analyst", "Аналитик шин"},
};

const char* pocketlab_tr(const char* en) {
    if(!en) return "";
    if(pocketlab_i18n_get_lang() != PocketLabLangRu) return en;
    for(size_t i = 0; i < COUNT_OF(translations); i++) {
        if(strcmp(translations[i].en, en) == 0) {
            return translations[i].ru[0] ? translations[i].ru : en;
        }
    }
    return en;
}
