#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xf5b3;
constexpr uint24_t FX_DATA_BYTES = 670939;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Levels
{
  constexpr uint24_t Invaders_Items = 0x000000;
  constexpr uint24_t Level1_FG = 0x000189;
  constexpr uint24_t Level1_BG = 0x0004B3;
  constexpr uint24_t level1_Data = 0x0007DD;
  constexpr uint24_t Level1_Items = 0x000818;
  constexpr uint24_t Level2_FG = 0x0009A0;
  constexpr uint24_t Level2_BG = 0x000FB8;
  constexpr uint24_t level2_Data = 0x0015D0;
  constexpr uint24_t Level2_Items = 0x00160B;
  constexpr uint24_t Level3_FG = 0x001793;
  constexpr uint24_t Level3_BG = 0x001CD9;
  constexpr uint24_t level3_Data = 0x00221F;
  constexpr uint24_t Level3_Items = 0x00225A;
  constexpr uint24_t Level4_FG = 0x0023DA;
  constexpr uint24_t Level4_BG = 0x002812;
  constexpr uint24_t level4_Data = 0x002C4A;
  constexpr uint24_t Level4_Items = 0x002C85;
  constexpr uint24_t Level5_FG = 0x002E0D;
  constexpr uint24_t Level5_BG = 0x003353;
  constexpr uint24_t level5_Data = 0x003899;
  constexpr uint24_t Level5_Items = 0x0038D4;
  constexpr uint24_t Level6_FG = 0x003A5C;
  constexpr uint24_t Level6_BG = 0x003CD2;
  constexpr uint24_t level6_Data = 0x003F48;
  constexpr uint24_t Level6_Items = 0x003F83;
  constexpr uint24_t Level7_FG = 0x004103;
  constexpr uint24_t Level7_BG = 0x00453B;
  constexpr uint24_t level7_Data = 0x004973;
  constexpr uint24_t Level7_Items = 0x0049AE;
  constexpr uint24_t Level8_FG = 0x004B36;
  constexpr uint24_t Level8_BG = 0x00505E;
  constexpr uint24_t level8_Data = 0x005586;
  constexpr uint24_t Level8_Items = 0x0055C1;
  constexpr uint24_t Level9_FG = 0x005749;
  constexpr uint24_t Level9_BG = 0x005B09;
  constexpr uint24_t level9_Data = 0x005EC9;
  constexpr uint24_t Level9_Items = 0x005F04;
  constexpr uint24_t Level10_FG = 0x00608C;
  constexpr uint24_t Level10_BG = 0x00635C;
  constexpr uint24_t level10_Data = 0x00662C;
  constexpr uint24_t Level10_Items = 0x006667;
  constexpr uint24_t Level11_FG = 0x0067EF;
  constexpr uint24_t Level11_BG = 0x006C27;
  constexpr uint24_t level11_Data = 0x00705F;
  constexpr uint24_t Level11_Items = 0x00709A;
  constexpr uint24_t Level12_FG = 0x007222;
  constexpr uint24_t Level12_BG = 0x0078B2;
  constexpr uint24_t level12_Data = 0x007F42;
  constexpr uint24_t Level12_Items = 0x007F7D;
  constexpr uint24_t Level13_FG = 0x008105;
  constexpr uint24_t Level13_BG = 0x0081B9;
  constexpr uint24_t level13_Data = 0x00826D;
  constexpr uint24_t Level13_Items = 0x0082A8;
  constexpr uint24_t level_FG = 0x008430;
  constexpr uint24_t Level_BG = 0x00845A;
  constexpr uint24_t level_Data = 0x008484;
  constexpr uint24_t Level_Items = 0x0084AE;
}

namespace Sounds
{
  constexpr uint24_t Dead = 0x0084D8;
  constexpr uint24_t Grab1 = 0x0084F6;
  constexpr uint24_t Grab2 = 0x008520;
  constexpr uint24_t Grab3 = 0x00854A;
  constexpr uint24_t Grab4 = 0x008584;
  constexpr uint24_t Seque = 0x0085DA;
  constexpr uint24_t Tada = 0x008828;
  constexpr uint24_t Theme = 0x008846;
  constexpr uint24_t Triumph = 0x008A14;
  constexpr uint24_t Victory = 0x008A32;
  constexpr uint24_t Ending = 0x008AA4;
  constexpr uint24_t OutOfTime = 0x008BF6;
  constexpr uint24_t GateGoingDown = 0x008C3C;
  constexpr uint24_t GateGoingUp = 0x008C7A;
  constexpr uint24_t ChopChop = 0x008CB8;
  constexpr uint24_t Thump = 0x008CCA;
  constexpr uint24_t Strike = 0x008CDC;
  constexpr uint24_t Invader_Wave_Start = 0x008CEA;
  constexpr uint24_t Invader_Wave_Success = 0x008D18;
  constexpr uint24_t Invader_End_of_Game = 0x008DBE;
  constexpr uint24_t Invader_Player_Fires_Bullet = 0x008E04;
  constexpr uint24_t Invader_Enemy_Fires_Bullet = 0x008E12;
  constexpr uint24_t Invader_Player_Explosion = 0x008E20;
  constexpr uint24_t Invader_Enemy_Explosion = 0x008E6A;
  constexpr uint24_t Invader_Hit_Barrier = 0x008EB4;
  constexpr uint24_t Step = 0x008EBE;
  constexpr uint24_t Table = 0x008EC4;
}

namespace Images
{
  constexpr uint24_t PPOT = 0x008F12;
  constexpr uint16_t PPOT_WIDTH  = 65;
  constexpr uint16_t PPOTHEIGHT  = 31;
  constexpr uint8_t  PPOT_FRAMES = 4;

  constexpr uint24_t Title_PoP = 0x009326;
  constexpr uint16_t Title_PoP_width  = 128;
  constexpr uint16_t Title_PoP_height = 33;

  constexpr uint24_t Title_PoA = 0x00982A;
  constexpr uint16_t Title_PoA_width  = 128;
  constexpr uint16_t Title_PoA_height = 33;

  constexpr uint24_t Title_Main_NC = 0x009D2E;
  constexpr uint16_t Title_Main_NC_width  = 128;
  constexpr uint16_t Title_Main_NC_height = 88;

  constexpr uint24_t Title_Main_NRC = 0x00A2B2;
  constexpr uint16_t Title_Main_NRC_width  = 128;
  constexpr uint16_t Title_Main_NRC_height = 88;

  constexpr uint24_t Title_Main_NCH = 0x00A836;
  constexpr uint16_t Title_Main_NCH_width  = 128;
  constexpr uint16_t Title_Main_NCH_height = 88;

  constexpr uint24_t Title_Main_NRCH = 0x00ADBA;
  constexpr uint16_t Title_Main_NRCH_width  = 128;
  constexpr uint16_t Title_Main_NRCH_height = 88;

  constexpr uint24_t Title_Cursor = 0x00B33E;
  constexpr uint16_t Title_Cursor_width  = 5;
  constexpr uint16_t Title_Cursor_height = 5;

  constexpr uint24_t Title_SoundIcon = 0x00B347;
  constexpr uint16_t Title_SoundIcon_width  = 8;
  constexpr uint16_t Title_SoundIcon_height = 8;
  constexpr uint8_t  Title_SoundIcon_frames = 2;

  constexpr uint24_t Title_Credits = 0x00B35B;
  constexpr uint16_t Title_Credits_width  = 73;
  constexpr uint16_t Title_Credits_height = 136;

  constexpr uint24_t Saves = 0x00B838;
  constexpr uint16_t SavesWidth  = 128;
  constexpr uint16_t SavesHeight = 5;

  constexpr uint24_t TimeRemaining = 0x00B8BC;
  constexpr uint16_t TimeRemainingWidth  = 81;
  constexpr uint16_t TimeRemainingHeight = 15;

  constexpr uint24_t LevelNumber = 0x00BA04;
  constexpr uint16_t LevelNumberWidth  = 81;
  constexpr uint16_t LevelNumberHeight = 15;

  constexpr uint24_t PressA = 0x00BB4C;
  constexpr uint16_t PressAWidth  = 79;
  constexpr uint16_t PressAHeight = 15;

  constexpr uint24_t TimeOut_PoP = 0x00BC8C;
  constexpr uint16_t TimeOut_PoP_width  = 86;
  constexpr uint16_t TimeOut_PoP_height = 114;

  constexpr uint24_t TimeOut_PoA = 0x00C19A;
  constexpr uint16_t TimeOut_PoA_width  = 86;
  constexpr uint16_t TimeOut_PoA_height = 114;

  constexpr uint24_t IntroGame_1A = 0x00C6A8;
  constexpr uint16_t IntroGame_1A_width  = 118;
  constexpr uint16_t IntroGame_1A_height = 96;

  constexpr uint24_t IntroGame_1B = 0x00CC34;
  constexpr uint16_t IntroGame_1B_width  = 123;
  constexpr uint16_t IntroGame_1B_height = 96;

  constexpr uint24_t IntroGame_9_PoP = 0x00D1FC;
  constexpr uint16_t IntroGame_9_PoP_width  = 123;
  constexpr uint16_t IntroGame_9_PoP_height = 160;

  constexpr uint24_t IntroGame_9_PoA = 0x00DB9C;
  constexpr uint16_t IntroGame_9_PoA_width  = 123;
  constexpr uint16_t IntroGame_9_PoA_height = 160;

  constexpr uint24_t Chambers_BG = 0x00E53C;
  constexpr uint16_t Chambers_BG_width  = 128;
  constexpr uint16_t Chambers_BG_height = 64;

  constexpr uint24_t Chambers_BG_01 = 0x00E940;
  constexpr uint16_t Chambers_BG_01_width  = 128;
  constexpr uint16_t Chambers_BG_01_height = 55;

  constexpr uint24_t Chambers_BG_02 = 0x00ECC4;
  constexpr uint16_t Chambers_BG_02_width  = 128;
  constexpr uint16_t Chambers_BG_02_height = 9;

  constexpr uint24_t Chambers_FG = 0x00EDC8;
  constexpr uint16_t Chambers_FG_width  = 128;
  constexpr uint16_t Chambers_FG_height = 64;

  constexpr uint24_t Credits_BG = 0x00F5CC;
  constexpr uint16_t Credits_BG_width  = 128;
  constexpr uint16_t Credits_BG_height = 9;

  constexpr uint24_t Eeek = 0x00F6D0;
  constexpr uint16_t EeekWidth  = 43;
  constexpr uint16_t EeekHeight = 19;

  constexpr uint24_t LevelRect = 0x00F7D6;
  constexpr uint16_t LevelRectWidth  = 16;
  constexpr uint16_t LevelRectHeight = 8;

  constexpr uint24_t Mouse = 0x00F7EA;
  constexpr uint16_t MouseWidth  = 16;
  constexpr uint16_t MouseHeight = 16;
  constexpr uint8_t  MouseFrames = 3;

  constexpr uint24_t HourGlasses = 0x00F8AE;
  constexpr uint16_t HourGlassesWidth  = 19;
  constexpr uint16_t HourGlassesHeight = 23;
  constexpr uint8_t  HourGlassesFrames = 6;

  constexpr uint24_t Menu = 0x00FB5E;
  constexpr uint16_t MenuWidth  = 42;
  constexpr uint16_t MenuHeight = 64;
  constexpr uint8_t  MenuFrames = 8;

  constexpr uint24_t Sword_Cursor = 0x0105E2;
  constexpr uint16_t Sword_Cursor_width  = 8;
  constexpr uint16_t Sword_Cursor_height = 10;

  constexpr uint24_t HUD_Backgrounds = 0x0105F6;
  constexpr uint16_t HUD_Backgrounds_width  = 8;
  constexpr uint16_t HUD_Backgrounds_height = 64;
  constexpr uint8_t  HUD_Backgrounds_frames = 3;

  constexpr uint24_t Numbers_Upright = 0x0106BA;
  constexpr uint16_t Numbers_Upright_width  = 7;
  constexpr uint16_t Numbers_Upright_height = 5;
  constexpr uint8_t  Numbers_Upright_frames = 100;

  constexpr uint24_t Numbers = 0x01097A;
  constexpr uint16_t NumbersWidth  = 11;
  constexpr uint16_t NumbersHeight = 7;
  constexpr uint8_t  NumbersFrames = 60;

  constexpr uint24_t Numbers_Large = 0x010C12;
  constexpr uint16_t Numbers_Large_width  = 22;
  constexpr uint16_t Numbers_Large_height = 14;
  constexpr uint8_t  Numbers_Large_frames = 60;

  constexpr uint24_t Numbers_Small = 0x011666;
  constexpr uint16_t Numbers_Small_width  = 5;
  constexpr uint16_t Numbers_Small_height = 7;
  constexpr uint8_t  Numbers_Small_frames = 100;

  constexpr uint24_t Numbers_Divider = 0x01185E;
  constexpr uint16_t Numbers_Divider_width  = 4;
  constexpr uint16_t Numbers_Divider_height = 8;

  constexpr uint24_t Healths = 0x011866;
  constexpr uint16_t HealthsWidth  = 5;
  constexpr uint16_t HealthsHeight = 3;
  constexpr uint8_t  HealthsFrames = 2;

  constexpr uint24_t Sword_HUD = 0x011874;
  constexpr uint16_t Sword_HUD_width  = 5;
  constexpr uint16_t Sword_HUD_height = 5;

  constexpr uint24_t Potion_Float_HUD = 0x01187D;
  constexpr uint16_t Potion_Float_HUD_width  = 5;
  constexpr uint16_t Potion_Float_HUD_height = 5;

  constexpr uint24_t HighScore = 0x011886;
  constexpr uint16_t HighScoreWidth  = 52;
  constexpr uint16_t HighScoreHeight = 5;

  constexpr uint24_t Sword = 0x0118BE;
  constexpr uint16_t SwordWidth  = 14;
  constexpr uint16_t SwordHeight = 5;

  constexpr uint24_t Skeleton = 0x0118DE;
  constexpr uint16_t SkeletonWidth  = 15;
  constexpr uint16_t SkeletonHeight = 12;

  constexpr uint24_t Gates = 0x01191E;
  constexpr uint16_t GatesWidth  = 9;
  constexpr uint16_t GatesHeight = 28;
  constexpr uint8_t  GatesFrames = 10;

  constexpr uint24_t Blades = 0x011BF2;
  constexpr uint16_t BladesWidth  = 9;
  constexpr uint16_t BladesHeight = 28;
  constexpr uint8_t  BladesFrames = 12;

  constexpr uint24_t ExitDoors = 0x011F56;
  constexpr uint16_t ExitDoorsWidth  = 25;
  constexpr uint16_t ExitDoorsHeight = 33;
  constexpr uint8_t  ExitDoorsFrames = 13;

  constexpr uint24_t Potions_Small = 0x0125B3;
  constexpr uint16_t Potions_Small_width  = 6;
  constexpr uint16_t Potions_Small_height = 15;
  constexpr uint8_t  Potions_Small_frames = 2;

  constexpr uint24_t Potions_Large = 0x0125E7;
  constexpr uint16_t Potions_Large_width  = 6;
  constexpr uint16_t Potions_Large_height = 15;
  constexpr uint8_t  Potions_Large_frames = 2;

  constexpr uint24_t Potions_Poison = 0x01261B;
  constexpr uint16_t Potions_Poison_width  = 6;
  constexpr uint16_t Potions_Poison_height = 15;
  constexpr uint8_t  Potions_Poison_frames = 6;

  constexpr uint24_t Potions_Float = 0x0126AF;
  constexpr uint16_t Potions_Float_width  = 6;
  constexpr uint16_t Potions_Float_height = 15;
  constexpr uint8_t  Potions_Float_frames = 7;

  constexpr uint24_t DecorativeDoor = 0x01275B;
  constexpr uint16_t DecorativeDoorWidth  = 23;
  constexpr uint16_t DecorativeDoorHeight = 40;

  constexpr uint24_t CollapsedFloor = 0x0127D2;
  constexpr uint16_t CollapsedFloorWidth  = 21;
  constexpr uint16_t CollapsedFloorHeight = 13;

  constexpr uint24_t CollapsingFloors = 0x01282A;
  constexpr uint16_t CollapsingFloorsWidth  = 21;
  constexpr uint16_t CollapsingFloorsHeight = 31;
  constexpr uint8_t  CollapsingFloorsFrames = 4;

  constexpr uint24_t FloorButtons_0and1 = 0x012ACE;
  constexpr uint16_t FloorButtons_0and1_width  = 21;
  constexpr uint16_t FloorButtons_0and1_height = 32;
  constexpr uint8_t  FloorButtons_0and1_frames = 4;

  constexpr uint24_t FloorButtons_2 = 0x012D72;
  constexpr uint16_t FloorButtons_2_width  = 12;
  constexpr uint16_t FloorButtons_2_height = 31;
  constexpr uint8_t  FloorButtons_2_frames = 2;

  constexpr uint24_t CollapsingFloors_FG = 0x012E36;
  constexpr uint16_t CollapsingFloors_FG_width  = 21;
  constexpr uint16_t CollapsingFloors_FG_height = 31;
  constexpr uint8_t  CollapsingFloors_FG_frames = 4;

  constexpr uint24_t FloorButtons_0and1_FG = 0x0130DA;
  constexpr uint16_t FloorButtons_0and1_FG_width  = 21;
  constexpr uint16_t FloorButtons_0and1_FG_height = 32;
  constexpr uint8_t  FloorButtons_0and1_FG_frames = 4;

  constexpr uint24_t FloorButtons_2_FG = 0x01337E;
  constexpr uint16_t FloorButtons_2_FG_width  = 12;
  constexpr uint16_t FloorButtons_2_FG_height = 31;
  constexpr uint8_t  FloorButtons_2_FG_frames = 2;

  constexpr uint24_t Torches = 0x013442;
  constexpr uint16_t TorchesWidth  = 3;
  constexpr uint16_t TorchesHeight = 11;
  constexpr uint8_t  TorchesFrames = 5;

  constexpr uint24_t Mirrors = 0x013482;
  constexpr uint16_t MirrorsWidth  = 12;
  constexpr uint16_t MirrorsHeight = 31;
  constexpr uint8_t  MirrorsFrames = 2;

  constexpr uint24_t Spikes_FG_Full = 0x0134E6;
  constexpr uint16_t Spikes_FG_Full_width  = 19;
  constexpr uint16_t Spikes_FG_Full_height = 18;
  constexpr uint8_t  Spikes_FG_Full_frames = 5;

  constexpr uint24_t Spikes_BG_Full = 0x013724;
  constexpr uint16_t Spikes_BG_Full_width  = 19;
  constexpr uint16_t Spikes_BG_Full_height = 18;
  constexpr uint8_t  Spikes_BG_Full_frames = 5;

  constexpr uint24_t Spikes_FG_Half = 0x013962;
  constexpr uint16_t Spikes_FG_Half_width  = 11;
  constexpr uint16_t Spikes_FG_Half_height = 18;
  constexpr uint8_t  Spikes_FG_Half_frames = 5;

  constexpr uint24_t Spikes_BG_Half = 0x013AB0;
  constexpr uint16_t Spikes_BG_Half_width  = 11;
  constexpr uint16_t Spikes_BG_Half_height = 18;
  constexpr uint8_t  Spikes_BG_Half_frames = 5;

  constexpr uint24_t Flashes = 0x013BFE;
  constexpr uint16_t FlashesWidth  = 22;
  constexpr uint16_t FlashesHeight = 20;
  constexpr uint8_t  FlashesFrames = 4;

  constexpr uint24_t Tiles_Dungeon = 0x013E12;
  constexpr uint16_t Tiles_Dungeon_width  = 12;
  constexpr uint16_t Tiles_Dungeon_height = 31;
  constexpr uint8_t  Tiles_Dungeon_frames = 100;

  constexpr uint24_t Tile_Dungeon_97 = 0x016396;
  constexpr uint16_t Tile_Dungeon_97_width  = 21;
  constexpr uint16_t Tile_Dungeon_97_height = 31;

  constexpr uint24_t Tile_Dungeon_98 = 0x016442;
  constexpr uint16_t Tile_Dungeon_98_width  = 12;
  constexpr uint16_t Tile_Dungeon_98_height = 31;

  constexpr uint24_t Tile_Dungeon_98_FG = 0x0164A6;
  constexpr uint16_t Tile_Dungeon_98_FG_width  = 12;
  constexpr uint16_t Tile_Dungeon_98_FG_height = 31;

  constexpr uint24_t Tiles_Dungeon_Torch = 0x01650A;
  constexpr uint16_t Tiles_Dungeon_Torch_width  = 12;
  constexpr uint16_t Tiles_Dungeon_Torch_height = 31;
  constexpr uint8_t  Tiles_Dungeon_Torch_frames = 5;

  constexpr uint24_t Princess = 0x0165FE;
  constexpr uint16_t PrincessWidth  = 32;
  constexpr uint16_t PrincessHeight = 32;
  constexpr uint8_t  PrincessFrames = 33;

  constexpr uint24_t Princess_Bounce = 0x018702;
  constexpr uint16_t Princess_Bounce_width  = 48;
  constexpr uint16_t Princess_Bounce_height = 32;
  constexpr uint8_t  Princess_Bounce_frames = 17;

  constexpr uint24_t Hearts = 0x01A086;
  constexpr uint16_t HeartsWidth  = 7;
  constexpr uint16_t HeartsHeight = 6;
  constexpr uint8_t  HeartsFrames = 4;

  constexpr uint24_t Jaffar = 0x01A0A6;
  constexpr uint16_t JaffarWidth  = 32;
  constexpr uint16_t JaffarHeight = 32;
  constexpr uint8_t  JaffarFrames = 26;

  constexpr uint24_t Prince_Left = 0x01BAAA;
  constexpr uint16_t Prince_Left_width  = 36;
  constexpr uint16_t Prince_Left_height = 36;
  constexpr uint8_t  Prince_Left_frames = 199;

  constexpr uint24_t Prince_Right = 0x02D286;
  constexpr uint16_t Prince_Right_width  = 36;
  constexpr uint16_t Prince_Right_height = 36;
  constexpr uint8_t  Prince_Right_frames = 199;

  constexpr uint24_t Mirror_Right = 0x03EA62;
  constexpr uint16_t Mirror_Right_width  = 36;
  constexpr uint16_t Mirror_Right_height = 36;
  constexpr uint8_t  Mirror_Right_frames = 111;

  constexpr uint24_t Mirror_Left = 0x04867E;
  constexpr uint16_t Mirror_Left_width  = 36;
  constexpr uint16_t Mirror_Left_height = 36;
  constexpr uint8_t  Mirror_Left_frames = 111;

  constexpr uint24_t Enemy_Right = 0x05229A;
  constexpr uint16_t Enemy_Right_width  = 36;
  constexpr uint16_t Enemy_Right_height = 36;
  constexpr uint8_t  Enemy_Right_frames = 38;

  constexpr uint24_t Enemy_Left = 0x05580E;
  constexpr uint16_t Enemy_Left_width  = 36;
  constexpr uint16_t Enemy_Left_height = 36;
  constexpr uint8_t  Enemy_Left_frames = 38;

  constexpr uint24_t Skeleton_Right = 0x058D82;
  constexpr uint16_t Skeleton_Right_width  = 36;
  constexpr uint16_t Skeleton_Right_height = 36;
  constexpr uint8_t  Skeleton_Right_frames = 38;

  constexpr uint24_t Skeleton_Left = 0x05C2F6;
  constexpr uint16_t Skeleton_Left_width  = 36;
  constexpr uint16_t Skeleton_Left_height = 36;
  constexpr uint8_t  Skeleton_Left_frames = 38;

  constexpr uint24_t Invaders = 0x05F86A;
  constexpr uint16_t InvadersWidth  = 25;
  constexpr uint16_t InvadersHeight = 23;
  constexpr uint8_t  InvadersFrames = 18;

  constexpr uint24_t Barriers = 0x0602FA;
  constexpr uint16_t BarriersWidth  = 4;
  constexpr uint16_t BarriersHeight = 2;
  constexpr uint8_t  BarriersFrames = 16;

  constexpr uint24_t Barrier = 0x06037E;
  constexpr uint16_t BarrierWidth  = 16;
  constexpr uint16_t BarrierHeight = 4;

  constexpr uint24_t Player = 0x060392;
  constexpr uint16_t PlayerWidth  = 25;
  constexpr uint16_t PlayerHeight = 25;
  constexpr uint8_t  PlayerFrames = 5;

  constexpr uint24_t Bullet = 0x06077E;
  constexpr uint16_t BulletWidth  = 1;
  constexpr uint16_t BulletHeight = 3;

  constexpr uint24_t HUD_Spaceship = 0x060783;
  constexpr uint16_t HUD_Spaceship_width  = 4;
  constexpr uint16_t HUD_Spaceship_height = 17;
  constexpr uint8_t  HUD_Spaceship_frames = 4;

  constexpr uint24_t Levels = 0x0607B7;
  constexpr uint16_t LevelsWidth  = 57;
  constexpr uint16_t LevelsHeight = 13;
  constexpr uint8_t  LevelsFrames = 5;

  constexpr uint24_t Falling_000 = 0x060C2F;
  constexpr uint16_t Falling_000_width  = 128;
  constexpr uint16_t Falling_000_height = 64;

  constexpr uint24_t Falling_001 = 0x061033;
  constexpr uint16_t Falling_001_width  = 128;
  constexpr uint16_t Falling_001_height = 64;

  constexpr uint24_t Falling_002 = 0x061437;
  constexpr uint16_t Falling_002_width  = 128;
  constexpr uint16_t Falling_002_height = 64;

  constexpr uint24_t Falling_003 = 0x06183B;
  constexpr uint16_t Falling_003_width  = 128;
  constexpr uint16_t Falling_003_height = 64;

  constexpr uint24_t Falling_004 = 0x061C3F;
  constexpr uint16_t Falling_004_width  = 128;
  constexpr uint16_t Falling_004_height = 64;

  constexpr uint24_t Falling_005 = 0x062043;
  constexpr uint16_t Falling_005_width  = 128;
  constexpr uint16_t Falling_005_height = 64;

  constexpr uint24_t Falling_006 = 0x062447;
  constexpr uint16_t Falling_006_width  = 128;
  constexpr uint16_t Falling_006_height = 64;

  constexpr uint24_t Falling_007 = 0x06284B;
  constexpr uint16_t Falling_007_width  = 128;
  constexpr uint16_t Falling_007_height = 64;

  constexpr uint24_t Falling_008 = 0x062C4F;
  constexpr uint16_t Falling_008_width  = 128;
  constexpr uint16_t Falling_008_height = 64;

  constexpr uint24_t Falling_009 = 0x063053;
  constexpr uint16_t Falling_009_width  = 128;
  constexpr uint16_t Falling_009_height = 64;

  constexpr uint24_t Falling_010 = 0x063457;
  constexpr uint16_t Falling_010_width  = 128;
  constexpr uint16_t Falling_010_height = 64;

  constexpr uint24_t Falling_011 = 0x06385B;
  constexpr uint16_t Falling_011_width  = 128;
  constexpr uint16_t Falling_011_height = 64;

  constexpr uint24_t Falling_012 = 0x063C5F;
  constexpr uint16_t Falling_012_width  = 128;
  constexpr uint16_t Falling_012_height = 64;

  constexpr uint24_t Falling_013 = 0x064063;
  constexpr uint16_t Falling_013_width  = 128;
  constexpr uint16_t Falling_013_height = 64;

  constexpr uint24_t Falling_014 = 0x064467;
  constexpr uint16_t Falling_014_width  = 128;
  constexpr uint16_t Falling_014_height = 64;

  constexpr uint24_t Falling_015 = 0x06486B;
  constexpr uint16_t Falling_015_width  = 128;
  constexpr uint16_t Falling_015_height = 64;

  constexpr uint24_t Falling_016 = 0x064C6F;
  constexpr uint16_t Falling_016_width  = 128;
  constexpr uint16_t Falling_016_height = 64;

  constexpr uint24_t Falling_017 = 0x065073;
  constexpr uint16_t Falling_017_width  = 128;
  constexpr uint16_t Falling_017_height = 64;

  constexpr uint24_t Falling_018 = 0x065477;
  constexpr uint16_t Falling_018_width  = 128;
  constexpr uint16_t Falling_018_height = 64;

  constexpr uint24_t Falling_019 = 0x06587B;
  constexpr uint16_t Falling_019_width  = 128;
  constexpr uint16_t Falling_019_height = 64;

  constexpr uint24_t Falling_020 = 0x065C7F;
  constexpr uint16_t Falling_020_width  = 128;
  constexpr uint16_t Falling_020_height = 64;

  constexpr uint24_t Falling_021 = 0x066083;
  constexpr uint16_t Falling_021_width  = 128;
  constexpr uint16_t Falling_021_height = 64;

  constexpr uint24_t Falling_022 = 0x066487;
  constexpr uint16_t Falling_022_width  = 128;
  constexpr uint16_t Falling_022_height = 64;

  constexpr uint24_t Falling_023 = 0x06688B;
  constexpr uint16_t Falling_023_width  = 128;
  constexpr uint16_t Falling_023_height = 64;

  constexpr uint24_t Falling_024 = 0x066C8F;
  constexpr uint16_t Falling_024_width  = 128;
  constexpr uint16_t Falling_024_height = 64;

  constexpr uint24_t Falling_025 = 0x067093;
  constexpr uint16_t Falling_025_width  = 128;
  constexpr uint16_t Falling_025_height = 64;

  constexpr uint24_t Falling_026 = 0x067497;
  constexpr uint16_t Falling_026_width  = 128;
  constexpr uint16_t Falling_026_height = 64;

  constexpr uint24_t Falling_027 = 0x06789B;
  constexpr uint16_t Falling_027_width  = 128;
  constexpr uint16_t Falling_027_height = 64;

  constexpr uint24_t Falling_028 = 0x067C9F;
  constexpr uint16_t Falling_028_width  = 128;
  constexpr uint16_t Falling_028_height = 64;

  constexpr uint24_t Falling_029 = 0x0680A3;
  constexpr uint16_t Falling_029_width  = 128;
  constexpr uint16_t Falling_029_height = 64;

  constexpr uint24_t Falling_030 = 0x0684A7;
  constexpr uint16_t Falling_030_width  = 128;
  constexpr uint16_t Falling_030_height = 64;

  constexpr uint24_t Falling_031 = 0x0688AB;
  constexpr uint16_t Falling_031_width  = 128;
  constexpr uint16_t Falling_031_height = 64;

  constexpr uint24_t Falling_032 = 0x068CAF;
  constexpr uint16_t Falling_032_width  = 128;
  constexpr uint16_t Falling_032_height = 64;

  constexpr uint24_t Falling_033 = 0x0690B3;
  constexpr uint16_t Falling_033_width  = 128;
  constexpr uint16_t Falling_033_height = 64;

  constexpr uint24_t Falling_034 = 0x0694B7;
  constexpr uint16_t Falling_034_width  = 128;
  constexpr uint16_t Falling_034_height = 64;

  constexpr uint24_t Falling_035 = 0x0698BB;
  constexpr uint16_t Falling_035_width  = 128;
  constexpr uint16_t Falling_035_height = 64;

  constexpr uint24_t Falling_036 = 0x069CBF;
  constexpr uint16_t Falling_036_width  = 128;
  constexpr uint16_t Falling_036_height = 64;

  constexpr uint24_t Falling_037 = 0x06A0C3;
  constexpr uint16_t Falling_037_width  = 128;
  constexpr uint16_t Falling_037_height = 64;

  constexpr uint24_t Falling_038 = 0x06A4C7;
  constexpr uint16_t Falling_038_width  = 128;
  constexpr uint16_t Falling_038_height = 64;

  constexpr uint24_t Falling_039 = 0x06A8CB;
  constexpr uint16_t Falling_039_width  = 128;
  constexpr uint16_t Falling_039_height = 64;

  constexpr uint24_t Falling_040 = 0x06ACCF;
  constexpr uint16_t Falling_040_width  = 128;
  constexpr uint16_t Falling_040_height = 64;

  constexpr uint24_t Falling_041 = 0x06B0D3;
  constexpr uint16_t Falling_041_width  = 128;
  constexpr uint16_t Falling_041_height = 64;

  constexpr uint24_t Falling_042 = 0x06B4D7;
  constexpr uint16_t Falling_042_width  = 128;
  constexpr uint16_t Falling_042_height = 64;

  constexpr uint24_t Falling_043 = 0x06B8DB;
  constexpr uint16_t Falling_043_width  = 128;
  constexpr uint16_t Falling_043_height = 64;

  constexpr uint24_t Falling_044 = 0x06BCDF;
  constexpr uint16_t Falling_044_width  = 128;
  constexpr uint16_t Falling_044_height = 64;

  constexpr uint24_t Falling_045 = 0x06C0E3;
  constexpr uint16_t Falling_045_width  = 128;
  constexpr uint16_t Falling_045_height = 64;

  constexpr uint24_t Falling_046 = 0x06C4E7;
  constexpr uint16_t Falling_046_width  = 128;
  constexpr uint16_t Falling_046_height = 64;

  constexpr uint24_t Falling_047 = 0x06C8EB;
  constexpr uint16_t Falling_047_width  = 128;
  constexpr uint16_t Falling_047_height = 64;

  constexpr uint24_t Falling_048 = 0x06CCEF;
  constexpr uint16_t Falling_048_width  = 128;
  constexpr uint16_t Falling_048_height = 64;

  constexpr uint24_t Falling_049 = 0x06D0F3;
  constexpr uint16_t Falling_049_width  = 128;
  constexpr uint16_t Falling_049_height = 64;

  constexpr uint24_t Falling_050 = 0x06D4F7;
  constexpr uint16_t Falling_050_width  = 128;
  constexpr uint16_t Falling_050_height = 64;

  constexpr uint24_t Falling_051 = 0x06D8FB;
  constexpr uint16_t Falling_051_width  = 128;
  constexpr uint16_t Falling_051_height = 64;

  constexpr uint24_t Falling_052 = 0x06DCFF;
  constexpr uint16_t Falling_052_width  = 128;
  constexpr uint16_t Falling_052_height = 64;

  constexpr uint24_t Falling_053 = 0x06E103;
  constexpr uint16_t Falling_053_width  = 128;
  constexpr uint16_t Falling_053_height = 64;

  constexpr uint24_t Falling_054 = 0x06E507;
  constexpr uint16_t Falling_054_width  = 128;
  constexpr uint16_t Falling_054_height = 64;

  constexpr uint24_t Falling_055 = 0x06E90B;
  constexpr uint16_t Falling_055_width  = 128;
  constexpr uint16_t Falling_055_height = 64;

  constexpr uint24_t Falling_056 = 0x06ED0F;
  constexpr uint16_t Falling_056_width  = 128;
  constexpr uint16_t Falling_056_height = 64;

  constexpr uint24_t Falling_057 = 0x06F113;
  constexpr uint16_t Falling_057_width  = 128;
  constexpr uint16_t Falling_057_height = 64;

  constexpr uint24_t Falling_058 = 0x06F517;
  constexpr uint16_t Falling_058_width  = 128;
  constexpr uint16_t Falling_058_height = 64;

  constexpr uint24_t Falling_059 = 0x06F91B;
  constexpr uint16_t Falling_059_width  = 128;
  constexpr uint16_t Falling_059_height = 64;

  constexpr uint24_t Falling_060 = 0x06FD1F;
  constexpr uint16_t Falling_060_width  = 128;
  constexpr uint16_t Falling_060_height = 64;

  constexpr uint24_t Falling_061 = 0x070123;
  constexpr uint16_t Falling_061_width  = 128;
  constexpr uint16_t Falling_061_height = 64;

  constexpr uint24_t Falling_062 = 0x070527;
  constexpr uint16_t Falling_062_width  = 128;
  constexpr uint16_t Falling_062_height = 64;

  constexpr uint24_t Falling_063 = 0x07092B;
  constexpr uint16_t Falling_063_width  = 128;
  constexpr uint16_t Falling_063_height = 64;

  constexpr uint24_t Falling_064 = 0x070D2F;
  constexpr uint16_t Falling_064_width  = 128;
  constexpr uint16_t Falling_064_height = 64;

  constexpr uint24_t Falling_065 = 0x071133;
  constexpr uint16_t Falling_065_width  = 128;
  constexpr uint16_t Falling_065_height = 64;

  constexpr uint24_t Falling_066 = 0x071537;
  constexpr uint16_t Falling_066_width  = 128;
  constexpr uint16_t Falling_066_height = 64;

  constexpr uint24_t Falling_067 = 0x07193B;
  constexpr uint16_t Falling_067_width  = 128;
  constexpr uint16_t Falling_067_height = 64;

  constexpr uint24_t Falling_068 = 0x071D3F;
  constexpr uint16_t Falling_068_width  = 128;
  constexpr uint16_t Falling_068_height = 64;

  constexpr uint24_t Falling_069 = 0x072143;
  constexpr uint16_t Falling_069_width  = 128;
  constexpr uint16_t Falling_069_height = 64;

  constexpr uint24_t Falling_070 = 0x072547;
  constexpr uint16_t Falling_070_width  = 128;
  constexpr uint16_t Falling_070_height = 64;

  constexpr uint24_t Falling_071 = 0x07294B;
  constexpr uint16_t Falling_071_width  = 128;
  constexpr uint16_t Falling_071_height = 64;

  constexpr uint24_t Falling_072 = 0x072D4F;
  constexpr uint16_t Falling_072_width  = 128;
  constexpr uint16_t Falling_072_height = 64;

  constexpr uint24_t Falling_073 = 0x073153;
  constexpr uint16_t Falling_073_width  = 128;
  constexpr uint16_t Falling_073_height = 64;

  constexpr uint24_t Falling_074 = 0x073557;
  constexpr uint16_t Falling_074_width  = 128;
  constexpr uint16_t Falling_074_height = 64;

  constexpr uint24_t Falling_075 = 0x07395B;
  constexpr uint16_t Falling_075_width  = 128;
  constexpr uint16_t Falling_075_height = 64;

  constexpr uint24_t Falling_076 = 0x073D5F;
  constexpr uint16_t Falling_076_width  = 128;
  constexpr uint16_t Falling_076_height = 64;

  constexpr uint24_t Falling_077 = 0x074163;
  constexpr uint16_t Falling_077_width  = 128;
  constexpr uint16_t Falling_077_height = 64;

  constexpr uint24_t Falling_078 = 0x074567;
  constexpr uint16_t Falling_078_width  = 128;
  constexpr uint16_t Falling_078_height = 64;

  constexpr uint24_t Falling_079 = 0x07496B;
  constexpr uint16_t Falling_079_width  = 128;
  constexpr uint16_t Falling_079_height = 64;

  constexpr uint24_t Falling_080 = 0x074D6F;
  constexpr uint16_t Falling_080_width  = 128;
  constexpr uint16_t Falling_080_height = 64;

  constexpr uint24_t Falling_081 = 0x075173;
  constexpr uint16_t Falling_081_width  = 128;
  constexpr uint16_t Falling_081_height = 64;

  constexpr uint24_t Falling_082 = 0x075577;
  constexpr uint16_t Falling_082_width  = 128;
  constexpr uint16_t Falling_082_height = 64;

  constexpr uint24_t Falling_083 = 0x07597B;
  constexpr uint16_t Falling_083_width  = 128;
  constexpr uint16_t Falling_083_height = 64;

  constexpr uint24_t Falling_084 = 0x075D7F;
  constexpr uint16_t Falling_084_width  = 128;
  constexpr uint16_t Falling_084_height = 64;

  constexpr uint24_t Falling_085 = 0x076183;
  constexpr uint16_t Falling_085_width  = 128;
  constexpr uint16_t Falling_085_height = 64;

  constexpr uint24_t Falling_086 = 0x076587;
  constexpr uint16_t Falling_086_width  = 128;
  constexpr uint16_t Falling_086_height = 64;

  constexpr uint24_t Falling_087 = 0x07698B;
  constexpr uint16_t Falling_087_width  = 128;
  constexpr uint16_t Falling_087_height = 64;

  constexpr uint24_t Falling_088 = 0x076D8F;
  constexpr uint16_t Falling_088_width  = 128;
  constexpr uint16_t Falling_088_height = 64;

  constexpr uint24_t Falling_089 = 0x077193;
  constexpr uint16_t Falling_089_width  = 128;
  constexpr uint16_t Falling_089_height = 64;

  constexpr uint24_t Falling_090 = 0x077597;
  constexpr uint16_t Falling_090_width  = 128;
  constexpr uint16_t Falling_090_height = 64;

  constexpr uint24_t Falling_091 = 0x07799B;
  constexpr uint16_t Falling_091_width  = 128;
  constexpr uint16_t Falling_091_height = 64;

  constexpr uint24_t Falling_092 = 0x077D9F;
  constexpr uint16_t Falling_092_width  = 128;
  constexpr uint16_t Falling_092_height = 64;

  constexpr uint24_t Falling_093 = 0x0781A3;
  constexpr uint16_t Falling_093_width  = 128;
  constexpr uint16_t Falling_093_height = 64;

  constexpr uint24_t Falling_094 = 0x0785A7;
  constexpr uint16_t Falling_094_width  = 128;
  constexpr uint16_t Falling_094_height = 64;

  constexpr uint24_t Falling_095 = 0x0789AB;
  constexpr uint16_t Falling_095_width  = 128;
  constexpr uint16_t Falling_095_height = 64;

  constexpr uint24_t Falling_096 = 0x078DAF;
  constexpr uint16_t Falling_096_width  = 128;
  constexpr uint16_t Falling_096_height = 64;

  constexpr uint24_t Falling_097 = 0x0791B3;
  constexpr uint16_t Falling_097_width  = 128;
  constexpr uint16_t Falling_097_height = 64;

  constexpr uint24_t Falling_098 = 0x0795B7;
  constexpr uint16_t Falling_098_width  = 128;
  constexpr uint16_t Falling_098_height = 64;

  constexpr uint24_t Falling_099 = 0x0799BB;
  constexpr uint16_t Falling_099_width  = 128;
  constexpr uint16_t Falling_099_height = 64;

  constexpr uint24_t Falling_100 = 0x079DBF;
  constexpr uint16_t Falling_100_width  = 128;
  constexpr uint16_t Falling_100_height = 64;

  constexpr uint24_t Falling_101 = 0x07A1C3;
  constexpr uint16_t Falling_101_width  = 128;
  constexpr uint16_t Falling_101_height = 64;

  constexpr uint24_t Falling_102 = 0x07A5C7;
  constexpr uint16_t Falling_102_width  = 128;
  constexpr uint16_t Falling_102_height = 64;

  constexpr uint24_t Falling_103 = 0x07A9CB;
  constexpr uint16_t Falling_103_width  = 128;
  constexpr uint16_t Falling_103_height = 64;

  constexpr uint24_t Falling_104 = 0x07ADCF;
  constexpr uint16_t Falling_104_width  = 128;
  constexpr uint16_t Falling_104_height = 64;

  constexpr uint24_t Falling_105 = 0x07B1D3;
  constexpr uint16_t Falling_105_width  = 128;
  constexpr uint16_t Falling_105_height = 64;

  constexpr uint24_t Falling_106 = 0x07B5D7;
  constexpr uint16_t Falling_106_width  = 128;
  constexpr uint16_t Falling_106_height = 64;

  constexpr uint24_t Falling_107 = 0x07B9DB;
  constexpr uint16_t Falling_107_width  = 128;
  constexpr uint16_t Falling_107_height = 64;

  constexpr uint24_t Falling_108 = 0x07BDDF;
  constexpr uint16_t Falling_108_width  = 128;
  constexpr uint16_t Falling_108_height = 64;

  constexpr uint24_t Falling_109 = 0x07C1E3;
  constexpr uint16_t Falling_109_width  = 128;
  constexpr uint16_t Falling_109_height = 64;

  constexpr uint24_t Falling_110 = 0x07C5E7;
  constexpr uint16_t Falling_110_width  = 128;
  constexpr uint16_t Falling_110_height = 64;

  constexpr uint24_t Falling_111 = 0x07C9EB;
  constexpr uint16_t Falling_111_width  = 128;
  constexpr uint16_t Falling_111_height = 64;

  constexpr uint24_t Falling_112 = 0x07CDEF;
  constexpr uint16_t Falling_112_width  = 128;
  constexpr uint16_t Falling_112_height = 64;

  constexpr uint24_t Falling_113 = 0x07D1F3;
  constexpr uint16_t Falling_113_width  = 128;
  constexpr uint16_t Falling_113_height = 64;

  constexpr uint24_t Falling_114 = 0x07D5F7;
  constexpr uint16_t Falling_114_width  = 128;
  constexpr uint16_t Falling_114_height = 64;

  constexpr uint24_t Falling_115 = 0x07D9FB;
  constexpr uint16_t Falling_115_width  = 128;
  constexpr uint16_t Falling_115_height = 64;

}

namespace Constants
{
  constexpr uint24_t StanceToImageXRefFX = 0x07DDFF;
}

namespace Constants
{
  constexpr uint24_t Stance_XYOffsetsFX = 0x07E15B;
}

namespace Constants
{
  constexpr uint24_t VertAdjustments = 0x07E811;
  constexpr uint24_t Prince_ImageDetails = 0x07E8A7;
}

constexpr uint24_t splashScreen_Frame = 0x07EAFC;
constexpr uint24_t Title_Main_Game_PoP_Frame_NC = 0x07EB20;
constexpr uint24_t Title_Main_Game_PoA_Frame_NC = 0x07EB32;
constexpr uint24_t Title_Main_Game_PoP_Frame_NCH = 0x07EB44;
constexpr uint24_t Title_Main_Game_PoA_Frame_NCH = 0x07EB56;
constexpr uint24_t Title_Main_Game_PoP_Frame_NRC = 0x07EB68;
constexpr uint24_t Title_Main_Game_PoA_Frame_NRC = 0x07EB7A;
constexpr uint24_t Title_Main_Game_PoP_Frame_NRCH = 0x07EB8C;
constexpr uint24_t Title_Main_Game_PoA_Frame_NRCH = 0x07EB9E;
constexpr uint24_t Title_High_PoP_Frame = 0x07EBB0;
constexpr uint24_t Title_High_PoA_Frame = 0x07EC52;
constexpr uint24_t Title_Select_Option = 0x07ECF4;
constexpr uint24_t Title_Cursor_XPos = 0x07ED14;
constexpr uint24_t MenuControlDataTable = 0x07ED24;
constexpr uint24_t MenuRenderDataTable = 0x07ED74;
constexpr uint24_t Invaders_HUD_frame = 0x07EDC4;
constexpr uint24_t Title_Intro_PoP_Frame_NC = 0x07EDD6;
constexpr uint24_t Title_Intro_Last_PoP_Frame_NC = 0x07F256;
constexpr uint24_t Title_Intro_PoP_Frame_NCH = 0x07F268;
constexpr uint24_t Title_Intro_Last_PoP_Frame_NCH = 0x07F6E8;
constexpr uint24_t Title_Intro_PoP_Frame_NRC = 0x07F6FA;
constexpr uint24_t Title_Intro_Last_PoP_Frame_NRC = 0x07FB7A;
constexpr uint24_t Title_Intro_PoP_Frame_NRCH = 0x07FB8C;
constexpr uint24_t Title_Intro_Last_PoP_Frame_NRCH = 0x08000C;
constexpr uint24_t Title_Intro_PoA_Frame_NC = 0x08001E;
constexpr uint24_t Title_Intro_Last_PoA_Frame_NC = 0x08049E;
constexpr uint24_t Title_Intro_PoA_Frame_NCH = 0x0804B0;
constexpr uint24_t Title_Intro_Last_PoA_Frame_NCH = 0x080930;
constexpr uint24_t Title_Intro_PoA_Frame_NRC = 0x080942;
constexpr uint24_t Title_Intro_Last_PoA_Frame_NRC = 0x080DC2;
constexpr uint24_t Title_Intro_PoA_Frame_NRCH = 0x080DD4;
constexpr uint24_t Title_Intro_Last_PoA_Frame_NRCH = 0x081254;
constexpr uint24_t Title_Main_PoP_Frame_NC = 0x081266;
constexpr uint24_t Title_Main_Last_PoP_Frame_NC = 0x0813F2;
constexpr uint24_t Title_Main_PoP_Frame_NCH = 0x081404;
constexpr uint24_t Title_Main_Last_PoP_Frame_NCH = 0x081590;
constexpr uint24_t Title_Main_PoP_Frame_NRC = 0x0815A2;
constexpr uint24_t Title_Main_Last_PoP_Frame_NRC = 0x08172E;
constexpr uint24_t Title_Main_PoP_Frame_NRCH = 0x081740;
constexpr uint24_t Title_Main_Last_PoP_Frame_NRCH = 0x0818CC;
constexpr uint24_t Title_Main_PoA_Frame_NC = 0x0818DE;
constexpr uint24_t Title_Main_Last_PoA_Frame_NC = 0x081A6A;
constexpr uint24_t Title_Main_PoA_Frame_NCH = 0x081A7C;
constexpr uint24_t Title_Main_Last_PoA_Frame_NCH = 0x081C08;
constexpr uint24_t Title_Main_PoA_Frame_NRC = 0x081C1A;
constexpr uint24_t Title_Main_Last_PoA_Frame_NRC = 0x081DA6;
constexpr uint24_t Title_Main_PoA_Frame_NRCH = 0x081DB8;
constexpr uint24_t Title_Main_Last_PoA_Frame_NRCH = 0x081F44;
constexpr uint24_t Title_Credits_PoP_Frame = 0x081F56;
constexpr uint24_t Title_Credits_PoA_Frame = 0x0850CD;
constexpr uint24_t Title_TimeOut_PoP_Frame = 0x088244;
constexpr uint24_t Title_TimeOut_PoA_Frame = 0x08AEC6;
constexpr uint24_t Title_IntroGame_1A_Frame = 0x08DB48;
constexpr uint24_t Title_CutScene_1_Frame = 0x08E11E;
constexpr uint24_t Title_IntroGame_1B_Frame = 0x09162B;
constexpr uint24_t Title_CutScene_2_Frame = 0x091C01;
constexpr uint24_t Title_CutScene_2B_Frame = 0x093041;
constexpr uint24_t Title_CutScene_3_Frame = 0x095F81;
constexpr uint24_t Title_CutScene_4_Frame = 0x0973C1;
constexpr uint24_t Title_CutScene_5_Frame = 0x097DE1;
constexpr uint24_t Title_CutScene_6_Frame = 0x099365;
constexpr uint24_t Title_CutScene_7_Frame = 0x09BE2E;
constexpr uint24_t Title_CutScene_8_Frame = 0x0A0A54;
constexpr uint24_t Title_CutScene_End_Frame = 0x0A0E83;
constexpr uint24_t Title_IntroGame_End_PoP_Frame = 0x0A28F3;
constexpr uint24_t Title_IntroGame_End_PoA_Frame = 0x0A313F;
constexpr uint24_t TitleFrameIndexTable = 0x0A398B;
constexpr uint24_t RunningJumpStances = 0x0A3A8B;
constexpr uint24_t StandingJumpStances = 0x0A3C1B;
