name: "FAP: Build and Release MQ-3 Alcometer"

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Build FAP'
    steps:
      - name: Checkout your code
        uses: actions/checkout@v4

      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-app
        with:
          sdk-channel: dev

      - name: Upload .fap file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: MQ-3-Alcometer-${{ github.sha }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download built .fap artifact
        uses: actions/download-artifact@v4
        with:
          name: MQ-3-Alcometer-${{ github.sha }}
          path: dist/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "MQ-3 Alcometer ${{ github.ref_name }}"
          body: |
            ## Что нового в этой версии?
            - Первый публичный релиз
            - Измерение алкоголя в mg/l
            - Автоматическая калибровка
            - Ведение лога измерений
          draft: false
          prerelease: false
          files: dist/*.fap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
