#pragma once

// Optional compiler optimization directives (currently disabled)
//#pragma GCC optimize("O3")           // Maximum optimization level
//#pragma GCC optimize("tree-vectorize") // Enable vectorization
//#pragma GCC optimize("unroll-loops")   // Basic loop unrolling
//#pragma GCC optimize("unroll-all-loops") // Aggressive loop unrolling

/**
 * Generates a key from an index value for brute force attempts
 * The key is generated by bit-shifting parts of the index into specific positions
 * This creates a pattern that covers the most likely key combinations first
 * 
 * @param index Current attempt number (0 to 2^28-1)
 * @param key_mode Which 4-byte segment of the key to modify (0-3)
 * @param key_out Output buffer for the generated key (16 bytes)
 */
void calculate_key_from_index(uint32_t index, uint8_t key_mode, uint8_t* key_out) {
    // Clear key buffer using 32-bit operations for efficiency
    uint32_t* key32 = (uint32_t*)key_out;
    key32[0] = 0;
    key32[1] = 0;
    key32[2] = 0;
    key32[3] = 0;

    // Pack and store directly to the correct position in one operation
    // Splits index into 4 parts and arranges them in optimal testing order:
    key32[key_mode] = ((index & 0x0000007F) << 25) | // Lowest 7 bits -> highest byte
                      ((index & 0x00003F80) << 10) | // Next 7 bits -> second byte
                      ((index & 0x001FC000) >> 5) | // Next 7 bits -> third byte
                      ((index & 0x0FE00000) >> 20); // Highest 7 bits -> lowest byte
}

/**
 * Formats a segment of the key into a human-readable hex string
 * Used for displaying key attempts and the found key
 * 
 * @param str Output string buffer
 * @param str_size Size of output buffer
 * @param key Source key buffer
 * @param offset Starting position in key buffer
 */
void format_key_segment(char* str, size_t str_size, const uint8_t* key, size_t offset) {
    // Format 8 bytes of key data as hex pairs with space in middle
    // Example output: "01234567 89ABCDEF"
    snprintf(
        str,
        str_size,
        "%02X%02X%02X%02X %02X%02X%02X%02X",
        key[offset], // First byte
        key[offset + 1], // Second byte
        key[offset + 2], // Third byte
        key[offset + 3], // Fourth byte
        key[offset + 4], // Fifth byte
        key[offset + 5], // Sixth byte
        key[offset + 6], // Seventh byte
        key[offset + 7] // Eighth byte
    );
}
